### ISSUE TITLE
support for redis password/ACLs?

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#1000]
I'm debating with myself over how much sense this would make here, but I don't currently see a way to use a redis password (--requirepass) or ACLs.

A password stored in the redis config file or set using --requirepass will be transmitted in plaintext anyways iirc, so ACLs might make more sense to increase security. If I get this right, the parameter set used when creating the Predis\Client object in /core/cacheengine.php:117 can be extended to also include a password (and a username which would be required for ACLs):
```
            $redis = new \Predis\Client([
                'scheme' => 'tcp',
                'host' => $hp[0],
                'port' => (int)$hp[1]
            ], ['prefix' => 'shm:']);
```
But I have no idea what the connection string in shimmie.conf.php would have to look like, or how much complexity this would add in other places.

Anyway, just a thought :)

**Comment by shish** [comment]
The CACHE_DSN setting is using a URL-like format (and now that I think about it, I wonder why it is being parsed with regex instead of a URL parser...) - so there should be a fairly standard way to add username / password

**Comment by Giraffaman** [comment]
already using it - thank you!
