### ISSUE TITLE
No indication or error handling when an upload exceeds imagemagick's limits

### ISSUE THREAD

**Issue by Ayutac** [shish/shimmie2#1006]
**Server Software**
about:
  title: "Wandering Inn Fanworks"
  theme: "twi"
  url: "https://twifanworks.shelter.moe/"

versions:
  shimmie: "b1dc9892d5c5d728c631512c16ea19359fd3b35b"
  schema: 21
  php: "8.1.2-1ubuntu2.14"
  db: "pgsql PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit"
  os: "Linux shelterv4 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64"
  server: "Apache"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["autocomplete","emoticons_list","et_server","favorites","graphql","handle_mp3","handle_svg","handle_video","home","image_view_counter","link_image","ouroboros_api","pools","post_titles","random_list","rating","regen_thumb","relationships","report_image","rotate","rss_comments","rss_images","rule34","sitemap","source_history","tag_categories","tag_editcloud","tag_history","tag_tools","tagger_xml","transcode","transcode_video"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","audio/mpeg","image/svg+xml","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]

stats:
  images: 4113
  comments: 302
  users: 93

media:
  memory_limit: "500.0MB"
  disk_use: "510.3GB"
  disk_total: "687.9GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

**Client Software (please complete the following information)**
 - Device: Xubuntu
 - Browser: Chrome Version 120.0.6099.129 (Official Build) (64-bit)

**What steps trigger this bug**
1. Upload JPG with very unquadratic measurements like 23622x2362 and a big file size like 15 MB
2. Bonus Points if you click on generate thumbnail afterwards

**What did you expect to happen?**
A thumbnail being generated.

**What actually happened?**
No thumbnail being generated.

from https://twifanworks.shelter.moe/post/list/artist%3Asocs/1 (sfw)
![image](https://github.com/shish/shimmie2/assets/7873396/9936810a-73ee-4041-89ef-b22e6598afa4)

There also seems to be no way to upload a custom thumbnail.

**Comment by shish** [comment]
Looking in my error logs when I try to upload the same image on my own board, it appears to be exceeding ImageMagick's limits :O

`2024-01-09T17:47:52+0000 127.0.0.1 handle_pixel demo Error while creating thumbnail: Resizing image with command `convert   -auto-orient -strip jpg:"/tmp/phpqBN89F[0]" -thumbnail 192x192 -background "#000000" -flatten  -quality 75    jpg:"data/thumbs/9c/9c48fcacb9d60d72f66f87dbc6fbca53" 2>&1`, returns 1, outputting convert-im6.q16: width or height exceeds limit `/tmp/phpqBN89F' @ error/cache.c/OpenPixelCache/3909.`


> There also seems to be no way to upload a custom thumbnail.

That is correct - you are welcome to make a separate feature request for that (or a pull request if you're feeling up to it)

**Comment by shish** [comment]
c16aeca4 should make this clearer where the error is, but also means blocking the upload completely when there are internal system errors, instead of getting into a weird half-uploaded state. For getting the thumbnail process to succeed you'll need to update imagemagick's limits - for ubuntu I think this is `/etc/ImageMagick-6/policy.xml` with the lines

```
  <policy domain="resource" name="width" value="16KP"/>
  <policy domain="resource" name="height" value="16KP"/>
  <policy domain="resource" name="area" value="128MP"/>
```

**Comment by shish** [comment]
I suspect that in cases where the image is too large for third-party software to handle, detecting that failure and letting the user know is the best we can do, so I'm considering this fixed -- though if you have better ideas for how to handle this situation I am open to suggestions ^^
