### ISSUE TITLE
Tag box is 1 or 2 px too small in height

### ISSUE THREAD

**Issue by Ayutac** [shish/shimmie2#1009]
**Server Software**
about:
  title: "Wandering Inn Fanworks"
  theme: "twi"
  url: "https://fanworks.wanderinginn.com/"

versions:
  shimmie: "2.10.0-beta2+" (will add in exact commit number later)
  schema: 21
  php: "8.1.2-1ubuntu2.14"
  db: "pgsql PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit"
  os: "Linux shelterv4 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64"
  server: "Apache"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","replace_file","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["autocomplete","emoticons_list","et_server","favorites","graphql","handle_mp3","handle_svg","handle_video","home","image_view_counter","link_image","pools","post_titles","random_list","rating","regen_thumb","relationships","report_image","rotate","rss_comments","rss_images","sitemap","source_history","tag_categories","tag_editcloud","tag_history","tag_tools","tagger_xml","transcode","transcode_video"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","audio/mpeg","image/svg+xml","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]

stats:
  images: 4233
  comments: 310
  users: 96

media:
  memory_limit: "500MB"
  disk_use: "511GB"
  disk_total: "688GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

**Client Software (please complete the following information)**
 - Device: Xubuntu
 - Browser: Chrome Version 120.0.6099.129 (Official Build) (64-bit)

**What steps trigger this bug**
1. Edit any image
2. Enter a couple of tags with _ in their names
3. Save and edit again.

**What did you expect to happen?**
Being able to read all tags with no ambiguity.

**What actually happened?**
The underscore character is just low enough to not be visible in the last line of the tags, making it difficult to see if it is there or a space.

![image](https://github.com/shish/shimmie2/assets/7873396/4b8627f3-93ab-4b31-8a60-1c21b13bbcc8)

**Comment by shish** [comment]
Thank you~ I've added a .5em buffer which should make this more readable and look nice :3
