### ISSUE TITLE
Upload attempted, but nothing succeeded and nothing failed?

### ISSUE THREAD

**Issue by shakealeg** [shish/shimmie2#1010]
**Server Software**
 - Shimmie version: 2.10.0-beta2+
 - Database: sqlite 3.40.1
 - Web server: PHP 8.2.7 Development Server

**Client Software**
 - Device: Gentoo GNU/Linux-libre
 - Browser: GNU IceCat

**What steps trigger this bug**
1. Attempt to upload file larger than 8MB

**What did you expect to happen?**
For the file to upload successfully without any issues.

**What actually happened?**
Got an error message in return saying the following:
```
No images uploaded
Upload attempted, but nothing succeeded and nothing failed?
```
PHP Development Server shows no errors or warnings, just "Accepting" and "Closing". I have slow internet (~2mb/s) and it takes about 5 minutes to upload a ~30MB file, but after that 5 minutes, it shows that error.
This has also happened on Szurubooru and Danbooru (self-hosted). The only things that worked were: Rsync, Element Web, and Nextcloud.
I'm not sure what else to provide, but please just ask and I'll give it over without hesitation.

**Comment by shish** [comment]
Hmm, this normally happens when one uploads a file that is larger than the webserver is configured to handle, and the webserver ends up ignoring the file before shimmie even sees it, but I'm not sure of a great way to know for sure if that's happening 🤔

**Comment by shakealeg** [comment]
> Hmm, this normally happens when one uploads a file that is larger than the webserver is configured to handle, and the webserver ends up ignoring the file before shimmie even sees it, but I'm not sure of a great way to know for sure if that's happening 🤔

post_max_size inside /etc/php/8.2/cli/php.ini was set to 8MB max, changing to 99999MB fixed it entirely.
NGINX has also caused issues with Shimmie, at least for me. No matter how high you set the timeout or max client body size, it won't upload. If you found this issue on google, I recommend you switch to another one and see if that works. Apache for example.
Issue solved.
