### ISSUE TITLE
Viewing user_admin/list as Admin is Broken

### ISSUE THREAD

**Issue by NottyNoz** [shish/shimmie2#1019]
**Server Software**
  shimmie: "2.10.0-20240117-6020c15"
  schema: 21
  php: "8.1.2-1ubuntu2.14"
  db: "mysql 8.0.35-0ubuntu0.22.04.1"
  os: "Linux vps-7eb368be 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64"
  server: "nginx/1.18.0"

**Client Software (please complete the following information)**
 - Device: windows desktop
 - Browser: firefox and chrome
 
**What steps trigger this bug**
1. Visit user_admin/list with the DELETE_USER permission.

**What did you expect to happen?**
for the page not to break

**What actually happened?**
the page broke

https://github.com/shish/shimmie2/tree/main/ext/user/main.php#L193
I think this TextColumn call is causing issues for some reason. I can see that the `email` column exists in the `users` db table and is populated. I had just upgraded shimmie2 directly from 2.9.2 to 2.10.0. The page works perfectly fine for normal users that can't see the email column.

var_dump($col); -> `object(MicroCRUD\TextColumn)#274 (3) { ["name"]=> string(5) "email" ["title"]=> string(5) "Email" ["table"]=> uninitialized(MicroCRUD\Table) ["sortable"]=> bool(true) }`

`Fatal error: Uncaught TypeError: MicroCRUD\Column::display(): Return value must be of type MicroHTML\HTMLElement|string, null returned in /mnt/www/shimmie2/vendor/shish/microcrud/src/Column.php:34 Stack trace: #0 /mnt/www/shimmie2/vendor/shish/microcrud/src/Table.php(311): MicroCRUD\Column->display() #1 /mnt/www/shimmie2/vendor/shish/microcrud/src/Table.php(254): MicroCRUD\Table->tbody() #2 /mnt/www/shimmie2/ext/user/main.php(201): MicroCRUD\Table->table() #3 /mnt/www/shimmie2/core/send_event.php(156): Shimmie2\UserPage->onPageRequest() #4 /mnt/www/shimmie2/index.php(89): Shimmie2\send_event() #5 {main} thrown in /mnt/www/shimmie2/vendor/shish/microcrud/src/Column.php on line 34`

**Comment by shish** [comment]
ecb3c642a9 should fix this, released in 2.10.1 :)
