### ISSUE TITLE
Support for GoatCounter

### ISSUE THREAD

**Issue by luRaichu** [shish/shimmie2#1021]
As an admin of a christian anime imageboard that runs Shimmie2, I think it'd be nice to have an extension for GoatCounter as to avoid handing over more data to Google. Google is evil.

**Comment by shish** [comment]
It looks like this is just a case of adding an HTML header? The "Custom HTML Headers" extension should allow you to put anything you want there, though if somebody wanted an extension similar to the google analytics one a pull request for that would be fine too :3
