### ISSUE TITLE
--user flag broken

### ISSUE THREAD

**Issue by NottyNoz** [shish/shimmie2#1022]
Server Software
  shimmie: "2.10.1-20240128-143ca48"
  schema: 21
  php: "8.1.2-1ubuntu2.14"
  db: "mysql 8.0.34-0ubuntu0.22.04.1"
  os: "Linux localhost 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64"
  server: "nginx/1.18.0"

https://github.com/shish/shimmie2/blob/main/core/cli_app.php#L38
This cli argument doesn't work at all.
`Trace: 0: shimmie2/index.php(87): Shimmie2\CliApp->run()
1: shimmie2/core/cli_app.php(39): Symfony\Component\Console\Input\Input->getOption()
Message: The "user" option does not exist.
Version: 2.10.1 (on 8.1.2-1ubuntu2.14)`

**Comment by shish** [comment]
(Splitting this into two bug reports because it is two bug reports~)
