### ISSUE TITLE
Incorrect Search Query Decoding

### ISSUE THREAD

**Issue by NottyNoz** [shish/shimmie2#1024]
Server Software
shimmie: "2.10.1-20240128-143ca48"
schema: 21
php: "8.1.2-1ubuntu2.14"
db: "mysql 8.0.34-0ubuntu0.22.04.1"
os: "Linux localhost 5.15.0-25-generic https://github.com/shish/shimmie2/issues/25 SMP Wed Mar 30 15:54:22 UTC 2022 x86_64"
server: "nginx/1.18.0"

Any search that includes a / gets encoded as %2F but it gets decoded back to / by php during the back and forth with the client. This occurs regardless of having nice urls enabled or not. This is a problem because any tag with a / is completely unsearchable and you can't search sources beyond just the host name. If you search for something like `n/a` it seems to get turned into `post/list/n/a/1`. Additionally, double slashes (`//`) get turned into a single slash due to RFC 3986 dictating that it be so. That means a search like `source=https://google.com/` gets turned into `post/list/source=https:/google.com/1`. A very hacky way to get around this problem is to double encode the queries, however this has unintended side effects to things like code that gets `$_GET['search']` directly. I don't understand how paheal doesn't have this problem, everything seems to work properly there.

**Comment by shish** [comment]
Can you see at what point the URL goes wrong? Specifically this is the correct workflow:

* User types `source=https://google.com/` into the search box and hits enter
* browser make a `GET` request to `/post/list/1?search=source=https://google.com&q=/post/list`
* shimmie responds with a response that includes the header `Location: /post/list/source%3Dhttps%3A%2F%2Fgoogle.com/1`
* browser makes a `GET` request to `/post/list/source%3Dhttps%3A%2F%2Fgoogle.com/1`
* shimmie responds with search results page

**Comment by shish** [comment]
Also if you manually visit `/post/list/source%3Dhttps%3A%2F%2Fgoogle.com/1` (ie the URL with encoded search query) does that load correctly? (That should help figure out if it's the search, redirect, or results page that's getting confused)

**Comment by NottyNoz** [comment]
I set up breakpoints

before the redirect in ext/index/main.php
`post/list/1?search=source%3Dhttps%3A%2F%2Farchived.moe&q=%2Fpost%2Flist` -> `$_GET['search']` is `source=https://archived.moe`

reponse header is `post/list/1?search=source%3Dhttps%3A%2F%2Farchived.moe&q=%2Fpost%2Flist`
page loads as `post/list/source%3Dhttps%3A%2F%2Farchived.moe/1`

after the redirect in ext/index/main.php
`_get_query()` -> `post/list/source=https:/archived.moe/1`
`var_dump($_GET)` -> `array(1) { ["q"]=> string(38) "post/list/source=https:/archived.moe/1" } `
`var_dump($_SERVER["QUERY_STRING"])` -> `string(40) "q=post/list/source=https:/archived.moe/1" `

> Also if you manually visit `/post/list/source%3Dhttps%3A%2F%2Fgoogle.com/1` (ie the URL with encoded search query) does that load correctly? (That should help figure out if it's the search, redirect, or results page that's getting confused)

This doesn't work, any request with a / just gets redirected to post/list however the url with the search still remains in the address bar

**Comment by shish** [comment]
> `_get_query()` -> `post/list/source=https:/archived.moe/1`

Aha, I suspect this might be an issue with the suggested nginx config file in the wiki where it is manually rewriting queries from `/post/list/asdf/1` to `index.php?q=/post/list/asdf/1`, and that rewrite doesn't handle decoding or encoding at all...

Do you happen to be comfortable fiddling with nginx configs? I don't have an nginx based setup to test with myself though I can probably make one if needed ^^

Specifically the current approach is:
* rewrite `*.css/js/png/html` / etc to itself, and stop rewriting here (ie ignore the next rule)
* rewrite all remaining requests from `/foo` to `/index.php?q=/foo` (I'm pretty sure this is broken)
* if the result of the rewrite contains *.php, then forward that to PHP

A better approach would be:
* for things which appear to be static files (`*.jpg` etc), if they exist on-disk, then serve them
* for everything else, send the request to shimmie

I think this change would be something like taking this old code:
```
    location / {
        rewrite "^(.*)/(.*)\.(php|css|js|gif|png|jpg|ico|html|manifest|appcache|txt|jar|zip)$" $1/$2.$3 break;
        rewrite "^(.*)/(.*)\?(.*)$ $1/index.php?q=$2&$3" last;
        rewrite "^(.*)/(.*)$ $1/index.php?q=$2" last;
        rewrite ^/(.*)$ /index.php?q=$1 last;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock; # replace with your PHP version
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
```
and replacing it with something like 
```
    location ~ "^.*\.(css|js|gif|png|jpg|ico)$" {
        try_files $uri @backend;
    }

    location / {
        try_files _ @backend;
    }

    location @backend {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock; # replace with your PHP version
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param  SCRIPT_NAME     index.php;
        include fastcgi_params;
    }
```

**Comment by NottyNoz** [comment]
> Aha, I suspect this might be an issue with the suggested nginx config file in the wiki where it is manually rewriting queries from `/post/list/asdf/1` to `index.php?q=/post/list/asdf/1`, and that rewrite doesn't handle decoding or encoding at all...

I figured it might be nginx when I saw that paheal worked fine. This config doesn't work at all and breaks `get_base_href()` in polyfills.php

it is now
`
["SCRIPT_NAME"]=> string(10) "/post/list"
["PHP_SELF"]=>string(10) "/post/list"
`
instead of 
`
["SCRIPT_NAME"]=> string(10) "/index.php"
["PHP_SELF"]=> string(10) "/index.php"
`

I would try to fix this myself but nginx configs are confusing and hard to test/debug.

**Comment by shish** [comment]
Argh, indeed D: Let's see if I can get a docker setup working to experiment with...

**Comment by shish** [comment]
e9c8e85 should fix `get_base_href()` - and then https://github.com/shish/shimmie2-examples/blob/main/nginx.conf should be a more efficient and correct nginx config - can you see if those work for you?

**Comment by NottyNoz** [comment]
Everything works fine now except I had to remove the `.*\.` from the _images and _thumbs in the nginx config. Additionally, this doesn't fix requests that don't have nice urls enabled. The nice urls tester in ext/setup even breaks.

https://github.com/shish/shimmie2/blob/main/ext/setup/main.php#L358
`$_SERVER["SCRIPT_NAME"]` now returns `/setup` instead of `/index.php` so the javascript queries the wrong page.

**Comment by shish** [comment]
niceurl test fixed, and I can reproduce the problem with search not working while niceurls are disabled so investigating that now...

**Comment by NottyNoz** [comment]
Nice urls with this config also doesn't work if shimmie2 isn't on the root web directory. I can't figure out how to achieve the same effect as the rewrites using just fastcgi.

**Comment by shish** [comment]
With a few more changes, what is currently in the `branch-2.10` branch, when combined with a config file from https://github.com/shish/shimmie2-examples, should now be working with niceurls and without, installed at the top-level and in a subdirectory
