### ISSUE TITLE
Booru failed after using Post Controls; no longer starts

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#1034]
**Server Software**
(note this is from a parallel booru container I'm running on the same host/docker image; as the bugged one will not start successfully I cannot get the info directly from it; the configuration is _nearly_ identical)
```
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://[redacted]/index.php?q="

versions:
  shimmie: "v2.11.0-alpha-20240213-28a3aad"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 11.22 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 92e33ebd67ec 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64"
  server: "Unit/1.31.1"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","post_lock","post_owner","post_source","post_tags","replace_file","setup","static_files","system","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","autocomplete","bulk_add_csv","emoticons_list","et_server","favorites","home","pools","post_titles","random_image","random_list","rating","regen_thumb","relationships","tag_categories","tag_tools","tagger_xml"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 28148
  comments: 0
  users: 2

media:
  memory_limit: "32MB"
  disk_use: "129GB"
  disk_total: "197GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 190
  height: 300
  scaling: 100
  mime: "image/jpeg"
```

**Client Software (please complete the following information)**
 - Device: macOS Desktop (Ventura 13.6.4)
 - Browser: Safari 17.3

**What steps trigger this bug**
1. Go to a post
2. Under "Post Controls" Click on 'Replace'

**What did you expect to happen?**
I expected either a separate page, or a file selection dialog to choose a replacement image.

**What actually happened?**
Nothing apparent; there appeared to be a quick flash of a redirect on the address bar, but it stayed on the same page. I also tried "Scan Media Properties" and saw nothing. "Regenerate Thumbnail" however, appeared to work.

A short time later I found the booru had crashed and was no longer reachable; this persisted through restarting the container after pulling the latest image. I can no longer connect to this booru (fortunately it's a side project and not my main repository).

The following is the only log data I see for the booru that will not start up.
```
shimmie-own $ docker logs shimmie-own
/app/.docker/entrypoint.sh: Launching Unit daemon to perform initial configuration...
2024/02/13 19:29:01 [info] 26#26 unit 1.31.1 started
2024/02/13 19:29:01 [info] 28#28 discovery started
2024/02/13 19:29:01 [notice] 28#28 module: php 8.2.7 "/usr/lib/unit/modules/php.unit.so"
2024/02/13 19:29:01 [info] 27#27 controller started
2024/02/13 19:29:01 [notice] 27#27 process 28 exited with code 0
2024/02/13 19:29:01 [info] 32#32 router started
2024/02/13 19:29:01 [info] 32#32 OpenSSL 3.0.11 19 Sep 2023, 300000b0
{
	"certificates": {},
	"js_modules": {},
	"config": {
		"listeners": {},
		"routes": [],
		"applications": {}
	},

	"status": {
		"connections": {
			"accepted": 0,
			"active": 0,
			"idle": 0,
			"closed": 0
		},

		"requests": {
			"total": 0
		},

		"applications": {}
	}
}
/app/.docker/entrypoint.sh: /app/.docker/entrypoint.d/ is not empty, applying initial configuration...
/app/.docker/entrypoint.sh: Looking for certificate bundles in /app/.docker/entrypoint.d/...
/app/.docker/entrypoint.sh: Looking for JavaScript modules in /app/.docker/entrypoint.d/...
/app/.docker/entrypoint.sh: Looking for configuration snippets in /app/.docker/entrypoint.d/...
/app/.docker/entrypoint.sh: Applying configuration /app/.docker/entrypoint.d/config.json
2024/02/13 19:29:01 [info] 39#39 "shimmie" prototype started
2024/02/13 19:29:01 [info] 40#40 "shimmie" application started
2024/02/13 19:29:01 [info] 41#41 "shimmie" application started
/app/.docker/entrypoint.sh: OK: HTTP response status code is '200'
 }success": "Reconfiguration done."
/app/.docker/entrypoint.sh: Looking for shell scripts in /app/.docker/entrypoint.d/...
/app/.docker/entrypoint.sh: Ignoring /app/.docker/entrypoint.d/config.json.tmpl
/app/.docker/entrypoint.sh: Stopping Unit daemon after initial configuration...
2024/02/13 19:29:01 [notice] 27#27 process 31 exited with code 0
/app/.docker/entrypoint.sh: Waiting for control socket to be removed...
2024/02/13 19:29:01 [notice] 27#27 process 32 exited with code 0
2024/02/13 19:29:01 [notice] 39#39 app process 40 exited with code 0
2024/02/13 19:29:01 [alert] 39#39 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
2024/02/13 19:29:01 [notice] 39#39 app process 41 exited with code 0
2024/02/13 19:29:01 [alert] 39#39 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
2024/02/13 19:29:01 [notice] 27#27 process 39 exited with code 0

/app/.docker/entrypoint.sh: Unit initial configuration complete; ready for start up...

2024/02/13 19:29:02 [info] 1#1 unit 1.31.1 started
2024/02/13 19:29:02 [info] 61#61 discovery started
2024/02/13 19:29:02 [notice] 61#61 module: php 8.2.7 "/usr/lib/unit/modules/php.unit.so"
2024/02/13 19:29:02 [info] 1#1 controller started
2024/02/13 19:29:02 [notice] 1#1 process 61 exited with code 0
2024/02/13 19:29:02 [info] 63#63 router started
2024/02/13 19:29:02 [info] 63#63 OpenSSL 3.0.11 19 Sep 2023, 300000b0
2024/02/13 19:29:02 [info] 64#64 "shimmie" prototype started
2024/02/13 19:29:02 [info] 65#65 "shimmie" application started
2024/02/13 19:29:02 [info] 66#66 "shimmie" application started
```

Honestly; these look essentially identical to the successful startup of my other booru container, so I don't think there's anything useful here. Is there a different log I should attach? Nothing immediately leapt out at me from the data folder.

**Comment by shish** [comment]
"Replace" not seeming to do anything was a separate issue (all of the other buttons in that list perform actions directly, but "replace" has its own "what do you want to replace with?" screen before the action takes place - f033efd45 should make sure the screen gets shown)

**Comment by diamondsw** [comment]
Well this is utterly bizarre... forgive me, but it appears to have been a browser issue. Here's a screenshot of two windows in the same browser session, on the left my usual view and on the right in private/incognito mode (which I opened for troubleshooting, not expecting an effect!):
<img width="1680" alt="Screenshot 1" src="https://github.com/shish/shimmie2/assets/49737/c42847da-26f4-4b4b-8f57-1c806b65c6d0">

I don't know how browser state can cause it to _not connect at all_ - especially spontaneously - but it certainly appears to be a local issue.

**Comment by shish** [comment]
No worries, I have found similar totally random and never-explained breakage on my macbook (though in my case it was firefox which randomly couldn't connect to my bank even though everything else was fine), in my case at least turning it off and on again seemed to work ^^
