### ISSUE TITLE
CSS stylesheet and JS scripts not found in fresh install

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#1064]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

  shimmie: "2.11.0-alpha-20240221-0890de3"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 15.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 2ebab2fec340 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64"
  server: "Unit/1.31.1"

**Client Software (please complete the following information)**
 - Device: desktop
 - Browser: Firefox 122.0, MS Edge Version 120.0.2210.61

I may be cursed today, sorry. Fresh install (using no cache) looks like this:
![image](https://github.com/shish/shimmie2/assets/56076467/948c5235-aec5-4934-8bef-27af0903999d)

CSS stylesheet and JS scripts don't seem to be found. However, checking both in the container and inside the volume, the stylesheets and scripts in /data/cache/* are there and belong to shimmie:shimme, so 1000:1000.

The only thing I noticed when testing a barebones container with:
`docker run -p 7005:8000 -v app:/app/data shish2k/shimmie2`
was this error in the browser console when first loading the install page:
![2024-02-21_16-29](https://github.com/shish/shimmie2/assets/56076467/04ca6ed1-5cc1-469c-88bb-1944d31e586a)

Testing again using shish2k/shimmie2:2, so v2.10.6, everything loads up fine.

**Comment by shish** [comment]
Gaaaaaaaah `envsubst` silently failed to replace a variable, then `unit` silently failed to understand that a variable was missing -_-
