### ISSUE TITLE
Requests from a unix socket fail get_session_ip()

### ISSUE THREAD

**Issue by discomrade** [shish/shimmie2#1076]
**Server Software**
 - Shimmie version: dev
 - Web server: NGINX

**What steps trigger this bug**
0, Have a server set up using a unix socket, such as a Tor daemon passing .onion requests to NGINX.
1, Attempt to login

The error occurs because `$addr` gets set to `unix:`, which makes `inet_pton_ex($addr)` fail.

https://github.com/shish/shimmie2/blob/ae92e423007fda7e9b5dd04236df9aa8efa1eac9/core/util.php#L198-L200

One approach to handling this is to just replace `unix:` with `127.0.0.1`.

**Comment by shish** [comment]
I can probably fix this blindly by just checking for the literal string "unix:", but I am actually intrigued by the .onion setup in general, and wonder if that's something that could be added to https://github.com/shish/shimmie2-examples so that I can experiment with a similar setup on my laptop and see how it works for myself 👀 


> One approach to handling this is to just replace unix: with 127.0.0.1.

That should stop the crashing, though I wonder if there's merit in somehow marking "Tor Client" as distinct from "Local Client" 🤔 (I don't know if there is a benefit, maybe not, my spidey-sense is just telling me that using a "valid but not accurate" source IP like 127.0.0.1 *might* lead to problems later)

**Comment by shish** [comment]
(In particular something to experiment with if I had a working setup to poke: would it make sense to add "unix:" to the TRUSTED_PROXIES system setting? 🤔 )

**Comment by discomrade** [comment]
> That should stop the crashing, though I wonder if there's merit in somehow marking "Tor Client" as distinct from "Local Client" 🤔 (I don't know if there is a benefit, maybe not, my spidey-sense is just telling me that using a "valid but not accurate" source IP like 127.0.0.1 _might_ lead to problems later)

There could be merit in it, because there are other anonymisers (I've seen both I2P and Loki handled on non-booru imageboards) and an admin could benefit from seeing if only one is being abused. I've seen this handled in NGINX by having it modify the headers depending on which anonymiser received the request. And I agree with your spidey-sense. It's probably better to handle them than lumping all the local and anonymous into one.

> I can probably fix this blindly by just checking for the literal string "unix:", but I am actually intrigued by the .onion setup in general
It's actually very simple to do, NGINX/Apache can either listen on post localhost 80 or listen to a unix socket. The socket is better practice but slightly more advanced since you have to get the file permissions correct. The examples in here (step 5 shows NGINX using sockets and Apache using port 80. There are really only two different lines, the server name and the listen target)
https://community.torproject.org/onion-services/setup/

**Comment by discomrade** [comment]
> the request that reaches Shimmie has zero meaningful metadata attached

This is true, unless the web server is manually instructed to attach some. e.g: `Socket: Tor Client`

It could be appropriate to give a generic example of adding a socket connection with that extra header in the examples repo, and creating a descriptive error message if 'unix:' is sent and the server didn't attach that extra header.
