### ISSUE TITLE
GraphQL API Internal Server Errors

### ISSUE THREAD

**Issue by cblanken** [shish/shimmie2#1089]
**Server Software**
 - URL: [https://fanworks.wanderinginn.com/](https://fanworks.wanderinginn.com/)
 - Shimmie version: v2.10.6
 - Database: PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
 - Web server: Apache
 - Extensions:
  ```
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","replace_file","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["autocomplete","emoticons_list","et_server","favorites","graphql","handle_mp3","handle_svg","handle_video","home","image_view_counter","link_image","pools","post_titles","random_list","rating","regen_thumb","relationships","report_image","rotate","rss_comments","rss_images","sitemap","source_history","tag_categories","tag_editcloud","tag_history","tag_tools","tagger_xml","transcode","transcode_video"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","audio/mpeg","image/svg+xml","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]
  ```

**Client Software (please complete the following information)**
 - Client: GraphQL client ([Hoppscotch](https://hoppscotch.io))

**What steps trigger this bug**
1. Make a GraphQL query to `https://fanworks.wanderinginn.com/graphql` for posts 
2. A query to `posts` specifying any of the following fields returns an "Internal server error"
  - `posted`
  - `locked`
  - `height`
  - `width`
  - `filesize`

**What did you expect to happen?**
Expected typical JSON response of provided fields. For example this similar query without one of the broken fields returns data like this.
### Query
```gql
query GetPosts {
  posts(limit: 3, offset: 0) {
    post_id
    tags
  }
}
```

### Response
```json
{
  "data": {
    "posts": [
      {
        "post_id": 4332,
        "tags": [
          "artist:wingedhatchling",
          "character:jelaqua_ivirith",
          "character:mrsha",
          "meta:animated",
          "spoiler:volume6"
        ]
      },
      {
        "post_id": 4331,
        "tags": [
          "armor",
          "artist:wingedhatchling",
          "blond",
          "blonde_hair",
          "braids",
          "character:ylawes_byres"
        ]
      },
      {
        "post_id": 4330,
        "tags": [
          "antinium",
          "meta:meme",
          "meta:tagchar",
          "meta:tagspoiler"
        ]
      }
    ]
  },
  "stats": {
    "time": 0.03,
    "dbtime": 0.01,
    "mem_mb": 4,
    "files": 436,
    "query_count": 8,
    "event_count": 5,
    "cache_hits": 1,
    "cache_misses": 3,
    "version": "v2.10.6",
    "graphql_schema_time": 0.01,
    "graphql_execute_time": 0.01
  }
}
``` 

**What actually happened?**
However, once adding one of the broken fields, an internal server error occurs.
### Query
```gql
query GetPosts {
  posts(limit: 3, offset: 0) {
    post_id
    tags
    posted
}
```

### Response
```json
{
  "errors": [
    {
      "message": "Internal server error",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "posts",
        0,
        "posted"
      ]
    }
  ],
  "stats": {
    "time": 0.04,
    "dbtime": 0.01,
    "mem_mb": 6,
    "files": 440,
    "query_count": 6,
    "event_count": 5,
    "cache_hits": 1,
    "cache_misses": 3,
    "version": "v2.10.6",
    "graphql_schema_time": 0.01,
    "graphql_execute_time": 0.02
  }
}
```

Queries on the mentioned fields were working previously since v2.10.0 I believe, but after updating to v2.10.6 the mentioned fields all seem to cause internal server errors.

**Comment by shish** [comment]
Hmm, IIRC nothing in our graphql code has changed between 2.10.0 and 2.10.6 - I wonder if some upstream dependency got bumped, which is now causing fields backed by class attributes to break (fields backed by class methods seem fine)...

```
$ php index.php graphql:query 'query GetPosts {posts(limit: 3, offset: 0) { post_id tags width }}'
In ReferenceExecutor.php line 853: Cannot return null for non-nullable field "Post.width".  
```

**Comment by shish** [comment]
This should be worked-around in the 2.10 branch now (the real fix is in an upstream library), one question before I do a 2.10.7 release though - do you plan on using the upload / image metadata setting APIs? I ask because I'm planning on changing those in 2.11, and I wonder if it's worth backporting the change to 2.10 so that you have a stable target to work with (if you're only using graphql to query the data then there are currently no changes)

**Comment by cblanken** [comment]
> ... do you plan on using the upload / update_post_metadata APIs? I ask because I'm planning on changing those in 2.11, and I wonder if it's worth backporting the change to 2.10 so that you have a stable target to work with (if you're only using graphql to query the data then there are currently no changes)

Nope, no plans on using the `upload` or `update_post_metadata` APIs just yet. I'm only using the queries for post data to compile some statistics.
