### ISSUE TITLE
TimeoutException during upload and the problem of passing php.ini settings

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#1096]
**Is your feature request related to a problem? Please describe.**
Coming back to https://github.com/shish/shimmie2/issues/1058 and the problem ob how to pass PHP internal settings: I am still playing around with the newly added MAX_FILE_UPLOADS env variable (thank you again btw) and noticed the following:
When uploading either a large amount of small files, e.g. 500 .jpg files, or a small amount of larger video files, the upload sometimes fails due to a TimeoutException being thrown in core/send_event.php -> send_event():
```
2024/02/25 21:30:44 [notice] 26#26 [unit] #27: php message: Shimmie Error: Timeout while sending ThumbnailGenerationEvent (Query: )
#0 /app/ext/image/main.php(142): Shimmie2\send_event()
#1 /app/core/send_event.php(161): Shimmie2\ImageIO->onImageAddition()
#2 /app/core/extension.php(371): Shimmie2\send_event()
#3 /app/core/send_event.php(161): Shimmie2\DataHandlerExtension->onDataUpload()
#4 /app/ext/upload/main.php(316): Shimmie2\send_event()
#5 /app/core/database.php(143): Shimmie2\Upload->Shimmie2\{closure}()
#6 /app/ext/upload/main.php(315): Shimmie2\Database->with_savepoint()
#7 /app/ext/upload/main.php(239): Shimmie2\Upload->try_upload()
#8 /app/core/send_event.php(161): Shimmie2\Upload->onPageRequest()
#9 /app/index.php(91): Shimmie2\send_event()
#10 {main}
```

(ran into timeouts with other events in other tests as well, like trying to send MediaCheckPropertiesEvent when uploading a large amount of images, or MediaResizeEvent when uploading a few larger videos (~300MB each).

As far as I understand it, send_event() throws a TimeoutException based on _shm_timeout which is set by shm_set_timeout, which in turn is only called if PHP's max_execution_time setting is detected. The timeout kicks in after about 30s which is also the default for max_execution_time.

This shows me we may need a way to set max_execution_time. However, depending on what kind and amount of files the user wants to upload, we may run into other PHP limits like max_input_time, max_input_vars or max_multipart_body_parts...I can now see why you are considering to just hardcode limits entirely :)

**Describe the solution you'd like**

You mentioned the approach of accepting environment vars like PHP_<settingname> - I think this may be a flexible enough way to allow for the configuration of PHP settings without being tied to which webserver is currently being used. Question there is if it's worth it to write conversions for each and every possible php.ini setting, or if it's better to just leave it up to the admin not to misspell the <settingname> part in any PHP_-environment vars they might use.

**Comment by shish** [comment]
https://github.com/shish/shimmie2/issues/1096 goes ahead and turns each `PHP_INI_FOO_BAR=123` environment variable into into a `foo_bar=123` php.ini setting - can you let me know if that covers all the cases you need?

**Comment by shish** [comment]
(Minor update: the calculation of maximum total upload size was broken by the above change, #1101 fixes it)

**Comment by Giraffaman** [comment]
Awesome thank you - I may not be able to test it before tomorrow, but this looks to be a nice solution

**Comment by Giraffaman** [comment]
specifying post_max_size in shorthand format is now possible and overall I haven't noticed any drawbacks from defining PHP ini settings using PHP_INI_xxx environment variables. Looks like a nice and flexible approach to me.

Thanks for implementing this :)
