### ISSUE TITLE
Uploading image hangs on blank page; cannot locate logs in Docker container

### ISSUE THREAD

**Issue by Hawker2** [shish/shimmie2#1097]
**Server Software**
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://[redacted]/index.php?q="

versions:
  shimmie: "2.11.0-alpha-20240225-b9c7d63"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 11.22 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 8c7dce5ef7fe 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64"
  server: "Unit/1.31.1"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","post_lock","post_owner","post_source","post_tags","replace_file","setup","static_files","system","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","autocomplete","bulk_add_csv","emoticons_list","et_server","favorites","home","pools","post_titles","random_image","random_list","rating","regen_thumb","relationships","tag_categories","tag_tools","tagger_xml"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 29093
  comments: 0
  users: 2

media:
  memory_limit: "128MB"
  disk_use: "131GB"
  disk_total: "197GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 190
  height: 300
  scaling: 100
  mime: "image/jpeg"

**Client Software (please complete the following information)**
 - Device: macOS Ventura 13.6.4
 - Browser: Safari 17.3.1

**What steps trigger this bug**
1. Go to "Upload"
2. Enter tags, source, and select an image
3. Click "Post"

**What did you expect to happen?**
Image to be uploaded, written to proper location in images, tags entered in database, etc.

**What actually happened?**
Hangs on that screen (which turns blank if the cache is dumped from memory). I've let it sit for a Long Time (e.g. ten minutes on a <300KB file) and it never returns. Meanwhile, the booru responds fine in other tabs.

Notably:
- The Bulk Add CSV extension works fine, which is why I had not noticed this until now
- Replacing an existing image also works; just not uploading a new one

I'm _sure_ this is some silly permissions error, but I cannot locate any logs in the Docker container (for instance, bashing into the container and `find /app -name error.log` yields nothing, nor does poking around by hand). If there's a log I can inspect I'm glad to.

**Comment by shish** [comment]
System level logs are all put on docker's stdout / stderr (visible with the `docker logs` command) rather than files inside the container

Hanging for multiple minutes should be cut off by the webserver o_O

Can you use the web inspector to see what the web browser is doing on the network when this happens? (Right click the page -> Inspect -> Network -> Go ahead and do the behaviour which triggers this issue). In particular we are expecting a POST to /upload which results in a 302 redirect, like this:

![Screenshot 2024-02-27 at 15 07 05](https://github.com/shish/shimmie2/assets/40659/0c045931-0df8-4b66-8807-6785d9aa5f86)

**Comment by Hawker2** [comment]
Note to self: Reboot everything _including the computer_ before submitting bugs. I can no longer reproduce this, and am sorry for wasting your time.
