### ISSUE TITLE
Permission denied even for admins when editing/adding tag categories

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#1103]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version:
  shimmie: "2.11.0-alpha-20240303-e5471df"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 15.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 0417ce3dc971 5.10.0-26-amd64 1 SMP Debian 5.10.197-1 (2023-09-29) x86_64"
  server: "Unit/1.32.0"

**What steps trigger this bug**
1. Login as admin
2. verify "Tag Categories" extension is enabled 
3. Go to /tags/categories
4. attempt to edit existing category or to submit a new one

**What did you expect to happen?**
Be able to edit existing category, e.g. change color, or be able to submit a new category by changing the "example" fields and clicking "submit"

**What actually happened?**
Get "permission denied".

From what I can see, /ext/tag_categories/main.php:75 checks for the EDIT_TAG_CATEGORIES permission:
```
        if ($event->page_matches("tags/categories", method: "POST", permission: Permissions::EDIT_TAG_CATEGORIES)) {
            $this->page_update();
        }
```
... which should be True at least for admins, but somehow the permission check fails.

Even adding a user of e.g. class Moderator with EDIT_TAG_CATEGORIES explicitly granted does not allow that user to edit/add tag categories.

**Comment by ksamavati** [comment]
+1 encountering the same issue, haven't found a workaround yet, no way I can find to add tag categories as admin.

**Comment by Giraffaman** [comment]
getting there - now it is possible to edit/add a tag category, but when sending the form, no matter if editing, adding or deleting, the following error is displayed:
```
Explanation
No handler could be found for the page 'tags/categories'
```
The change goes through though, so maybe we're missing some redirect after page_update() does its thing?

**Comment by Giraffaman** [comment]
all fixed now - ty
