### ISSUE TITLE
"No handler could be found for the page 'x.php'"

### ISSUE THREAD

**Issue by CesiumCs** [shish/shimmie2#1236]
**Server Software**

 - Shimmie version: 2.10.4 to latest (2.12.0) from Docker
 - Database: postgres 15.8
 - Web server: not sure? /system_info didn't tell me and i don't see it in headers either. it's whatever the docker instructions end you up with.

**Client Software**
 - Device: Debian 12
 - Browser: Firefox

**What steps trigger this bug**
I had an installation with Docker I havent updated too recently, pretty sure it was on 2.10 something, and after pulling the latest versions of both postgres and shimmie2 I get an error: No handler could be found for the page 'x.php'. This error is the only page that loads, with a 404 in the title and nothing else on the page except navigation and the footer.
I traced back through versions until I stopped getting the error, and had a working setup again after reverting to 2.10.3. I poked around settings and extensions to figure out how to log, the console log extension doesnt seem to log to dockers log and i dont know where else to look.

**What did you expect to happen?**
Posts to appear like normal

**What actually happened?**
all pages look the same and show the same error

2.10.4
![2 10 4](https://github.com/user-attachments/assets/e2be4148-e87f-4444-8fa2-40e7e450e6c3)
2.12.0
![2 12 0](https://github.com/user-attachments/assets/c1660c14-6a7e-44c0-bc3d-fa815aa20a5a)

**Comment by shish** [comment]
Well that's very weird, there is no `x.php` referenced in the code, unless something is taking `index.php` and cutting off the first 4 characters for some reason O_o

I wonder what the rest of the setup looks like - eg is there some reverse-proxy in front, or are you connecting directly to the docker container? Is it being accessed at the root (http://gallery.mysite.com) or in a subfolder (http://mysite.com/gallery/)? Is the docker container being launched with any particular flags?

**Comment by CesiumCs** [comment]
There's an apache https reverse proxy in front of it providing it at a subfolder /img. the container is being launched using docker compose using the same config file from the docs, with the only changes being irrelevant like php upload size or the exposed port on the host. I also found out that the root url of the service still shows the name and search like its supposed to but any links still lead to that same error.

**Comment by shish** [comment]
Can I see the Apache config, to try and recreate the same setup? (Feel free to email me if you don't want it public on GitHub)

(For context there is no reliable and automatic and consistently-available way for shimmie to know that it is at /img, so it makes several guesses, and the guess logic was changed between 2.10 and 2.12, but I _thought_ that all cases covered previously were still covered now... But it is currently sounding like something in the chain of servers is confused and thinking "I'm at /img so I will ignore the first 4 characters in the path" and something else is saying "the path is index.php")

**Comment by CesiumCs** [comment]
Host server's site conf, its an ssl one because my http one only redirects to https, so theres really no conf there. any other configuration files should be what you expect from ubuntu 24.04
<details>
  <summary>/etc/apache2/sites-available/010-root-le-ssl.conf</summary>

```apacheconf
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName cesium.one
	ServerAdmin webmaster@cesium.one

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	ProxyRequests Off
	ProxyPreserveHost On

	ProxyPass /img http://localhost:8212
	ProxyPassReverse /img http://localhost:8212
	<Location /img>
		AuthType Basic
		AuthName "Internal Content"
		AuthUserFile /etc/apache2/.htpasswd
		Require valid-user

	</Location>
	<Location /.git>
		Require all denied
	</Location>

	ProxyPass "/" "http://localhost:2281/"
	ProxyPassReverse "/"  "http://localhost:2281/"

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/cesium.one/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/cesium.one/privkey.pem
</VirtualHost>
</IfModule>
```
</details>

**Comment by shish** [comment]
#1243 _should_ fix this (and I assume you have `define("BASE_HREF", "/img");` in your `shimmie.conf.php` already, because I can't figure out how this issue would be triggered if that weren't the case?)

**Comment by CesiumCs** [comment]
Seems mostly fixed, thanks! The root url at /img still gives a 404 for no handlers found for "/" but that doesn't stop it from functioning, everything else works after i click index in navigation.

**Comment by shish** [comment]
#1244 should cover that last edge case /o/
