### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Shimmie2\preg_replace_ex()

### ISSUE THREAD

**Issue by abasameer** [shish/shimmie2#1240]
Fatal error: Uncaught Error: Call to undefined function Shimmie2\preg_replace_ex()

**Comment by shish** [comment]
How, where, what version of the software are you running, does the full error include any hint at what is trying to call that function, are there any customisations?

**Comment by abasameer** [comment]
i using cpanal 

[04-Sep-2024 13:06:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Shimmie2\preg_replace_ex() in /home/example/public_html/core/database.php:188
Stack trace:
#0 /home/example/public_html/core/database.php(248): Shimmie2\Database->count_time('get_all', 1725455204.5249, 'SELECT name FRO...', Array)
#1 /home/example/public_html/core/database.php(408): Shimmie2\Database->get_all('SELECT name FRO...')
#2 /home/example/public_html/core/install.php(219): Shimmie2\Database->count_tables()
#3 /home/example/public_html/core/install.php(80): Shimmie2\create_tables(Object(Shimmie2\Database))
#4 /home/example/public_html/core/install.php(49): Shimmie2\do_install('sqlite:data/shi...')
#5 /home/example/public_html/index.php(28): Shimmie2\install()
#6 {main}
  thrown in /home/example/public_html/core/database.php on line 188
