### ISSUE TITLE
[docker] Failed to authorize in new workflow

### ISSUE THREAD

**Issue by BadMannersXYZ** [shish/shimmie2#1255]
Follow-up of #1251 

The latest builds on main [seem to be failing](https://github.com/shish/shimmie2/actions/runs/10736302793/job/29775435481) due to an unauthorized error related to a missing token.

The exact error is:

```
ERROR: failed to push shish2k/shimmie2:latest: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3A***%2Fshimmie2%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized
```

This is not a login issue, as that step succeeds in the workflow. Nor is this a permission issue, as a read+write token is all that's necessary.

**Comment by BadMannersXYZ** [comment]
Actually, I'm not sure if a [personal access token](https://app.docker.com/settings/personal-access-tokens) is being used as a secret for the DOCKER_PASSWORD variable. Looking at containerd/nerdctl#3378, that seems to be the proposed solution, and it matches my own working setup.

**Comment by shish** [comment]
I thought that it was already using a PAT, but maybe I'm thinking of all my other projects, and this one predates them... shall give that a go /o/

**Comment by shish** [comment]
Still failing with a fresh token D:

**Comment by shish** [comment]
Looks like all the different things that I tried for DOCKER_REGISTRY were incorrect, and the default seems to be correct (but the default isn't documented anywhere so I don't know what that value actually _is_)

If somebody wants to be able to push to a different registry we can re-add that flag, if somebody tells me what the correct value is :sweat_smile:

**Comment by BadMannersXYZ** [comment]
Huh, that's weird! Never would've guessed that was the reason. But now that it builds I tried pulling the image to my Raspberry Pi, and it works! :tada:
