### ISSUE TITLE
Nice Urls breaking images (probably my fault)

### ISSUE THREAD

**Issue by smokiemario** [shish/shimmie2#1280]
I don't really know what Im doing so Im going to be as descriptive as possible

**Info**
about:
  theme: "lite"
  url id rather keep private, but both through localhost and the other thing im using I encounter the same issue
  
versions:
  shimmie: "2.12.0-alpha+b1e6ba52"
  schema: 21
  php: "8.3.6"
  db: "sqlite 3.45.1"
  os: Linux
  server: "PHP/8.3.6 (Development Server)"
 

extensions:
  core: ["admin","alias_editor","bbcode","comment","common_elements","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","post_lock","post_owner","post_source","post_tags","replace_file","setup","static_files","system","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["approval","auto_tagger","autocomplete","biography","blocks","browser_search","bulk_actions","bulk_add","bulk_add_csv","bulk_download","bulk_import_export","bulk_parent_child","custom_html_headers","danbooru_api","favorites","filter","handle_archive","handle_cbz","handle_mp3","handle_svg","handle_video","home","link_image","notes","ouroboros_api","pm","pools","post_peek","private_image","random_image","random_list","rating","relationships","reverse_search_links","tag_categories","tag_editcloud","tag_history","tag_tools","tips","transcode","wiki"]
  handled_mimes: {"0":"image/jpeg","1":"image/gif","2":"image/png","3":"image/webp","4":"application/zip","6":"application/vnd.comicbook+zip","7":"audio/mpeg","8":"image/svg+xml","9":"video/x-ms-asf","10":"video/x-msvideo","11":"video/x-flv","12":"video/x-matroska","13":"video/mp4","14":"video/ogg","15":"video/quicktime","16":"video/webm"}

stats:
  images: 14707

media:
  memory_limit: "8.0MB"
  disk_use: "309GB"
  disk_total: "525GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"
  
(Hopefully thats enough relevant info)

**What steps trigger this bug**
1. Set up the site using the steps under the "straight to disk" link on the readme file
2. Upload some images, noticing that the images display properly
3. Go to Board Config, notice it says "(test passed)" next to Nice URLs
4. Click on Nice URLS
5. Go to posts, notice thumbnails are no longer showing up, clicking an image reveals that the images themselves aren't loading either

**What did you expect to happen?**
I expected the images to work and display like they did before turning on Nice URLS

**What actually happened?**

![image](https://github.com/user-attachments/assets/98937158-62be-45b2-a775-12d136da647d)
The thumbnails will not load

![image](https://github.com/user-attachments/assets/132bcdb5-4688-40cf-89ec-8884ca93a30a)
Clicking on an post reveals the image will not load either, and is being replaced by "main image" which I assume to be alt text as the failsafe for the image not working

Copying this image link it looks like this - **[domain]**_images/070e4d05f5af81e859cda97c28ecc36b/15011%20-%20tagme.png
Opening image in a new tab reveals a 404 error

**More Context**

Im using shimmie as a nice way to organize all the art I have saved. And its so nice, I have literally spent hours daily for the last like month tagging stuff for myself, and it feels so good to have something like this.
But I don't really have much experience with this kind of stuff so honestly there's a good chance its my fault but maybe someone can help.

I set it up by following the instruction under install straight to disk on the Readme file
Thing is I can't say I know too much about what I'm doing

I read under settings nice urls need mod_rewrite configured and enabled
I don't really know how to do that. But considering test passed and the site works and its just the image and thumbnail links breaking, im assuming its already enabled

I tried to use apache since thats what that is for I think, but as much as I tried I couldn't get it to work, it just kept saying it couldn't access the .htaccess file
And I tried for hours to get it to work with no luck
And no idea if it even would have fixed the problem

Admittedly again I don't really know what I am doing here-- but if someone could point me in the right direction, ive been stuck not knowing what to do

Maybe this is better for discussions, not sure if its even a bug or just me not knowing how to do things

**Comment by shish** [comment]
> [domain]_images/070e4d05f5af81e859cda97c28ecc36b/15011%20-%20tagme.png

Is there no slash between the domain and _images?

If you open that URL by itself in the browser, what comes up? (I'm guessing something like either failed to find server, or a shimmie error message, or a web server error message)

**Comment by smokiemario** [comment]
no no there is a / slash my bad

![image](https://github.com/user-attachments/assets/3ff4550b-9c93-4362-b413-f8eca91bb060)

I get this

**Comment by smokiemario** [comment]
If it helps, the url with nice-urls off looks like this /index.php?q=image/15016/15016%20-%20tagme.png

**Comment by smokiemario** [comment]
I think its also worth noting I am having issues with some things, namely the wiki. For instance, clicking edit just takes me back to the homepage, I have to manually type /edit in the url to edit a page

And also things don't seem to really format.

 I was thinking maybe nice urls would fix the wiki editing thing maybe, but I can't even get nice urls to work so.

**Comment by shish** [comment]
So I'm not sure how this was working previously, but I've added a router script in https://github.com/shish/shimmie2/pull/1281/files (which should handle images and thumbs before passing other requests to Shimmie)

If you run that with `php -S localhost:9000 tests/router.php`, does that work?

**Comment by smokiemario** [comment]
Yea, it does, thanks

**Comment by smokiemario** [comment]
Not a huge deal but I am going to point out this does break the post peek extention, its incredibly pixelated now

**Comment by shish** [comment]
Looks like post peek was just never compatible with niceurls in the first place, #1284 should fix that
