### ISSUE TITLE
Unable able to create private Pool

### ISSUE THREAD

**Issue by wfscans** [shish/shimmie2#1292]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version: "2.12.0-alpha-unknown-unknown" https://github.com/shish/shimmie2/commit/305fc1f8d9b52d9baa083842a8d299f71473c889
 - Database: "sqlite 3.40.1"
 - Web server: "Unit/1.33.0"
 - Docker: Yes

**Client Software (please complete the following information)**
 - Device: Windows
 - Browser: Firefox

**What steps trigger this bug**
1. Enable Pools Extension
2. Goto "server/index.php?q=pool/new"
3. Enter required info
4. Uncheck checkbox
5. Get error for missing "Missing POST parameter public"

**What did you expect to happen?**
Expected outcome is to get a private pool 

**What actually happened?**
User receives error about lack of "public" parameter.

**Suggested Fix**
1. Either change the backend to handle the lack of "public" or relating the lack to it being private
2. Modify the checkbox to be two radio buttons https://github.com/shish/shimmie2/pull/1291

**Comment by shish** [comment]
Fixed in #1291
