### ISSUE TITLE
Fix Invalid Post ID when clicking post from tag list

### ISSUE THREAD

**Issue by BR3XALITY** [shish/shimmie2#1311]
**Server Software**
about:
  title: "Dihydrogen Monoxide"
  theme: "default"
  url: "http://localhost:9000/index.php?q="

versions:
  shimmie: "2.12.0-alpha+83dfcb39"
  schema: 21
  php: "8.3.10"
  db: "sqlite 3.47.0"
  os: "Linux localhost 5.10.198-android12-9-29539737-abS711USQS6CXK5 #1 SMP PREEMPT Mon Nov 11 05:04:52 UTC 2024 aarch64"
  server: "PHP/8.3.10 (Development Server)"
  origin: "https://github.com/shish/shimmie2 (main)"

extensions:
  core: ["admin","alias_editor","bbcode","comment","common_elements","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","post_lock","post_owner","post_source","post_tags","replace_file","setup","static_files","system","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["artists","autocomplete","biography","favorites","filter","forum","handle_video","home","image_view_counter","numeric_score","pm","post_titles","private_image","relationships"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]

stats:
  images: 2
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "87GB"
  disk_total: "104GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: "83dfcb39"
  branch: "main"
  origin: "https://github.com/shish/shimmie2"

 - Shimmie version:
 - Database: sqlite
 - Web server: php

**Client Software (please complete the following information)**
 - Device: Android
 - Browser: opera

**What steps trigger this bug**
1. Search a tag
2. Click on of the posts
3. You got the error

**What did you expect to happen?**
I expected it to show the post

**What actually happened?**
It shows an error
![Screenshot_20241125_004323_Opera](https://github.com/user-attachments/assets/7fb9b4a7-ad4c-4995-a590-ed55e71def05)

**Comment by shish** [comment]
What is the URL for the page with the error?

**Comment by BR3XALITY** [comment]
> What is the URL for the page with the error?

I was using localhost, but friendly urls fixed it. Thanks anyway.
