### ISSUE TITLE
Colored tags in information box underneath image

### ISSUE THREAD

**Issue by lysytsya459** [shish/shimmie2#1328]
Hi,
I forked Shimmi2 to start my own booru and I wanted to add ability to color tags based on regex like *_(artist) tags are yellow for example. Where should I look in the php to implement this? I have never written PHP before so it would be nice if you could point me at a file to look at since I don't know where to start.

Thank you.

**Comment by lysytsya459** [comment]
I created a bandaid fix by editing `ext/post_tags/theme.php` the `get_tag_editor_html` function block of code
`
global $user;

$tag_links = [];
foreach ($image->get_tag_array() as $tag) {
    $tag_links[] = A([
        "href" => search_link([$tag]),
        "class" => "tag",
        "title" => "View all posts tagged $tag"], $tag);
}
` 
into
`
global $user;
global $database;

if (Extension::is_enabled(TagCategoriesInfo::KEY)) {
    $tagcategories = new TagCategories();
    $tag_category_dict = $tagcategories->getKeyedDict();
}

$tag_links = [];
foreach ($image->get_tag_array() as $tag) {
    $color = null;

    if (Extension::is_enabled(TagCategoriesInfo::KEY)) {
        $category = explode(":", $tag)[0];

        $query = "SELECT color FROM image_tag_categories WHERE category = :category";
        $args = ["category" => $category];

        $color = $database->get_one($query, $args);
    }

    if ($color) {
        $tag_links[] = A([
            "href" => search_link([$tag]),
            "class" => "tag",
            "title" => "View all posts tagged $tag",
            "style" => "color: $color",
        , $tag);
    } else {
        $tag_links[] = A([
            "href" => search_link([$tag]),
            "class" => "tag",
            "title" => "View all posts tagged $tag",
        ], $tag);
    }
}
`

However I know this is not optimal approach, because looking through code base I saw the `TagCategories` class but I don't have enough knowledge to apply it here.

**Comment by lysytsya459** [comment]
That's not what I want, it only colors on the left side info panel. I wanted colors in the tags underneath the image, unless there is a way to hide that information and only show the set/edit tags button.
When I tried to do that I found the `build_information` function I could modify in view.theme.php for my own theme but that modifies the left panel.
I would use the category extension if I didn't have duplicated information since it looks really ugly have left panel tags colored while the ones underneath image aren't.
Here is what I did, but the left panel is better so I'd like to get rid of this info box, i just don't know how since what I edit modifies the left panel instead:
![Screenshot_20241213_172338](https://github.com/user-attachments/assets/701c6a82-bf2d-4908-a7b9-99a81aea01d3)

**Comment by lysytsya459** [comment]
To edit the information box below the post image I edited the `onImageInfoBoxBuilding`
`ext/post_tags/main.php` into:
```php
public function onImageInfoBoxBuilding(ImageInfoBoxBuildingEvent $event): void
    {
        global $user;
        if ($user->can(Permissions::EDIT_IMAGE_TAG) || $user->id == $event->image->owner_id) {
                $event->add_part($this->theme->get_tag_editor_html($event->image), 40);
        }
    }
```
`ext/post_source/main.php` into:
```php
public function onImageInfoBoxBuilding(ImageInfoBoxBuildingEvent $event): void
    {
        global $user;
        if ($user->can(Permissions::EDIT_IMAGE_TAG) || $user->id == $event->image->owner_id) {
                $event->add_part($this->theme->get_source_editor_html($event->image), 41);
        }
    }
```
`ext/post_owner/main.php` into:
```php
public function onImageInfoBoxBuilding(ImageInfoBoxBuildingEvent $event): void
{
        global $user;
        if ($user->can(Permissions::EDIT_IMAGE_TAG) || $user->id == $event->image->owner_id) {
                $event->add_part($this->theme->get_owner_editor_html($event->image), 39);
        }
}
```

This removes the info box for regular users but keeps it for the image uploader and moderator/higher classes.
Also as an aside, I had to mess with permissions to allow uploader to edit tags of their own image even if they don't have EDIT_IMAGE_TAG permissions to prevent grief of other users but save approvers tagging effort. This is why the permissions if statement looks different from other codebase.

**Comment by lysytsya459** [comment]
@shish thank you for adding the `build_tag` function I merged it in and updated my theme accordingly

**Comment by lysytsya459** [comment]
I'm reading through the `TagCategories` code and I found I could use the `getTagHtml` and just edit `build_tag` in my theme to be
```php
$tag_links[] = A([
                "href" => search_link([$tag]),
                        "class" => "tag",
                        "title" => "View all posts tagged $tag"
                ], rawHTML(TagCategories::getTagHtml($tag)))
```
is there any chance this could be default behavior?

Also thank you for your help I got more familiar with code base by seeing where you made changes.

**Comment by shish** [comment]
Yeah, my end goal is to have a single `build_tag` function which has similar behaviour to what is currently in `getTagHtml` (but is implemented in such a way that it's easy for themes to customise it, which they can't do currently; and then use that function everywhere, as opposed to getTagHtml which is only used sometimes)

There's a bunch of commits happening (and more in-progress) because when tag categories were first added they were kind of duct-taped on top of a system that wasn't designed for them, so now I'm going through and cleaning up to make the code as simple as possible rather than adding duct-tape on top of duct-tape :)
