### ISSUE TITLE
Error when 2+ images are uploaded with same tag

### ISSUE THREAD

**Issue by DakuTree** [shish/shimmie2#147]
<pre>Internal Error
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'anytag' for key 'tag'
Query: INSERT INTO tags(tag) VALUES (:tag)</pre>

Keep having this error occur when two files are uploaded at same time with each sharing a tag.
Example: 'Image1: "blah" & Image2: "blah" uploaded at same time, error occurs.'
Example: 'Image1: "blah" & Image2: "notblah" uploaded at same time, no error.'
Example: 'Image1: "blah notblah" & Image2: "notblah moo" uploaded at same time, error occurs.'

**Comment by shish** [comment]
This seems to have been fixed some time ago, cleaning up the bug report
