### ISSUE TITLE
User permission (e.g. Moderator)

### ISSUE THREAD

**Issue by k12onos** [shish/shimmie2#215]
Hi,

I'm wondering if there's any way for me to assign a user to a role such as moderator? For moderator they could be set to have ability to delete images and set featured images, etc.

Is there any modifications that will allow me to do this?

Thank you

**Comment by SpannerWZ** [comment]
is there any way to let uploaders delete their own images?

**Comment by shish** [comment]
At the moment there's no option for that, but it shouldn't be too hard to add an extra permission to allow it - pull requests welcome :)
