### ISSUE TITLE
Forum extension not working

### ISSUE THREAD

**Issue by pachuco** [shish/shimmie2#244]
I've never been able to use the forum extension successfully. All I get is:

Internal Error

Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''0', '15'' at line 1

Query: SELECT f.id, f.sticky, f.title, f.date, f.uptodate, u.name AS user_name, u.email AS user_email, u.admin AS user_admin, sum(1) - 1 AS response_count FROM forum_threads AS f INNER JOIN users AS u ON f.user_id = u.id INNER JOIN forum_posts AS p ON p.thread_id = f.id GROUP BY f.id, f.sticky, f.title, f.date, u.name, u.email, u.admin ORDER BY f.sticky ASC, f.uptodate DESC LIMIT ?, ?

Version: trunk

**Comment by shish** [comment]
I'm not sure when exactly, but at _some_ point in the past 12 years the SQL was changed to use the cross-database compatibility format
