### ISSUE TITLE
Image duplication problem

### ISSUE THREAD

**Issue by Solaris17** [shish/shimmie2#261]
I get this error when i do bulk uploads and their are duplicate images.

Strict Standards: Non-static method BaseThemelet::build_thumb_html() should not be called statically, assuming $this from incompatible context in F:\xampp\htdocs\ext\image\main.php on line 308

the corrisponding line is "already has hash {$image->hash}:<p>".Themelet::build_thumb_html($existing);

**Comment by shish** [comment]
This got fixed a while ago
