### ISSUE TITLE
Warning: Upload Collision handler - Merge

### ISSUE THREAD

**Issue by ghost** [shish/shimmie2#274]
Warning: assert() [function.assert]: Assertion failed in /www/core/imageboard.pack.php on line 73
Makes it nearly impossible to use "Bulk Add" and any duplicate images being uploaded by users show an ugly php error.

EDIT: This occurs when uploading a file with the same hash and the "Upload collision handler" option in the Board Config is set to "Merge".

**Comment by shish** [comment]
This should be fixed now; and if it's still happening for anyone, it should give more useful debug info to track down the real source (so feel free to reopen if so)
