### ISSUE TITLE
Tag implications

### ISSUE THREAD

**Issue by sergalbutt** [shish/shimmie2#320]
Another booru-style board I browse has a feature where if something gets tagged with a specific tag, it would imply another tag.

For example: An image tagged 'cat' would get the tags 'cat' and 'feline', or an image tagged with 'wolf' would get the tags 'wolf' 'dog' and 'canine'

I don't know if you can do this with aliases, but I think I've tried it before and it didn't work, so this feature would be super.

**Comment by shish** [comment]
This has been working for a while, not sure when it was implemented exactly, closing the report
