### ISSUE TITLE
Overlapping thumbnails

### ISSUE THREAD

**Issue by sergalbutt** [shish/shimmie2#321]
Is it my imagination or was there once a feature which allowed you to determine how many rows/columns are on the post list?

If it is just my imagination, this should be a thing, especially if someone choose to have large thumbnails.

**Comment by SpannerWZ** [comment]
is there any way to increase the size on DanbooruV2 theme? when i increase the size of thumbnails i also get overlapping but in this case modifying the style.css does not make any difference.
