### ISSUE TITLE
post index still cached after upload

### ISSUE THREAD

**Issue by shish** [shish/shimmie2#334]
<passing_by> main page doesn't alway update in time after uploading and you get the impression that your upload was never made

**Comment by sanmadjack** [comment]
@shish I don't know what it was 6 years ago, but this looks like it's a transaction timing issue, at least in my environment. I don't have multiple users but I still see this kind of behavior constantly. It 100% happens every time I hit save on the settings page, it always re-loads with the previous settings. Refreshing the page again then shows the new settings that I had been saving. I've found a change that so far has stopped it from happening at all.

This code is from index.php:

```
    // saving cache data and profiling data to disk can happen later
    if (function_exists("fastcgi_finish_request")) {
        fastcgi_finish_request();
    }
    $database->commit();
```
Most operations make use of a redirect after completing the operation. My theory is that when fast_cgi_finish runs, the request returns and the browser immediately redirects, requesting the redirected page. If that happens fast enough, the new page request can trigger before the commit operation from the previous request has completed, resulting in a request that receives the pre-commit data.

I don't know how much of a performance impact it would have on a large-scale site, but just moving the commit up before fastcgi_finish_request has so far stopped it from happening for me.

```
    $database->commit();

    // saving cache data and profiling data to disk can happen later
    if (function_exists("fastcgi_finish_request")) {
        fastcgi_finish_request();
    }
```

Again, this is just a theory as to what's happening, but so far it's solved the issue in my environment.
