### ISSUE TITLE
PHP warning in log file for htmlentities()

### ISSUE THREAD

**Issue by jgen** [shish/shimmie2#348]
Using PHP 5.3.2.

Looking in the error.log file for php and noticing a lot of these:

"PHP Warning:  htmlentities(): Invalid multibyte sequence in argument in core/util.inc.php on line 16"

Seems to be mainly when Shimmie is using the EXIF extension.

I thought that it might be due to this http://stackoverflow.com/questions/2327219/htmlentities-invalid-multibyte-sequence-error

but the code is already specifying "UTF-8" as the charset:

``` php
function html_escape($input) {
    return htmlentities($input, ENT_QUOTES, "UTF-8");
}
```

Hmm... I'm not quite sure what is causing this...

Here is the (censored) output from the log:

```
FastCGI sent in stderr: "PHP Warning:  htmlentities(): Invalid multibyte sequence in argument in /core/util.inc.php on line 16
PHP Stack trace:
PHP   1. {main}() /index.php:0
PHP   2. send_event() /index.php:86
PHP   3. ViewImage->onPageRequest() core/util.inc.php:1134
PHP   4. send_event() /ext/view/main.php:117
PHP   5. DataHandlerExtension->onDisplayingImage() /core/util.inc.php:1134
PHP   6. PixelFileHandlerTheme->display_image() /core/extension.class.php:216
PHP   7. html_escape() /ext/handle_pixel/theme.php:16
PHP   8. htmlentities() /core/util.inc.php:16" while reading response header from upstream...
```

**Comment by shish** [comment]
I haven't seen this for a while, not sure if people started agreeing on a standard or if PHP7 does encoding better; feel free to re-open if it's still an issue (ideally with an example of an image that triggers the problem)
