### ISSUE TITLE
Invalid URLs provided via $_GET don't cause an error

### ISSUE THREAD

**Issue by espressoelf** [shish/shimmie2#366]
When trying to upload URLs like the ones in #362 (wrong extension, incomplete transloads and files that are not images at all), Shimmie just redirects to the index page. I tried to fix that with #365 but failed horribly - the error massage always popped up (even if everything went fine). 

Since I can't locate the source of the problem on my own, I'm opening an issue. 

Edit 1: When uploading without extension: [01-Jan-2014 06:38:21 Europe/Berlin] PHP Notice:  Undefined index: extension in /srv/www/htdocs/shimmie2/ext/upload/main.php on line 349

Edit 2: We should just stop asap when there is no extension, since every file-handler relies on it. The problem seems that Shimmie tries all loaded file handlers (pixel and flash in my case), tests if the extension is supported (returns false; nothing is done so the loop continues: https://github.com/shish/shimmie2/blob/master/core/util.inc.php#L1123). But there is no error after the last handler so it just "displays" the upload status (https://github.com/shish/shimmie2/blob/master/ext/upload/main.php#L201) - which is a redirect to the index (https://github.com/shish/shimmie2/blob/master/ext/upload/theme.php#L279).

Edit 3: It looks like #365 wasn't completely wrong: https://github.com/shish/shimmie2/blob/master/core/extension.class.php#L145 silently continues with invalid extension or invalid data (and valid extension) so instead of my "else" I should've used something like

``` php
        elseif($this->supported_ext($event->type) && !$this->check_contents($event->tmpname)){
            throw new UploadException("Invalid or corrupted file");
        }
```

~~I'll let you check the code (and submit it) to avoid submitting garbage again =/~~ Sorry for the wall-of-text.

Edit 4: Re-opened #365 with new code.

**Comment by shish** [comment]
> So there still needs to be implemented some kind of "unhandled extension"-detection with a proper error-message.

This happened at some point in the past few versions \o/
