### ISSUE TITLE
Advanced Tagging v2 Broken?

### ISSUE THREAD

**Issue by jgen** [shish/shimmie2#412]
I have no idea if this extension even works, the JavaScript code that it uses seems to rely on the Dojo toolkit, but that isn't even part of Shimmie, or even included by the plugin.

Does anyone know if this even works at all?

See: ext/tagger/

From the comments:

```
 * Name: Tagger
 * Description: Advanced Tagging v2
```

**Comment by shish** [comment]
I never got this to work either, and nobody else has stepped up to fix it, so deleting in fd359fb0
