### ISSUE TITLE
Mass Tag Edit changes upper case letters

### ISSUE THREAD

**Issue by Neop** [shish/shimmie2#447]
Mass Tag Edit changes upper case letters to lower case (while other ways to add tags allow upper case).

I guess it can be fixed by removing strtolower() from line 247 in main.php of tag_edit:
https://github.com/shish/shimmie2/blob/master/ext/tag_edit/main.php#L247
$replace_set = Tag::explode($replace, false);

**Comment by sanmadjack** [comment]
@shish new bulk actions extension does not suffer from this issue. What do you think about removing the mass tag edit extension at this point?

**Comment by shish** [comment]
(Cleaning up old bug reports - Mass Tag Edit got removed, because Bulk Actions does the same thing better)
