### ISSUE TITLE
HTTPS Support for QR Code Extension

### ISSUE THREAD

**Issue by TheOpponent** [shish/shimmie2#477]
I migrated my website to HTTPS and I found that the only element that is not being served over HTTPS is the Google API used to generate QR codes.

**Comment by jgen** [comment]
I'm guessing that you are referring to these links?:

```html
<img alt='QR Code' src='http://chart.apis.google.com/chart?chs=150x150 ...' etc ...
```

**Comment by The-Excel** [comment]
Yes, simply changing the http:// breaks the links.

**Comment by jgen** [comment]
I've made a quick change to the make_http method as well as the QR extension to output "https://" if HTTPS is enabled on the server.

See pull request #479.

If possible, you can try it out and see if that works.

**Comment by The-Excel** [comment]
The links are still the same.

If it matters, I'm using CloudFlare's Flexible SSL to get HTTPS on my server.

**Comment by jgen** [comment]
This might have to do with the CloudFlare Flexible SSL setup.
(https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-Off-Flexible-SSL-Full-SSL-Full-SSL-Strict-mean-)
It seems that in this setup the site (shimmie) would not be even _aware_ that the content is being set via HTTPS to the user, as CloudFlare would be essentially wrapping up everything and sending it over.

**Comment by shish** [comment]
55e0e323 should fix this (tell the client to use whatever protocol they are using for the HTML to use the same protocol for the image, as we're doing in a few other places)
