### ISSUE TITLE
Extension "Handle archives" doesn't tag imported images

### ISSUE THREAD

**Issue by MayakoAelys** [shish/shimmie2#483]
Hi,

First, thanks for your great imageboard, as I have too many images to keep these in a folder hierarchy, I searched for a practical solution and found shimmie2.

The board works fine except for one point. I've activated the "Handle archives" extension and the upload works fine. But, there is an issue : no matter if I set tags on the individual upload or the whole upload, it keeps the "tagme" tag. I tried with single images and the same tags, it worked.

Is there an other way to upload multiples images ?

Thanks in advance!

**Comment by shish** [comment]
tags for archived images are taken from folder names within the archive, not from the tags in the web form -- it should probably do both I guess?

**Comment by shish** [comment]
The original motivation for this extension was for turning a folder structure like
```
cute/
    cat/
        cat01.jpg
        cat02.jpg
    bunny/
        bunny01.jpg
        bunny02.jpg
```
into four images in shimmie, two tagged with 'cute cat' and two tagged with 'cute bunny'. It seems like you're doing things the other way round; having all images zipped together with no folders, and then applying the same tags to every image via the upload form.

**Comment by MayakoLyyn** [comment]
"It seems like you're doing things the other way round; "
Yes, it's exactly how I tought it was working. It explains why it didn't work when I tried... 

"tags for archived images are taken from folder names within the archive, not from the tags in the web form -- it should probably do both I guess?"

My pull request only check for the tags in the web form, i'm going to cancel it so. Taking the tags both from the web and the archive folders seems a very good idea :)

Thanks for responding :+1:

**Comment by MayakoAelys** [comment]
> Sorry it took 9 years, but this is fixed in the main branch now ^^;

Damn. I completely forgot this xD

Thanks for the fix ♥️
