### ISSUE TITLE
Unable To Edit Existing Note On Image

### ISSUE THREAD

**Issue by ottenbel** [shish/shimmie2#485]
It looks like there is an issue with the notes extension.  The extension appears to be unable to catch the click event on an existing note.  So there is no way to edit or remove a note other then nuking all notes on an image and adding any notes back to the image.

**Comment by shish** [comment]
05a981d935bdd06083cebf9514cd71c6c8c1016c goes ahead and rewrites the frontend javascript from scratch, and I've checked that editing works there
