### ISSUE TITLE
Upgrading Issue

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#487]
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1004

Warning: array_change_key_case() expects parameter 1 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1007

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/xxx/public_html/core/util.inc.php on line 1008

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1004

Warning: array_change_key_case() expects parameter 1 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1007

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/xxx/public_html/core/util.inc.php on line 1008

Fatal error: Call to undefined function mb_strlen() in /home/xxx/public_html/core/imageboard.pack.php on line 537

I tried to do an update everything works but I can't upload when I try to upload I get these errors any help would be appreciated.

**Comment by PronMaster** [comment]
Okay I figured out the fatal call error but now the browser suggestions does not want to come up any help on fixing that?

**Comment by jgen** [comment]
Hello, thanks for the feedback.

I think I have a fix for the warnings, but I haven't tested it yet.

As for the undefined function error, what version of PHP are you using?

(You can check with the System Info link on the board, or the url /system_info )

**Comment by PronMaster** [comment]
its says PHP: 5.4.29

**Comment by jgen** [comment]
Thanks! I wasn't sure if perhaps you had an older version of PHP.

Anyways, it seems as though mb_strlen is not enabled by default for many distributions of PHP (http://stackoverflow.com/questions/6419102/fatal-error-call-to-undefined-function-mb-strlen)

If you have a Debian/Ubuntu based system, then you could check to see if your distro's PHP package  has it with this:  (although it should)
`apt-cache search mbstring`

**Comment by PronMaster** [comment]
Thanks jgen that fixed the fatal error and the rest of those errors, but I have another issue after upgrading the tag suggestions not showing up any help with that as that is key on my site?

**Comment by PronMaster** [comment]
I don't want to compile you with issues jgen, but I found another bug the fit to height or width doesn't work on the new version.

**Comment by jgen** [comment]
Hmm. I upgraded my site as well and the tag suggestions for when you edit a picture no longer work either. Also, the auto-complete for the search box now only shows one suggestion.

I would suggest that you file a separate issue for each bug (that you think is separate) as that might help to keep track of what is broken. (As otherwise this could turn into a very long thread...)

**Comment by jgen** [comment]
Fixed by #488
