### ISSUE TITLE
Tag suggestion drop down not working

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#489]
Hello just to let you know with the latest upgrade the tag suggestion drop down box is bugged I tried it with a different browser, computer even my phone nothing. A little help would be appreciated as this is a big part of the script for my site anyway thanks.

**Comment by jgen** [comment]
Thanks PronMaster.
Just to add a bit more info, do you happen to have a rough idea what the previous version was that you were using? (ie: the date you last updated it and/or installed it)
Also, are you using the master branch or the dev branch?
Thanks!

**Comment by PronMaster** [comment]
Well I thought it was upgrading it self but it wasn't so its been a year since my site been up so I was using version shimmie 2.5.0 master I believe.

**Comment by PronMaster** [comment]
Ah this bug is killing my site so I'm going to downgrade until you guys can get this working.

**Comment by jgen** [comment]
Hi PronMaster,
This bug should be fixed in the master branch now.

**Comment by PronMaster** [comment]
I got some different errors when I was trying to upload a duplicate picture 

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/xxxpublic_html/core/util.inc.php on line 999

Warning: array_change_key_case() expects parameter 1 to be array, boolean given in /home/xxx/public_html/core/util.inc.php on line 1002

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/xxx/public_html/core/util.inc.php on line 1003

**Comment by jgen** [comment]
Thanks.
Those warnings are related to #487.
I will open a pull request shortly.

**Comment by jgen** [comment]
This issue has been fixed in both master and develop. (Thanks for merging Shish).
Closing issue.
