### ISSUE TITLE
Picture Bugs

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#490]
These are the small bugs I found with the latest version of shimmie the fit picture to width and height is bugged also the information for the picture like the source and tags box don't load it says at set if you could look into this shimmie crew this would be great thanks.

**Comment by jgen** [comment]
Thanks for opening the issue.

Do you happen to have a screenshot of how the images aren't looking right?
(Or perhaps a link? -- you can email me directly if you'd rather not post here.)

Also, when you say that the source and tag box don't load, what exactly do you mean "it says at set" ?
(Sorry, I don't quite understand.)

Thank you!

**Comment by PronMaster** [comment]
I sent you a email jgen

**Comment by jgen** [comment]
Thanks PronMaster.

I have created a pull request to fix the issue with the "Fit to ..." not working. (See #492 )
