### ISSUE TITLE
Rating & Relation not showing during Upload

### ISSUE THREAD

**Issue by ghost** [shish/shimmie2#493]
Is it intended that the only option I've got while uploading is to tag the image and provide a source?
Everytime I'm uploading something I do have to edit the rating as well as the parent/child afterwards through accessing the picture.
Is this normal? If so, is there a way to include those two options within the upload page itself?

**Comment by funkygamer** [comment]
Push

**Comment by shish** [comment]
Not intended per se, but that is the case (there's no nice way for extensions to add extra fields to the upload form). It should be possible to do with code changes

**Comment by shish** [comment]
"Add extra fields during upload" is already an issue here, so closing this as duplicate
