### ISSUE TITLE
Random Tip extension causes a MySQL error

### ISSUE THREAD

**Issue by Xetanai** [shish/shimmie2#494]
[Created a pull request for this issue](https://github.com/Xetanai/shimmie2/tree/patch-1)
This error persists on every page and renders the site unusable until manually disabled fromt the extensions file.

I believe it is the error of the highlighted code in this image. I will try out a few things before confirming this theory.
![image](https://cloud.githubusercontent.com/assets/4240796/8077954/e9cb4402-0f27-11e5-9264-d3c71679e384.png)

**Comment by Xetanai** [comment]
Confirmed, training comma in the end of that MySQL query was to blame.
![err_1](https://cloud.githubusercontent.com/assets/4240796/8078037/a03511f0-0f28-11e5-8d4d-278b653ad94f.PNG)
![err_2](https://cloud.githubusercontent.com/assets/4240796/8078038/a04560f0-0f28-11e5-89e3-6ae27e90d91b.PNG)

**Comment by jgen** [comment]
Awesome!
Thank you!

**Comment by jgen** [comment]
Fixed by commit 10e7dd2
