### ISSUE TITLE
403 on Saving Config

### ISSUE THREAD

**Issue by Xetanai** [shish/shimmie2#496]
Board is forever locked at the current configuration due to denial of access for unknown reasons.
I am logged in as the administrator account set on installation.
![image](https://cloud.githubusercontent.com/assets/4240796/8078299/bc2dcc1a-0f2a-11e5-851a-7efc83ed0441.png)
Looking at the code, it seems to me that can() is returning false even though my UserClass is admin.
![image](https://cloud.githubusercontent.com/assets/4240796/8080958/957237f0-0f3e-11e5-94cc-f8d884e0daa5.png)

**Comment by jgen** [comment]
Hmm, this one seems rather odd. First off, are you sure that this is Shimmie that is giving you the error?

The reason I ask is that the Shimmie error for an invalid user attempting to save the config is done via a full HTML webpage and the error message is slightly different as well:
 `You do not have permission to access this page`
vs. the screenshot above, which looks more like a server error page.

Off the top-of-my-head, do you know if the webserver (or the PHP service/daemon) has write access to the /data/ folder?

Do you have any error logs from the server and/or the PHP service/daemon?

**Comment by Xetanai** [comment]
I'm 50% sure.I hadn't changed any permissions, and the file 403-ing was the index.php which handles everything, though it was likely an included file that was inaccessible. To test, I set all permissions to 777 and that made the error a 502 server-wide

Date: Thu, 11 Jun 2015 22:10:50 -0700

**Comment by jgen** [comment]
Hmm, well the error code being different when you changed the permissions to 777 is interesting.

Further more, the 502 error code is for a "Bad Gateway" which could be any number of things (other than Shimmie). If you have access to the php error logs then you might be able to track down what is happening.

When you say that it was server-wide do you mean on all pages? (as in you changed permissions to 777 and then _all_ pages gave you the 502 error?)

What server setup are you using?

**Comment by shish** [comment]
These 403s and 502s do indeed look like web server errors more than shimmie errors, so web server error logs would be a great help

**Comment by Xetanai** [comment]
I don't have access to the server anymore, so the logs are gone too. I recall looking at them from the advice a friend gave me, and it was the fault of the server, not Shimmie
