### ISSUE TITLE
Ranking System

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#497]
Hello I think a ranking system would be great because as far as I can tell the voting system is pretty useless, and it would be great to see what's the most favored image or highest rated/voted image even the lowest rated one something like chan.sankakucomplex.com (Warning NSFW).

**Comment by shish** [comment]
There should be filtering by votes (something like "score>10") and ordering (something like "order_by=score") -- though those are fairly non-obvious; do you want anything other than filtering and ordering?

**Comment by PronMaster** [comment]
Yeah anything to let the audience know what's hot or what's popular this week because some posts on my site if there not on the front page people don't see them.

**Comment by DakuTree** [comment]
There is the popular_by_day, popular_by_month & popular_by_year pages which may be what you're looking for.
They aren't linked from any pages though, so they would have to be added to the theme you are using.

**Comment by PronMaster** [comment]
I guess that will due Daku thanks
