### ISSUE TITLE
reCAPTCHA V2

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#498]
Hello I recently got an email for reCAPTCHA v2 are there any plans to upgrade the current reCAPTCHA?

**Comment by shish** [comment]
I wasn't aware that v2 was a thing; does the email give any info about upgrading?

**Comment by HungryFeline** [comment]
http://googleonlinesecurity.blogspot.de/2014/12/are-you-robot-introducing-no-captcha.html and https://developers.google.com/recaptcha/intro are linked. They contain everything needed :)

**Comment by jgen** [comment]
Here is a copy of the email that I got:


> Dear Webmaster,
>
> You're receiving this email because you're registered as a website administrator for a site that uses reCAPTCHA.
>
> Google launched [reCAPTCHA v2](http://googleonlinesecurity.blogspot.com/2014/12/are-you-robot-introducing-no-captcha.html) (i.e. No CAPTCHA reCAPTCHA) in Dec, 2014. The new version provides a more simplified user experience than reCAPTCHA v1, with an enhanced spam fighting mechanism.
>
> ![Image of v2](http://4.bp.blogspot.com/-wt7yljKcU_8/VH5MJTUCBOI/AAAAAAAAACw/WKqE3ixUUdw/s1600/Recaptcha_anchor%402x.gif)
>
> Action requested: please upgrade your site implementation to reCAPTCHA v2.
>
> Please refer to the [developer guide](https://developers.google.com/recaptcha/intro) for integration details. We hope you enjoy the new reCAPTCHA.
>
> Thank you,
> reCAPTCHA Support
