### ISSUE TITLE
Varnish Cache 4 configuration for Shimmie2

### ISSUE THREAD

**Issue by cyb-er** [shish/shimmie2#501]
Similar to this -> https://github.com/shish/shimmie2/wiki/Varnish but updated to be compatible with Varnish Cache 4
Does anyone have it and would be willing to share?

**Comment by shish** [comment]
I have one~ full of site-specific hacks, but it shouldn't be too hard to clean up

**Comment by cyb-er** [comment]
So, would you be so nice and share it with me? Please please? :)
You could email it to: temp21@nym.hush.com or just post it here.

(I was struggling today with finding the way to install varnish cache 3.0.7 just to get it working with shimmie but it seems that FreeBSD 3.0.7 version is deleted from FreshPorts, so the only way to get it would be to compile it on my own from the source but it's getting a bit too difficult. So the config for Varnish Cache 4 would save me lots of effort.)

**Comment by shish** [comment]
https://github.com/shish/shimmie2/wiki/Varnish-4

**Comment by cyb-er** [comment]
This should be good enough! Thank you so much! =)
