### ISSUE TITLE
Question about "test" files

### ISSUE THREAD

**Issue by cyb-er** [shish/shimmie2#502]
Can I remove all files/folders with the name "test" in it? Or are there are any dependencies in actual shimmie code that require those files? I understand those are files related to development testing and not actual shimmie software files.

**Comment by shish** [comment]
`tests/*` and `ext/*/test.php` can be removed, though I'm not sure why you'd want to o.o (They aren't even loaded into memory unless you run the test suite)

**Comment by cyb-er** [comment]
I just like to have everything in nice order, so then it's easier do maintain and develop. My logic is also the less executable server-side code the less chances of possible vulnerabilities.
Anyway, thank you for an answer. :)

**Comment by shish** [comment]
But tests are /for/ maintenance and development; and even if you don't use them, by removing them you'll end up having conflicts where you're deleted a file and somebody else has updated it (assuming you're using git, which you *really* should be if you want to do development work).

Less space for vulnerabilities to hide makes sense in theory, but in practice there is no executable code in the test.php files, so they're about as dangerous as a .txt file...

**Comment by cyb-er** [comment]
Well, I cannot argue with that. :) I don't use git for development. I develop everything locally on my pc. It's just the way I do things.

**Comment by shish** [comment]
I develop everything locally too, but having a source code manager like git is still a massive productivity boost :)

(Anyway, closing now because the question is answered, but I'm still happy to answer questions about git if you're curious ^_^)
