### ISSUE TITLE
No handler could be found for the page 'bulk_add'

### ISSUE THREAD

**Issue by lisandro52** [shish/shimmie2#505]
Hi! 
I installed shimmie on my Debian home-server yesterday. 
Everything was running fine - I even tested by uploading 9k~ of images using the 'Bulk Add' extension, and it worked fine.
Today, whenever I try to use the Bulk Add just like before, I get the message

`No handler could be found for the page 'bulk_add'`

Any ideas on what could it be the problem? I'll post the configuration or anything you need, ask away.
Thanks

**Comment by shish** [comment]
Did you upgrade between it working and not? (Trying to figure out if it's a code change or something else...)

**Comment by shish** [comment]
Also, which version are you using? (git ID if possible, or the version number in core/sys_config)

**Comment by lisandro52** [comment]
Hi, Shish! Thanks for the reply.
No, I didn't upgrade after the installation. Didn't pull any changes, if that's what you mean.

core/sys_config says version 2.5.4.
The git log says I'm on commit 4ebcf449e which is the latest one, I believe from Jun 1.

Tell me if you need anything else, and thanks for the help

**Comment by lisandro52** [comment]
Oh and btw, I just realized that I installed it by making a git clone from this repo. Maybe it was just too edgy ha!

**Comment by lisandro52** [comment]
I've been trying a few thing but with no success:
-Removed entire shimmie2 directory.
-Dropped database and started from scratch.
-Selected just Admin Controls and Bulk Add extensions.

Still says 'No handler could be found'.

**Comment by DakuTree** [comment]
Have you tried the develop branch?
There was a commit (2aea79ac356c572ef5601cb3a31b862afb9ab18d) which changed some stuff with bulk_add which hasn't made it into master yet. Might fix the issue you are having

**Comment by lisandro52** [comment]
Same thing but different.
I cloned develop, and started the bulk add of just a few hundreds photos (200~).
The php-fpm process then ate 3GB of RAM and never stopped adding more and more until I restarted the service.
After restarting it, I went to try the bulk add again, but it showed the original error message...

**Comment by shish** [comment]
That is very strange o_o;;

Maaaaybe there's an error message, but instead of showing the error it shows nothing, and then the default "nothing handled this request" error is shown? (Which is misleading, because something did handle it, it just didn't have any output)

**Comment by DakuTree** [comment]
RAM eating issue seems to be due to this getting stuck in an endless loop: https://github.com/shish/shimmie2/blob/develop/core/util.inc.php#L1278

**Comment by DakuTree** [comment]
No handler exists error & RAM bug should be fixed in the above PR.

**Comment by lisandro52** [comment]
Nice. I'm at work now, but once I get home, I'll test it and give some feedback. Thanks for the help!

**Comment by lisandro52** [comment]
I'm so fucking stupid...
After so many reinstalls and things I tried, there was one simple thing that's always the root of these kind of problems: file permissions.
I was so damn sure that everything was OK with the files that I never checked those... They were '700', and the owner wasn't www-data.
I'm so sorry guys.
I'm now changing permissions to test this a bit more, and I'm reproducing the same error (it's different now that DakuTree changed the message tho). Maybe we should check for folders/files perms with [is_readable()](http://php.net/manual/es/function.is-readable.php) while doing the file list?
