### ISSUE TITLE
Bandwidth 

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#509]
Hello my site is getting bigger I noticed bandwidth staring to become a issue is there any way to use the amazon s3 to help reduce the usage I already reduced the file size?

**Comment by shish** [comment]
There is an "Amazon S3" extension which *should* copy uploaded files to an S3 bucket, and then in advanced config you can change the image URL from eg `/_images/$hash/$tags.$ext` to `http://mybucket.s3.amazon.com/images/$hash.$ext` -- I haven't used that myself for a few years though so it may have bit-rotted...

(Also I'm surprised that S3 seems like a good option; it always came out way more expensive than self-hosting in my own tests o_O  Though again, I've not looked at it for years)

**Comment by HungryFeline** [comment]
If traffic is a problem try using a host like OVH. They offer traffic flats with all their servers. See http://www.kimsufi.com/en/ for their cheapest ones.

**Comment by PronMaster** [comment]
Hey shish would this do it for all my post or just some and if so is there anyway to switch it it up like some go to the s3 server and other go to my self hosting sever?

**Comment by shish** [comment]
The extension only syncs new files as they're uploaded, so you'd need to either upload old posts some other way (possibly worth adding a feature to the extension to do this), or hack core/imageboard.pack.php:Image::get_image_link() to return s3 for some images and local for others

(Also something that may or may not be helpful - if you have several image mirrors, you can load balance between them by setting the image path to eg `http://mirror-{1=50,2=50}.mysite.com/images/$blah` to split traffic evenly between `mirror-1.mysite.com` and `mirror-2.mysite.com`)

**Comment by jgen** [comment]
Random idea, (and unrelated to using s3), but one thing you could do is take a look at the largest images on your site.
You can search for this: `order=filesize_desc` and it will sort all images by filesize in descending order.

If you have large animate GIF images on your site one thing you could do is consider converting them to webm.
