### ISSUE TITLE
[PHP7] Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by JarJak** [shish/shimmie2#510]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; TestSuite has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/test_case.php on line 477

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; BadTestSuite has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/test_case.php on line 612

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; NestingXmlTag has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/xml.php on line 292

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; NestingMethodTag has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/xml.php on line 342

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; NestingCaseTag has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/xml.php on line 382

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; NestingGroupTag has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/xml.php on line 422

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SimpleTestXmlParser has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/xml.php on line 474

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SimpleRealm has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/authentication.php on line 18

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SimpleAuthenticator has a deprecated constructor in /home/jarek/public_html/shimmie/lib/simpletest/authentication.php on line 131

Same error in various locations

**Comment by shish** [comment]
This is mostly fixed by the "replace simpletest with phpunit" branch (which is working fine, just not all the unit tests are converted to the new format yet)

**Comment by JarJak** [comment]
it happened to me not only in simpletext lib

**Comment by shish** [comment]
These should all be gone since a while ago, so closing this
