### ISSUE TITLE
Finish porting tests to phpunit

### ISSUE THREAD

**Issue by shish** [shish/shimmie2#516]
SimpleTest -> PHPUnit conversion got merged because even when incomplete it was a significant improvement. Being complete would be even better though. I'll aim to port a test per evening, but pull requests to help out would be very appreciated :)

```
$ ./phpunit.phar --configuration tests/phpunit.xml --debug
[...]
Tests: 94, Assertions: 297, Skipped: 18, Incomplete: 13.
```

To give an idea how much there is left to do:

```
$ git grep "markTestIncomplete"  | cut -d: -f1 | uniq | xargs wc -l | sort -n
      29 ext/favorites/test.php
      33 ext/image_hash_ban/test.php
      35 ext/featured/test.php
      42 ext/pools/test.php
      43 ext/report_image/test.php
      54 ext/rating/test.php
      57 ext/random_image/test.php
      59 ext/pm/test.php
      60 ext/numeric_score/test.php
      76 ext/tag_edit/test.php
      85 ext/tips/test.php
     108 ext/index/test.php
     681 total
```

**Comment by lisandro52** [comment]
Is there anything someone, who has some experience with C# unit tests and some PHP knowledge, could do to help with this issue?

**Comment by JarJak** [comment]
I can't see any C# experience needed here.

**Comment by shish** [comment]
It's mostly shimmie knowledge TBH - the old tests were outside-in, the new are inside-out; so where previously the test would be `click("Button Label")` it's now `send_event(new ButtonClickedEvent())` etc

(Which is slightly more abstract, as you're prodding the code directly instead of pretending to be a web browser; but it's about 200x faster, a bunch more reliable, and way more convenient. Plus, this testing tool is maintained, where the last is several years out of date and incompatible with php7...)

**Comment by JarJak** [comment]
Personally I prefer writing tests in Codeception - very nice TDD/BDD framework built on top of PHPUnit / Selenium, easily extensible and able to write unit, functional and acceptance tests in various formats.

**Comment by shish** [comment]
This got done
