### ISSUE TITLE
Consider merging 'develop' branch into 'main' again

### ISSUE THREAD

**Issue by xXAdamXx** [shish/shimmie2#517]
Somehow when I start extensions, it simply gives me an error, and I'm locked out, PERIOD. Delete The Config, Nope. Change Services, Nope.

Internal Error

Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ENGINE=InnoDB DEFAULT CHARSET='utf8'' at line 6

Query: CREATE TABLE tips ( id INTEGER PRIMARY KEY auto_increment, enable ENUM('Y', 'N') NOT NULL DEFAULT 'N', image TEXT NOT NULL, text TEXT NOT NULL, ) ENGINE=InnoDB DEFAULT CHARSET='utf8'

Version: 2.5.4

**Comment by JarJak** [comment]
It's because you are using master branch, which is outdated and buggy. Patch is in develop branch.
@shish any plans for updating master branch?

**Comment by JarJak** [comment]
https://github.com/shish/shimmie2/blob/develop/core/database.class.php#L724
this is the line you need

**Comment by xXAdamXx** [comment]
Ah. So git clone {github} Develop?

**Comment by shish** [comment]
cherry-picked that into master, will look at merging in the changes from develop since it has been a while~

**Comment by xXAdamXx** [comment]
Damn. Just got suspended from Byet.host...

**Comment by jgen** [comment]
Going to rename this issue to "Merge develop into main".

**Comment by jgen** [comment]
Gah, sorry for renaming so many times... my keyboard is failing. :(

**Comment by shish** [comment]
merged~
