### ISSUE TITLE
ext_manager page should show when extensions can't be enabled

### ISSUE THREAD

**Issue by DanielOaks** [shish/shimmie2#525]
The `ext_manager` should show when extensions aren't able to be enabled due to `$db_support` not supporting the currently used db.

I was trying to work out why a certain extension wasn't showing at all, even though it was enabled on the `ext_manager` page and everything looked good. Maybe putting a little orange mark or something next to the extension name saying something like "This won't be enabled due to the currently selected database. This extension can be used on the mysql, sqlite databases" when you hover over it?

**Comment by dali99** [comment]
:+1:

**Comment by shish** [comment]
This got done a while ago
