### ISSUE TITLE
Bookmarks EXTension

### ISSUE THREAD

**Issue by cyb-er** [shish/shimmie2#532]
Could anyone explain to me what this extension does?
I was wondering since a while and I can't figure it out just by looking at code.
Description says:"Allow users to bookmark searches".
But I don't see any option in shimmie like this (when it's activated) so, I am missing something.. :)

**Comment by HungryFeline** [comment]
The code seems to be incomplete and it has no theme.

**Comment by shish** [comment]
Yeah, it is incomplete and doesn't do much anyway; maybe worth just removing it, and anyone who wants their bookmarks to work across PCs can use a browser plugin instead of a website-specific thing...
