### ISSUE TITLE
Commit 2aea79ac356c572ef5601cb3a31b862afb9ab18d broke bulk upload 

### ISSUE THREAD

**Issue by Enerccio** [shish/shimmie2#533]
Specifically, you can't upload from nested subdirectories...

**Comment by Enerccio** [comment]
No response?

**Comment by shish** [comment]
It it still broken? Just tried uploading from nested subdirectories and it seems to have worked ok :S

**Comment by Enerccio** [comment]
Not sure, will try when I am home, but last time I got white screen because it couldn't search it correctly.

**Comment by Enerccio** [comment]
Nope, tried checkout from git, added whole path as a+r and tried to upload, no results

**Comment by shish** [comment]
Tested and it's still working for me; if it's still an issue feel free to re-open with more details ^^
