### ISSUE TITLE
Thumbnail generator black background

### ISSUE THREAD

**Issue by dali99** [shish/shimmie2#536]
The thumbnail generator produces black when it sees something transparent. looks pretty bad:

![blackthumb](https://cloud.githubusercontent.com/assets/990767/12058998/472aeadc-af53-11e5-9d58-80fe65097aed.PNG)

**Comment by sanmadjack** [comment]
This is partially resolved by the recent graphics engine changes. If you're using jpg thumbnails it's still black, but if webp (or other future transparency-supporting formats) are used the thumbnail should preserve the transparency.
