### ISSUE TITLE
Danbooru style displays random image outside of its div

### ISSUE THREAD

**Issue by Xetanai** [shish/shimmie2#539]
In the Danbooru theme with the random image block, if the image is wider than it is tall, it will clip outside of it's div and into the page. I have already created a fix, which I will upload in a moment.

**Comment by Xetanai** [comment]
I can't seem to remember how to make a pull request. Haven't used Github in a while. Just add this to the danbooru theme's style.css

img[id^="thumb_rand"] {
	display: block;
	max-width: 100%;
	max-height: 100%;
	height: auto;
	width: auto;
	object-fit: contain;
}

**Comment by Xetanai** [comment]
Seems object-fit is not supported in Edge, which causes this bug. I'm working on a workaround now.
![godihateie](https://cloud.githubusercontent.com/assets/4240796/12233406/a5d27fd2-b82c-11e5-9e02-658aa2dd8f94.PNG)

**Comment by Xetanai** [comment]
New fix, confirmed working in MS Edge 25.10586.0.0 and both aforementioned browsers.

img[id^="thumb_rand"] {
display: block;
max-width: 100%;
max-height: 100%;
height: auto !important;
width: 100% !important;
object-fit: contain;
}

**Comment by PronMaster** [comment]
Hello I know I'm little late but I'm using the warm template where exactly do I put this?

**Comment by shish** [comment]
Should be fixed by 866b77ab
