### ISSUE TITLE
multi-search with wildcard broken

### ISSUE THREAD

**Issue by shish** [shish/shimmie2#547]
image with 3 tags: foo1, foo2, bar

search for: foo*, baz

image shows up, I guess because number of tags matched = number of tags searched for

**Comment by shish** [comment]
Gah, Daku fixed this for mysql, and then my attempt at merging the two search paths a little to stop the huge amount of deduplication broke it again, and it's 2am with work tomorrow morning >_<

We now have some much better test cases at least, will try and bring the fix back to all DB engines tomorrow /o/

**Comment by DakuTree** [comment]
Looks like this broke again during some of the recent deduping commits.[¹](https://github.com/shish/shimmie2/commit/dc83d4ace72e55e2b70bf17f17d02cd5507f61ad#commitcomment-17922089) [²](https://github.com/shish/shimmie2/commit/bfa1dc20c01b50da775c55b93db9d16792b093d1#commitcomment-17922121)

Not sure how to go about fixing without reverting a bunch of the changes :|

**Comment by shish** [comment]
Yeah, I think my re-fix-wildcards branch is closer to where we want to end up -- it keeps wildcards in their raw form (ie, "a string with a wildcard" rather than "an array of plain tags") until the last moment before executing SQL, so that we aren't losing that context.

I'm currently installing mysql on my laptop so that I can test that code path...

https://github.com/shish/shimmie2/blob/re-fix-wildcards/core/imageboard.pack.php#L985
