### ISSUE TITLE
Problem with Uploading

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#549]
Hello I'm having a issue with uploading large files like 20+ MB when I try to upload them to my site after its done the page just refreshes it shows no error or nothing so I'm confused what could be causing this any help?

**Comment by shish** [comment]
When I've seen that happen before, the cause was the web server (eg apache, nginx) settings being set to reject large files, so all shimmie sees is somebody hitting the /upload page with no files attached to their request

**Comment by PronMaster** [comment]
Nginx was the issue its fixed thanks.
