### ISSUE TITLE
shimmie url is ../home/artlowbr/public_html/post/list instead of ../post/list

### ISSUE THREAD

**Issue by trollworkout** [shish/shimmie2#561]
see here http://artlowbrow.ml/

**Comment by shish** [comment]
What web server config are you using?

**Comment by trollworkout** [comment]
@shish  I have no control over the web server is a free hosting server + my own free domain. I just want to be able to control what the root folder is from config perhaps.

**Comment by shish** [comment]
c14a360 adds an option to force it - I wonder which host you are with? I try to make things automatically work in most common situations, so it would be nice to investigate

**Comment by trollworkout** [comment]
@shish  When is the new version going to be available? 

Also thank you for this option. 

My host is called https://x10hosting.com/  It offers unlimited anything (including unlimited connections at the same time) though a limited speed/shared server for free. Is just good for start up.

**Comment by shish** [comment]
If you're using git, it's available now; for zip files I just need to figure out how to package the composer dependencies nicely...

Either way, you should be able to modify the files in the same way to get the same effect of adding the option - then to make use of the option, open up data/config/shimmie.conf.php and add

```
define("BASE_URL", "/");
```

**Comment by trollworkout** [comment]
@shish  Thank you shish 👍  I will try to figure out how to use the new version from github with  composer . I don't have control over the server or over ffmpeg stuff so hopefuly it will work on a shared free web hosting system.  Currently I am using the latest zip version.
