### ISSUE TITLE
Improper tag validation can cause errors [develop]

### ISSUE THREAD

**Issue by im-mi** [shish/shimmie2#564]
Affected branch(es): [develop](https://github.com/shish/shimmie2/tree/develop)

Recent changes to how `Tag::explode` is used mean that tags aren't always fully validated. Either it tries to add duplicate tags or it tries to set to zero tags. In either case, an error is produced.

It happens in at least the following cases:
- Adding a duplicate tag using the mass tagger (duplicate tag error) (see 89dffd569a9d73c44d37990c456cae9884805b5f)
- Removing all tags using the mass tagger (zero tags error) (see 89dffd569a9d73c44d37990c456cae9884805b5f)
- Setting an image's tags to only metatags (zero tags error)
- Uploading an image with only metatags (zero tags error)

Relevant commits:
- 89dffd569a9d73c44d37990c456cae9884805b5f (no longer uses `Tag::explode` in the last step, bypassing necessary validation)
- 7be951b271c8a9e285e599206cfeac622e42bff3 (?)
- ... possibly more

**Comment by im-mi** [comment]
On a related note, an SQL error is shown if one tries to use the mass tagger to remove all of a post's tags (by using negative tags). It's caused by the same reason.

> Warning: assert(): array ( ): "is_array($tags) && count($tags) > 0" failed in \core\imageboard.pack.php on line 608
> Internal Error
> 
> Message: Tried to set zero tags
> 
> Version: 2.5.5+ (on 7.0.8)

**Comment by rogueralsha** [comment]
They recently corrected an issue with bulk-imported tags not using the proper events, so now this is affecting the bulk uploader too.

**Comment by Diftraku** [comment]
Not sure if relevant to this issue, but a really dirty workaround is to add `IGNORE` to the SQL-query in `imageboard.pack.php` at line 646:
```
INSERT IGNORE INTO image_tags(image_id, tag_id)
```

This causes any key constraints (ie. duplicate entries) to silently fail. I **do not recommend anyone to use this** as this may have some issues down the line. I kept having issues with `upload_collision_handler` set to `merge` and using `ouroboros_api` to upload an already uploaded image, causing the dupe handling to occurr.

**Comment by shish** [comment]
This should be working now, feel free to reopen if it's still an issue
