### ISSUE TITLE
Creating a post with zero tags is possible by using one long tag

### ISSUE THREAD

**Issue by im-mi** [shish/shimmie2#565]
It's possible to create a post with zero tags by setting its tags to one long tag (>255 characters in length). Posts with zero tags show up in the list correctly, but are absent when searching for `tags:<1`.

This happens because [`Tag::explode`](https://github.com/shish/shimmie2/blob/e7403819a7e9201b403fb4922dd7ecfa14b264e9/core/imageboard.pack.php#L1137) does not reject tags that exceed the maximum length specified in [`Image::set_tags`](https://github.com/shish/shimmie2/blob/e7403819a7e9201b403fb4922dd7ecfa14b264e9/core/imageboard.pack.php#L598). It sees at least one valid tag and therefore does not add a tagme tag.

**Comment by shish** [comment]
Should be fixed with the above, sorry for the delay :3
