### ISSUE TITLE
Cannot search for tag ending in period when "Nice URLs" is enabled

### ISSUE THREAD

**Issue by im-mi** [shish/shimmie2#566]
It's not possible to search for tags that end in a period when "Nice URLs" is enabled. When attempting said search, the trailing period will be truncated.

**Comment by shish** [comment]
This is working for me on the testbed, where is it not working for you?

http://shimmie.shishnet.org/v2/post/list/test./1

**Comment by im-mi** [comment]
It works for me on the testbed, but I can't get the same result on my local server (can't link to it). Maybe it's actually a server configuration issue. I'll be looking into this more.

**Comment by im-mi** [comment]
I've confirmed that this isn't an issue with Shimmie, rather with the server.

Apparently, it's rewriting any path with trailing periods to a different path without any. For example, it allows accessing a file named 'test' with any number of trailing periods (ex. 'test', 'test.', and 'test.......' all refer to the same file). This all happens before Shimmie gets the path, so there's nothing that can be done here.

... looks I'll have to find someone else to blame

**Comment by im-mi** [comment]
For anyone else who encounters this issue: It's a quirk of Apache for Windows. You can find similar issues on the Apache bug tracker [here](https://bz.apache.org/bugzilla/show_bug.cgi?id=20036) and [here](https://bz.apache.org/bugzilla/show_bug.cgi?id=42686).

What it all means is this: For each directory or file name, trailing periods will get removed. Additionally, consecutive slashes will get collapsed into one. Affected is Apache for Windows and no others (to my knowledge). As a result, you cannot search for tags that would necessarily break these rules unless you disable "Nice URLs" first.

And lastly: It's unlikely to ever get fixed, so strap in.
