### ISSUE TITLE
Error when viewing random image if user does not have sufficient privileges

### ISSUE THREAD

**Issue by im-mi** [shish/shimmie2#567]
### Description

An error is shown when viewing a random image if the user does not have sufficient privileges (ex. safe only, safe and questionable, etc.). This affects both the `random_image` and `random_list` extensions.
### Cause of Error

This happens because `Image::by_random` returns `null` if the user does not have sufficient privileges to view the image that was selected.
### Error Messages

Error displayed by `random_image`:

```
No handler could be found for the page 'random_image/view'
```

Error displayed by `random_list`:

```
Fatal error: Uncaught TypeError:

Argument 1 passed to BaseThemelet::build_thumb_html() must be an instance of Image, null given, called in \ext\random_list\main.php on line 41 and defined in \core\basethemelet.class.php:50

Stack trace:
  #0 \ext\random_list\main.php(41): BaseThemelet->build_thumb_html(NULL)
  #1 \core\util.inc.php(1521): RandomList->onPageRequest(Object(PageRequestEvent))
  #2 \index.php(98): send_event(Object(PageRequestEvent))
  #3 {main} thrown in \core\basethemelet.class.php on line 50
```

**Comment by shish** [comment]
The random image page now does a full search query (which includes all the permission stuff), so this should have been fixed a while ago
