### ISSUE TITLE
Pool post count doesn't update after removing posts from pool

### ISSUE THREAD

**Issue by im-mi** [shish/shimmie2#568]
When removing a post from a pool, its post count doesn't get updated. This happens whether the post is removed through the pool UI or by deleting the post itself.

Fixing the former case seems simple enough. It looks like it updates the post count here in [`add_posts`](https://github.com/shish/shimmie2/blob/89dffd569a9d73c44d37990c456cae9884805b5f/ext/pools/main.php#L537-L542). Perhaps the same should be done here in [`remove_posts`](https://github.com/shish/shimmie2/blob/89dffd569a9d73c44d37990c456cae9884805b5f/ext/pools/main.php#L588).

That leaves updating the post count when a post gets deleted. A rough fix was implemented by https://github.com/DakuTree/shimmie2/commit/ccb292291b83b75d5b61b87d693a94afaf711d14, but it involves recalculating every pool's post count any time a post gets deleted.

**Comment by sanmadjack** [comment]
@shish looks like this is fixed in develop
