### ISSUE TITLE
Reset thumbnails for all images

### ISSUE THREAD

**Issue by davidh8** [shish/shimmie2#592]
how i reset thumbnails for all images?
I have 30000 images.
Please, any help is important

**Comment by im-mi** [comment]
There's no built-in way, as far as I know, but there is this extension: https://github.com/im-mi/regen_all_thumbs

It will likely take several hours to finish. And, if possible, I recommend renaming/deleting the old thumbs directory and keeping the "force" option off. That way you can resume later if necessary.

**Comment by sanmadjack** [comment]
@shish Would you mind if I added functionality for this to the admin extension?

**Comment by shish** [comment]
That seems a good place to put it :)

**Comment by sanmadjack** [comment]
@shish this got added with that last pull request you merged from me in 064b24f
