### ISSUE TITLE
Should we include a copy of the license in the repository?

### ISSUE THREAD

**Issue by jgen** [shish/shimmie2#593]
From the GitHub page on licensing here:
https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository
(bold emphasis mine)
> As long as your intention is clear, you can place your license information wherever you like. Some projects only include a descriptive line in the project's README (e.g., "This project is licensed under the terms of the MIT license."). **However, to avoid any potential ambiguity, it's best to include the license file with your project as well.**

Perhaps we should include a copy of the GNU GPLv2 in the root of the repository to avoid any such ambiguity?

**Comment by greysondn** [comment]
Uh, yes. That's a general tendency. The usual tendency is just to stuff a LICENSE file in the project root. Most devs know to look there for it.

**Comment by shish** [comment]
That does seem pretty sensible :)

**Comment by jgen** [comment]
Thanks Shish, closing based on commit fefc922 .
