### ISSUE TITLE
Implement site-wide TLS

### ISSUE THREAD

**Issue by tbennett6421** [shish/shimmie2#594]
I want to make my whole instance require HTTPS certificates and no guest login. Basically invite-only. I know how to setup my apache instance to require the certificates, but what changes do I need to make to the shimmie app to force redirect to my login page/registration page if the user is unauthenticated.

In other projects i've done, the majority of the time we edited a file that was included on all pages loads, and added code to check for auth presence and redirect if not authenticated. Is there a file such as this that is loaded on each hit. Or can I make a change in the shimmie config to do this out-of-the-box.

Thanks!

**Comment by shish** [comment]
I don't think there's anything out of the box to force being logged in - off the top of my head I'd do that by going to `ext/user/main.php::onPageRequest()` and adding something along the lines of

```
if($user->is_anonymous() && !$event->page_matches("user_admin/login")) {
    $page->set_mode("redirect");
    $page->set_redirect(make_link("user_admin/login"));
}
```

**Comment by tbennett6421** [comment]
That worked pretty well out of the box actually. I modified portions of the theme.php, but the code you posted was very helpful.

Thanks
