### ISSUE TITLE
Questions regarding User List

### ISSUE THREAD

**Issue by cyb-er** [shish/shimmie2#596]
Shimmie's User List shows only 49 users. Is there any way to display the rest of the list e.g. with some query in the url? I’ve tried user_admin/list/2/ , user_admin/list?page=2 etc. without any success.

And the another thing, is there any way to access a user profile page by the id number instead of /user/name/ ?

I would be grateful for any help/suggestions with this.

**Comment by shish** [comment]
The user list got pagination support a while ago, I forgot to close the bug reports though
