### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by jgen** [shish/shimmie2#599]
We should probably push out an official release...
Its been ~2 years since the last one, and there has been lots of change in the meantime. (Composer, new theme from @dali99, many bug fixes, etc).

Though this means packaging up the composer dependencies into a zip for consumption.
I took a brief look into it, but I'm not sure how best to go about it. (It would be great if someone can document on the wiki how if/when the make an attempt.)

**Comment by DakuTree** [comment]
Release with composer should just be a simple ```composer install --no-dev```.  
Maybe also clear up the files that aren't needed for production (.git, eclipse, composer, scrutinizer & travis files for example).

Should probably try and grab the stray commits that also managed to get committed to master by mistake, and pull them over to master. Few odd bug fixes in there.

**Comment by jgen** [comment]
Thanks Daku (and thanks for your work on moving over to composer!).
Those are some good ideas for packaging up a release. I didn't realize it would be that simple -- various other docs mention performance tweaks you should make to composer in production.
(Though in retrospect I don't think we are using any of the auto-loading features of composer, so perhaps that isn't relevant).

Good point about stray commits on master. Are you saying we should merge them into the develop branch? (merge from master to master seems odd?)

Thanks again!

**Comment by DakuTree** [comment]
> (Though in retrospect I don't think we are using any of the auto-loading features of composer, so perhaps that isn't relevant).

We are using the composer autoloader at the moment as it's a bit easier to work with: https://github.com/shish/shimmie2/blob/develop/core/_bootstrap.inc.php#L12  
Extension specific libs are still loaded manually though, as to avoid loading them when the extension is disabled.

> ... various other docs mention performance tweaks you should make to composer in production.

Didn't know there was any performance tweaks for composer in production..  
Having a quick look, it seems like ```--optimize-autoloader``` would help us here. [This](http://mouf-php.com/optimizing-composer-autoloader-performance) post reports a 37%~ speed increase.

> Good point about stray commits on master. Are you saying we should merge them into the develop branch? (merge from master to master seems odd?)

Yeah, meant to say pull them over to develop.

**Comment by jgen** [comment]
Given the amount of time between releases, all of the various changes/tweaks, bug fixes, using composer, using phpunit now, etc. etc. -- I'm wondering if perhaps we might consider bumping the version number up from 2.5.5+ to something like 2.6.0 before releasing?

**Comment by jgen** [comment]
I created a simple wiki page that attempts to explain how to create a .zip/.tar.gz file that can be uploaded as a 'release': https://github.com/shish/shimmie2/wiki/Releasing
(Please feel free to edit/update/correct, etc.)

**Comment by jgen** [comment]
Uploaded .zip/.tar.gz files for the v2.6.0 release: https://github.com/shish/shimmie2/releases/tag/v2.6.0

(It is marked as "pre-release" for now. It works for me, but it would be nice if someone else could test it before fully 'releasing').

**Comment by DakuTree** [comment]
@jgen Works fine for me too.

**Comment by jgen** [comment]
Thanks @DakuTree :+1: 
I've marked it as a real 'release'.
