### ISSUE TITLE
Time since joined/uploaded often starts at 12 hours ago.

### ISSUE THREAD

**Issue by needed-a-name** [shish/shimmie2#620]
I'm running the 2.6.0 release.
When creating a new account or uploading an image most of the time the booru immediately lists it as about 12 hours ago. I have rarely seen it work properly listing the time as a few seconds ago but can't remember the circumstances.

**Comment by shish** [comment]
This tends to happen when the database timezone and PHP timezone aren't matched up - you can override the PHP timezone by adding a line to data/config/shimmie.conf.php like:

define("TIMEZONE", 'UTC');
