### ISSUE TITLE
Users Can't Favorite Random Images

### ISSUE THREAD

**Issue by greysondn** [shish/shimmie2#621]
If a user selects a random image, I believe in the Danbooru theme, they don't have an option to favorite it from the favorite images extension.

My server runs on my LAN. I don't have it accessible but I will check back in within a few days with the exact details if needbe.

**Comment by GP32** [comment]
modify ext/random_image/main.php to make a redirection to original image link. favorite block isn't appear in ".../random_image/view" page, but only in ".../post/view/[image ID]" page.
