### ISSUE TITLE
Cannot remove images entirely through the Web UI

### ISSUE THREAD

**Issue by noirscape** [shish/shimmie2#622]
It is currently not possible to completely remove an image through the Web UI. The best I could do was use the `Delete` button on the image view page to remove it from the disk, but the entries for the image id still continue to exist in the database, meaning that (in particular on search results) you see an empty thumb and image. The only way I have found to remove an image entirely from the database (and subsequently the search results and the like) is by removing the corresponding `id` line in the `images` table using PHPmyAdmin after `Delete`ing the image on the disk through the Web UI.

**Comment by shish** [comment]
I can't reproduce this; if it's still an issue - what database / OS / web server are you using?
