### ISSUE TITLE
Help with grabber/shimmie/localhost

### ISSUE THREAD

**Issue by fobear697** [shish/shimmie2#623]
I need a full walkthrough on getting localhost/grabber/shimmie to work together. I would like to go on grabber save a pic and have localhost/shimmie automatically update with the new file. thank you. 

BTW is there a way to mass upload a directory to shimmie? J/C.... if so can I be directed to the help.
 Thx in Advance.

**Comment by shish** [comment]
I have no idea what grabber is, so I can't really help with that

There is an extension for bulk uploading from a directory on the server, and one for uploading zip files from the browser

**Comment by fobear697** [comment]
grabber is a image downloader from Booru's using gelbooru/danbooru/shimmie. created by Bionus on here (GitHub). anyways the coding on the wiki isn't fully explainable:
[https://github.com/Bionus/imgbrd-grabber/wiki/Shimmie](url)
I added the command lines but nothing happens........
if you can please explain or help with the extension I do not see a link on the localhost/board to use it

**Comment by shish** [comment]
I think you want help from their end - I don't know what that software is trying to do, so I can't help fix it
