### ISSUE TITLE
Show blocks only to specific user classes

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#624]
Hello is their anyway to limit the blocks extension for showing for different user classes, say like I want to show the anon user class the blocks and not show any for the admin user class is their any command I can use in the userclass.class.php to set this up or the ext blocks?

**Comment by shish** [comment]
There's currently no way of doing that, and I can't think of a nice way to make that work :(

Leaving open as a feature request in case somebody can think of a good way to do it

**Comment by PronMaster** [comment]
I hope this allowed but I'm willing to pay someone to develop a solution for this. This could be how pixiv do it and allow the site to have a premium service for supporters of the site which could help the site grow and reduce needed advertisement anyone interested?

**Comment by MetallicAchu** [comment]
Cloud you please elaborate on what you mean by blocks? The news / ads stuff?
