### ISSUE TITLE
Question About Some Stuff of the Script

### ISSUE THREAD

**Issue by wid0wmaker** [shish/shimmie2#629]
So just to explain first some stuff about what I was doing. So I can't test the script anywhere else or I wish I could If I knew, but most of free web hosts won't help me install the imagemagick and ffmpeg extensions, and the reason why I want them is simpy because they are definitely needed to look better. I definitely don't want to pay any hosting before actually testing full features. And So, guys I tried with xampp, ImageMagick is working perfectly, but the thing that bothers me is ffmpeg, which I also installed and is located in C:/ffmpeg, but Idk if I have done the right path in the shimmie (board config section) where I've set the path like "C:\ffmpeg\bin". I think I have to do it manually, but the imagemagick typed the "convert" thing automatically, so everything okay with that, but the problem with this ffmpeg is as I already said Idk if I did the right path or what I even have to do, also the problem is that the thumbnail doesnt' work it just creates an 1x1 icon, but with built-in gd it just shows the "Video File" default image, so can anyone help me about this? I would be glad. Also by using the "warm" theme, it's saying "Navigation links go here", how do I even add the navigation, I'm just totally confused by testing the script I hope someone can help, Thanks in advance

**Comment by Apowerse** [comment]
Bump.  I also have problem with setting the path to ffmpeg... In linux it works without problems but in Windows it does not.  What should we type in this box on a win server (XAMPP)?

I can run ffmpeg commands in console so my enviroment variables are okay.

**Comment by shish** [comment]
The whole video-management framework has been changed around, so the 1x1 thumbnails shouldn't be an issue any more, but feel free to re-open if it is ^^

(Also yes, the path to ffmpeg should be the full path with the .exe on the end; sorry for not responding sooner, I don't have a windows box to test with properly >_<)
