### ISSUE TITLE
Tag Categories extension. Search.

### ISSUE THREAD

**Issue by Nielsthomas1** [shish/shimmie2#630]
While the Tag Categories extension is enabled, searchterms are changed to work as (for example) "character:'charactername'" or "artist:'artistname'", rather than "'charactername'" or "'artistname'". Which means simply entering a character-name in the searchbar will yield no results.

![ss 2018-02-02 at 11 42 57](https://user-images.githubusercontent.com/16469212/35729326-8af11cda-080e-11e8-9bdf-667189d62c6c.png)
![ss 2018-02-02 at 11 43 14](https://user-images.githubusercontent.com/16469212/35729325-8ad63f28-080e-11e8-856f-0a9c6f99f06e.png)

**Comment by arthurmv** [comment]
Could use alias for most used categories names. One of mine is `peach` for `char:ピーチ姫`. Although some trick for many tags would appreciate it.

> While the Tag Categories extension is enabled, searchterms are changed to work as (for example) "character:'charactername'" or "artist:'artistname'", rather than "'charactername'" or "'artistname'". Which means simply entering a character-name in the searchbar will yield no results.
