### ISSUE TITLE
nicescript assumes end user protocol matches server protocol

### ISSUE THREAD

**Issue by kfoxdotnet** [shish/shimmie2#632]
Hello,

$nicescript in the board config (etc/setup/main.php) takes a full url as the testing endpoint by concatenating server-side variables. This makes the assumption that the protocol being used by the end user matches the request to the host server. While it is not intuitive to consider, some sites reside behind a reverse proxy (load balancer, hardware accelerated TLS proxy, CloudFlare...) which the user interacts with over https: while, in some valid scenarios, the proxy communicates with the host server over http:.

The script checks for a 200 status code and the payload 'ok' while depending on the environment (let's say CF) it may in fact get a 302 to https: with no payload. In that case the admin may try to check the test URL and - to a human using a browser - all might seem well because they are instantly redirected to the valid location from the perspective of the end user.

This makes the nice_urls checkbox permanently disabled which can break the site and if the admin overrides by editing the corresponding config variable in the database the next time they save the board config it may revert this setting on account of the disabled checkbox being discounted.

Suggestions:
- Obtain test end point location by client-side means.
- Do not disable the checkbox. Simply show the visual indicator. IMO this is an important enough setting to give admins total control over even when conditions may not SEEM advisable. Not every board operator may be savvy enough to realize they must neuter the script to make board config usable or always follow up every config change with an SQL override.

**Comment by shish** [comment]
Fixed with the client-side approach~

(I'm sticking with disabling the checkbox, because ticking it when niceurls genuinely don't work will break the site in a way that can't be un-broken without code changes; also niceurls can be forced on via sys_config)
