### ISSUE TITLE
handle_video relies on mime_content_type()

### ISSUE THREAD

**Issue by kfoxdotnet** [shish/shimmie2#633]
The video handling function relies on the presence of mime_content_type(). Depending on the hosting environment this function may not be available and there may be little that can be done about it. It is possible to implement a simple failover, however:

if(!function_exists('mime_content_type'))
{
        function mime_content_type($filename)
        {
                if(function_exists('finfo_file'))
                {
                        $result = new finfo();
                        if(is_resource($result) === true)
                                return $result->file($filename, FILEINFO_MIME_TYPE);
                        else
                                return false;
                }   
                else
                {   
                        if($_FILES['data0']['type'] != '')
                                return $_FILES['data0']['type'];
                        else
                                return false;
                }
        }
}

The structure of $_FILES may be unidimensional if multiple uploads are disabled; untested.

**Comment by jackr579** [comment]
if you're on windows, the handler for this is disabled by default. Enable the extension 'php_fileinfo.dll' if this is the problem.
