### ISSUE TITLE
shimmie2 database access very slow

### ISSUE THREAD

**Issue by billsargent** [shish/shimmie2#634]
The more images that are uploaded to the shimmie2 site, the slower the database access is for opening posts. It becomes so slow that I never can open a post at all. The main site loads but no posts can be opened. Mysql seems to stick on this query...

`SELECT t3.tag AS tag, t3.count AS calc_count, it3.tag_id FROM image_tags AS it1, image_tags AS it2, image_tags AS it3, tags AS t1, tags AS t3 WHERE it1.image_id='86409' AND it1.tag_id=it2.tag_id AND it2.image_id=it3.image_id AND t1.tag != 'tagme' AND t3.tag != 'tagme' AND t1.id = it1.tag_id AND t3.id = it3.tag_id GROUP BY it3.tag_id, t3.tag, t3.count ORDER BY calc_count DESC LIMIT 15`

**Comment by sanmadjack** [comment]
This is known, and I think this particular query has been re-written. Can you test with the latest code?

**Comment by shish** [comment]
Closing as this should be fixed, feel free to re-open if it's still an issue
