### ISSUE TITLE
FFMPEG Path

### ISSUE THREAD

**Issue by arthurmv** [shish/shimmie2#638]
I attempted `$ffmpeg = 'C:\\ffmpeg\\bin\\ffmpeg.exe';` and `$ffmpeg = 'C:\ffmpeg\bin\ffmpeg.exe';`, also without `ffmpeg.exe`, something like this `$ffmpeg = 'C:\ffmpeg\bin';` in PHP code and no works for me. The same with path in Board Config. I can't create video thumbnails.

I'm using ffmpeg v3.4.

How could I pin my own thumbs or fix ffmpeg path?

**Comment by shish** [comment]
If you enable a logging extension set to "debug" it should show you exactly what command is being run under the hood - can you see what command that is? Does that command work if copy-pasted into a command line?

**Comment by arthurmv** [comment]
```
[Parsed_scale_0 @ 000001d47d3eef20] Invalid size 'if(gt(a'
[AVFilterGraph @ 000001d47cd9d720] Error initializing filter 'scale' with args 'if(gt(a:flags=bicubic'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!
```

**Comment by shish** [comment]
Ah, I think you're using a build of ffmpeg that doesn't support dynamic scaling >_< In the video handler options there should be an option to disable scaling, and then you get square thumbnails, which is slightly better than no thumbnails...

Now that I think about it, it shouldn't be too hard to create a temporary screenshot file which is just the a frame from the video with no scaling applied at all, and then use the regular .jpg thumbnailing code to shrink that while keeping the aspect ratio. I'm about to head off for a weekend without internet access though, so I can't do that right now, but the idea is there if anyone feels like coding it ^^

**Comment by arthurmv** [comment]
I'd love some way to pin custom thumbs for audio and flash files. It would help to find files faster.

**Comment by PronMaster** [comment]
So any update on this shish?

**Comment by shish** [comment]
Does anything show up in the webserver's error log to go along with that 500?

**Comment by PronMaster** [comment]
Yes shish it says PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home/xxx/public_html/ext/handle_video/main.php on line 56

**Comment by PronMaster** [comment]
Weird now it says PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home/xxx/public_html/ext/handle_video/main.php on line 50

**Comment by PronMaster** [comment]
Well my web developer fixed the small syntax errors on you code shish and thumbnails are working thanks.

**Comment by shish** [comment]
I'm curious what the error that needed fixing was, as I'm not getting a syntax error from the same file :S

**Comment by shish** [comment]
I'm assuming that this was some kind of merge conflict, as the current code seems to have no syntax errors...
