### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by arthurmv** [shish/shimmie2#639]
```
Internal Error

Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1819-144' for key 'image_id'

Query: INSERT INTO image_tags(image_id, tag_id) VALUES(:iid, :tid)

Version: 2.6.2 (on 5.6.36)
```

I get this error every time when set same tag in mass edit, but if I edit one by one goes well. I got this error often, I think for been using tag implications in alias, is usefull.

**Comment by shish** [comment]
I think this got fixed a while ago as part of the big tag-editing rewrite, feel free to re-open if it's still an issue
