### ISSUE TITLE
paginated tag list missing main URL

### ISSUE THREAD

**Issue by billsargent** [shish/shimmie2#640]
When turning on paginated tag lists, and having nice urls on, the generated html leaves out the host url and just tries to navigate the user to something like

` hxxp://tags/?starts_with=a`

I'm running this on lighttpd with the following rewrite rules:

```
url.rewrite-repeat = (
        "^/_images/([0-9a-f]{2})([0-9a-f]{30}).*" => "images/$1/$1$2",
        "^/_thumbs/([0-9a-f]{2})([0-9a-f]{30}).*" => "thumbs/$1/$1$2"
)

url.rewrite-if-not-file = (
        "^([^\?]+)(\?(.*))?" => "/index.php?q=$1&$3"
)

```

When I disable nice urls, it works fine.

**Comment by shish** [comment]
This should be fixed by b60e8ac5
