### ISSUE TITLE
Please help PHP Warning:  PDO::rollBack()

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#642]
getting this error PHP Warning:  PDO::rollBack(): Error reading result set's header in /home/xxx/public_html/core/database.class.php on line 654

I can't do much of anything on my site this includes upload comment nothing it throws 500 error any help would be appreciated.

**Comment by shish** [comment]
What version are you running? Line 654 for me doesn't seem to mention rollBack() at all :S

Either way, this sounds like a database issue, as if the database is returning corrupt data o_O What database are you using? Can you connect to it with the command line tools and make queries to it?

**Comment by PronMaster** [comment]
Shish I fixed it it turns out I ran out of memory for my server I used this line to clear it up 
sync && echo 3 | sudo tee /proc/sys/vm/drop_caches

so if anyone runs into this issue you need to clear up your memory or get more memory thanks shish.

**Comment by shish** [comment]
Well that’s weird - the server should really be doing that kind of memory
cleaning automatically whenever necessary; if you need to do it manually,
that suggests that something else has gone weird and it’d eventually happen
again if the root cause isn’t fixed :S

**Comment by PronMaster** [comment]
Yeah this did not fix the issue damn...

**Comment by PronMaster** [comment]
Oh and I can make changes to it do you have any suggestions?

**Comment by shish** [comment]
That's more of a general linux server issue than a shimmie thing; The only thing I can think of would be to start at the start (run `top`, see what's using a ton of memory, go debug that thing)

**Comment by PronMaster** [comment]
I typed top this is what I got shish 
![109](https://user-images.githubusercontent.com/7246977/44057985-b123e434-9f1a-11e8-819d-9bbd0c2f3ace.PNG)

**Comment by PronMaster** [comment]
Okay top top and got this 
![7806](https://user-images.githubusercontent.com/7246977/44058182-59dee90c-9f1b-11e8-87c1-27bab022b61f.PNG)

**Comment by PronMaster** [comment]
I don't think it's a memory issue but I got some new error logs idk if this tells anything

Stack trace:
#0 /home/xxx/public_html/core/database.class.php(727): Database->connect_db()
#1 /home/rule34he/public_html/core/database.class.php(760): Database->execute('SELECT name, va...', Array)
#2 /home/xxx/public_html/core/config.class.php(386): Database->get_all('SELECT name, va...')
#3 /home/xxx/public_html/core/_bootstrap.inc.php(37): DatabaseConfig->__construct(Object(Database))
#4 /home/xxx/public_html/index.php(89): require_once('/home/rule34he/...')
#5 {main}
  thrown in /home/xxx/public_html/core/database.class.php on line 594

**Comment by PronMaster** [comment]
I don't think it's a memory issue but I got some new error logs idk if this tells anything

Stack trace:
#0 /home/xxx/public_html/core/database.class.php(727): Database->connect_db()
#1 /home/xxx/public_html/core/database.class.php(760): Database->execute('SELECT name, va...', Array)
#2 /home/xxx/public_html/core/config.class.php(386): Database->get_all('SELECT name, va...')
#3 /home/xxx/public_html/core/_bootstrap.inc.php(37): DatabaseConfig->__construct(Object(Database))
#4 /home/xxx/public_html/index.php(89): require_once('/home/rule34he/...')
#5 {main}
thrown in /home/xxx/public_html/core/database.class.php on line 594

**Comment by PronMaster** [comment]
I don't think it's a memory issue but I got some new error logs idk if this tells anything

Stack trace:
#0 /home/xxx/public_html/core/database.class.php(727): Database->connect_db()
#1 /home/xxx/public_html/core/database.class.php(760): Database->execute('SELECT name, va...', Array)
#2 /home/xxx/public_html/core/config.class.php(386): Database->get_all('SELECT name, va...')
#3 /home/xxx/public_html/core/_bootstrap.inc.php(37): DatabaseConfig->__construct(Object(Database))
#4 /home/xxx/public_html/index.php(89): require_once('/home/xxx/...')
#5 {main}
thrown in /home/xxx/public_html/core/database.class.php on line 594

**Comment by shish** [comment]
"PDO not found" would suggest that PHP itself didn't manage to load properly, before it even reached Shimmie code :S (Assuming that PHP's PDO plugin is installed, which it should be if shimmie has ever worked in the past, and assuming that you didn't uninstall it recently)

With seemingly random failures like that I would be starting to suspect that the RAM or CPU are beginning to physically fail, like one particular patch of ram has fried...

**Comment by PronMaster** [comment]
Okay Shish I'm going to have my host upgrade my server and if the issue persistent this we know its not a hardware issue. I do have a question is there anyway to reinstall shimmie and keep everything intact?

**Comment by shish** [comment]
You'd need to backup the database (depends which database software you're using) and the data (images / thumbs folders, can  be backed up as regular files)

**Comment by PronMaster** [comment]
You hit it right on the head shish I just got done upgrading my server and the issue is gone so I'm assuming it was a memory issue so if anyone else gets this issue its more then likely for memory thanks shish.
