### ISSUE TITLE
How to change video player?

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#644]
Anyone know how to change the video player to fluid player or jw player?

**Comment by shish** [comment]
Sorry for the delay >.> If you want a custom player, you'd want to add that player's code into the VideoFileHandler theme - either editing it directly, or coming up with a custom theme. The exact code to use depends on the player you're using, but you could start by copying ext/handle_video/theme.php and using the variables there.

For creating a custom theme (to avoid getting any conflicts when the original theme changes) you can create `themes/{your_theme}/handle_video.theme.php`

```
<?php
class CustomVideoFileHandlerTheme extends VideoFileHandlerTheme {
    public function display_image(Page $page, Image $image) {
        [... code to render the player ...]
    }
}
```
