### ISSUE TITLE
No video with supported format and MIME type found

### ISSUE THREAD

**Issue by arthurmv** [shish/shimmie2#646]
This is weird because all videos run well in WAMP, but I moved to Linux VPS one month ago and some few MP4 videos doesn't play.

I must install something? FFMPEG installed and just upgraded all APT packages, all other features else seems works correctly...

**Comment by shish** [comment]
AFAIK this is a client-side issue; the video served to the user is the same either way (it's the file which was uploaded, unmodified). Whether the client can play it or not depends on which codecs are installed :S

**Comment by arthurmv** [comment]
Oh Firefox, Chrome and Opera doesn't play them in booru, but if I drag that viedos play them fine, this same machine runs very well everything with WAMP, I thought something related VPS.
So what could I do?

**Comment by shish** [comment]
What do you mean by "drag them"?

Maaaybe it's a webserver setup thing, with different headers... is the site public at all so I can take a look?

**Comment by arthurmv** [comment]
Drag and drop for play any video from browser.
Is private but I could give you access by PM.

**Comment by arthurmv** [comment]
Finaly I fixed it. Was a dumb thing, just increase `memory_limit = 128M` to `memory_limit = 512M` in PHP.ini.
Thanks!
