### ISSUE TITLE
Check-box deletion

### ISSUE THREAD

**Issue by shish** [shish/shimmie2#647]
Deleting specific images in a large group one-by-one is a pain.

It'd be nice to have checkboxes on the main post list, to tick particular images and then delete all the ticked ones.

**Comment by sanmadjack** [comment]
This is very pertinent to me, I'd be willing to work on this.

**Comment by shish** [comment]
FWIW I was thinking that it should be possible to do this in a way that works for multiple extensions out of the box - like right now you can enter a search query, and then perform an action on all search results ("delete all", "ban all", "regenerate all thumbnails", etc).

An ugly way of doing it would be to have a bunch of tickboxes, and then click a button to turn those tickboxes into a search query of "id=123,543,1323,654,33,667,341", then search for that, and then use the existing "perform action for each search result" code -- but that is a lot of steps.

Perhaps if the "perform action for each search result" form had a hidden field for "query to use", which would default to current-query, but if the user ticks some boxes, then we replace the value of that hidden field with "id=<list of ticked IDs>"?

**Comment by sanmadjack** [comment]
The advanced tagger has an item selection system similar to what's being described, can that be abstracted out somehow?

**Comment by sanmadjack** [comment]
I've done it, pull request forthcoming.

**Comment by sanmadjack** [comment]
These are in #659

**Comment by sanmadjack** [comment]
Well, @shish, was my implementation good enough to close the ticket?

**Comment by shish** [comment]
Yup, it seems to work wonderfully ^__^ Now I'm looking through for any other things that could be built on top of the bulk actions framework :)
