### ISSUE TITLE
[SUGGESTION] convert all @$_GET to array_key_exists

### ISSUE THREAD

**Issue by ryonagana** [shish/shimmie2#648]
i saw in the source code and some parts of Core
there some nasty @$_GET['foo']

what you guys think if change to array_key_exists('foo', $_GET)
it just return true or false (if not exists)
i think  supressing a possible error  is a bad thing
if you guy approves.. i can do it by myself and create a new pull request..

**Comment by shish** [comment]
What errors would be suppressed, other than "array key doesn't exist"?

Either way, I don't see any harm in switching to `array_key_exists` :)

**Comment by ryonagana** [comment]
not an error but supress warnings (if occur one)
using array_key_exists just returns true or false, no warning is triggered

**Comment by shish** [comment]
Closing as this seems inactive; though if there were a pull request to make the switch then I wouldn't have any objections to merging it
