### ISSUE TITLE
Image ratings not working

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#649]
**Describe the bug**
Image ratings and numerical rating don't appear.

**To Reproduce**
1. Install fresh Shimmie 2.6.2
2. Enable image ratings extension
3. Upload an image and view it
4. No rating editor

**Expected behavior**
To see the rating editor

**Server Software, if you're the server admin (please complete the following information):**
 - Shimmie version 2.6.2
 - Database postgres
 - Web server nginx

**Client Software (please complete the following information):**
 - Device windows desktop
 - Browser chrome

**Comment by shish** [comment]
Are other extensions working, or are all of them failing to load? :S

**Comment by sanmadjack** [comment]
Board admin and bulk import are working, I can try others if needed.

**Comment by sanmadjack** [comment]
I was initially using a checkout of the master branch, I did a new clean install using the release zip of the same version and the issue persists.

**Comment by sanmadjack** [comment]
In terms of extensions that affect the image page, links, QR code, and regen thumbnail extensions all are working ok.

**Comment by sanmadjack** [comment]
Figured it out, the extension isn't marked for posgtresql compatibility. I'm going over the database code in it now and I'll make a pull request to get it compatible.
