### ISSUE TITLE
cron uploader ignore dot files

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#650]
On linux the cron importer sees dot files as real files, which causes it to see 2 extra files for each folder. This can be fixed with this change:

		$ite=new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS);

This affects both the develop and master branches. If you need me to create a pull request, please let me know.

**Comment by sanmadjack** [comment]
Additionally, this change to process_upload prevents it from throwing warnings when the max imported is greater than the amount available:

		// Upload the file(s)
		for ($i = 0; $i < $upload_count && $i < sizeof($this->image_queue); $i++) {

**Comment by shish** [comment]
Both look good, fixed in develop, and the difficulty of keeping master and develop in sync is making me think it's probably time for a new release :P
