### ISSUE TITLE
cron uploader can't handle paths with regex special characters

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#652]
glob() treats the path passed to it as a regex, so if the folder path in your cron upload has special regex characters (like the brackets mine did), it won't be able to see what's in them. Changing the foreach line to this takes care of escaping the special characters:

		foreach ( glob (preg_quote("$base/$subdir/")."*" ) as $fullpath ) {

**Comment by shish** [comment]
Gah, glob isn't _quite_ regex, but there's no `glob_quote` function which would do exactly the right thing... But we could fix that _and_ be more consistent by using the same `RecursiveDirectoryIterator` for both `scan_dir()` and `generate_image_queue()`

**Comment by sanmadjack** [comment]
that's more sensible, really.
