### ISSUE TITLE
Independent thumbnail display and file size

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#657]
With the advent of high-dpi displays, pixel densities are on the rise. I'm typing this from a laptop with a 12.3" 2400x1600 screen, and my desktop is a 4k screen. A thumbnail size of about 256x256 takes up an appropriate amount of space on these screens (imo), but because of the higher dpi settings the actual pixels on screen can be much more, resulting in stretched thumbnails that look blurry. Increasing the size of the thumbnails causes them to take a greater amount of screen space than is useful, and they're still stretched anyway since the browser cranks up the size.

Adding a second set of thumbnail width and height settings to be used as the max in-page thumbnail size would add the ability to set an in-page size but allow generating higher-resolution thumbnails that look good at higher dpis. I've added such settings to my shimmie instance and I think they look great, lots of detail even though the thumbnails are still only about an inch. If this would be a desirable change I can prepare a pull request.

**Comment by shish** [comment]
> a second set of thumbnail width and height settings

I wonder if that's needed, or just a "high-dpi thumbnails" checkbox, which makes file size be 2x display size? (ie, is there a use-case for any value other than 2x?)

Either way, supporting high-dpi screens would be nice :)

**Comment by sanmadjack** [comment]
Windows uses a standard of 96 dpi, scaling by percent up and down from there. On my laptop I'm using 200% scaling, so that would be 192 dpi (though the specs for the screen physically are 235 dpi, so things are still a bit smaller than normal). My desktop is at 150% since it's a 40-inch 4k screen, that's 144 dpi. 2x would cover this entire range, and would work for all of my use cases.

While simpler, it wouldn't give people any flexibility in regards to whether they want the thumbnails to be 4 times the size (2x2) or if they want to compromise somewhere in between, or just target 150% instead. It also limits forward-compatibility if the DPIs of displays keep increasing. Perhaps a percent input would suffice?

**Comment by shish** [comment]
Blerg, looking up the current state of high-dpi stuff, seems it isn't as consistent as I'd like :( So yeah, having it be variable rather than checkbox seems sensible

**Comment by sanmadjack** [comment]
Okay, I'll rig it up and get a pull request for it after I get in the selection stuff checked in.

**Comment by sanmadjack** [comment]
These are in #659
