### ISSUE TITLE
Webp support

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#658]
I'd like to add webp support. Should I add it as part of handle_pixel, or create a separate extension?

I'd also like to add webp as an option for thumbnail generation. It's supported by everything except IE and safari. The quality/compression analysis I saw showed it having a good 20% better compression for the same visual quality, which would amount to a significant savings for larger collections.

**Comment by shish** [comment]
For viewing, yeah I'd put it in handle_pixel, it's fundamentally similar to jpg/png/etc

For thumbnails, I'd also find 20% bandwidth savings useful - but if we still want to support IE, wouldn't that mean keeping both webp+jpg thumbnails, which ends up being +80% disk / ram costs?

**Comment by sanmadjack** [comment]
I think storing both versions would be unnecessary, I'd view webp thumbnail usage as deliberately deciding to not support IE/Safari. That's why it would definitely need to be implemented as an option, clearly labelled as not supported by IE/Safari (at present at leas). The optimal long-term result would be that it would eventually be supported everywhere and then it could become a recommended option.

**Comment by sanmadjack** [comment]
These are in #659
