### ISSUE TITLE
Negative tags not working on their own.

### ISSUE THREAD

**Issue by DakuTree** [shish/shimmie2#66]
As title says, negative tags only seem to work while using them with other tags (I.E: wallpaper -dualscreen).
So instead of: Search database for wallpaper > remove anything containing dualscreen.
You get: Get Database > remove anything containing dualscreen.

**Comment by sanmadjack** [comment]
YO, I'm back five years later, and some query changes I wrote just got merged in that may resolve this. What say you @shish ?

**Comment by shish** [comment]
Looks like this is actually still not working right o_O

**Comment by Frogging101** [comment]
@shish Could look at my patch linked above. It's from 3 years ago, might not apply cleanly, but I recall that it did fix this for me.

**Comment by shish** [comment]
This should have been working for a while now; and I recently added a ton of test-cases while working on a related issue - https://github.com/shish/shimmie2/blob/main/core/tests/SearchTest.php
