### ISSUE TITLE
Flash file thumbnailing

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#660]
ffmpeg can generate thumbnails for flash files. I'd like to create a common create_thumbnail_ffmpeg function somewhere (maybe core/imageboard/misc.php?) that both handle_video and handle_flash can call, since the arguments are no different. 

Additionally ffmpeg has a "thumbnail" filter that tries to automatically pick a frame that is "representative" of the video (whatever that means), I think it would be better to use that than always using frame 0 like shimmie currently does.

**Comment by shish** [comment]
Both of those sound like sensible ideas :3

**Comment by sanmadjack** [comment]
These are in #659
