### ISSUE TITLE
Constant usage

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#662]
@shish, Many places in shimmie use strings as identifier for things like current database driver, setting names, pre-defined folder names, etc. I think that it would be beneficial to start changing shimmie to use constants wherever possible for strings that need to be the same in many places. This would provide a somewhat small performance assist, since reducing the number of string variables isn't that much in the grand scale of things, but more importantly it would reduce the likelihood of typos causing issue, as well as make it possible for PHP inspectors to catch when an invalid string is specified. It would also mean that if a value needed changed globally, it need only be done in one place, and all usages can be precisely detected by any IDE. 

I'll admit, this is my normal style when programming, but I'm trying to keep with what I'm seeing as the established code style in this project. I don't want just my code to be in a different style, and I don't want to force my style on the project without someone's ok. Obviously it wouldn't be done all at once, but since I'm basically going around looking for bugs everywhere at this point I should be able to hit just about everything in the end. If you'd rather just let sleeping dogs lie, that's fine too, just let me know what you'd like to see happen.

**Comment by shish** [comment]
The strings mostly came from organic growth and a bunch of legacy stuff, I'm happy for them to be replaced with constants where appropriate :)
