### ISSUE TITLE
Check which old hacks are no longer needed

### ISSUE THREAD

**Issue by shish** [shish/shimmie2#677]
Debian Stable is the most out-of-date OS I care about - now that debian 9 is "old" and 10 is "stable", are there any old hacks that are no longer needed?

For reference, debian 10 includes:

php 7.3
mariadb 10.3
postgres 11
sqlite 3.27

**Comment by shish** [comment]
A bunch of stuff got tidied up in the past few months; old functions refactored out of existence; a lot of scoreql replaced with vanilla sql, etc

**Comment by sanmadjack** [comment]
Is that a goal, to remove scoreql?

**Comment by shish** [comment]
It's not a huge priority, but if in 2010 we needed to write 3 different queries for 3 databases, and today they've all finally agreed on the same syntax, then it seems sensible to use that syntax instead of maintaining our own compatibility layer~
