### ISSUE TITLE
Upload an image from an URL

### ISSUE THREAD

**Issue by Lifebearer** [shish/shimmie2#685]
Is there a way to upload an Image from an URL?

**Comment by sanmadjack** [comment]
If it's enabled int he system setting, yes. Once enabled you can paste in a url on the uploads page.

**Comment by Lifebearer** [comment]
Can you tell me which setting it is exactly? I seriously can't find it. Sorry for the trouble.

**Comment by sanmadjack** [comment]
It's called "Transload", and you have to set it to something other than "Disabled".

**Comment by sanmadjack** [comment]
Nice. @shish this can be closed.
