### ISSUE TITLE
Tag categories screen

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#689]
I want to clean up and enhance the tag categories stuff, but tag_list currently provides a tag/categories screen that doesn't make much sense. It shows a list of the top tags by count, and a random thumbnail from each. Before I rip it and apart and make it into something that actually has something to do with categories as I understand them, I'd like to know what the function of this screen is supposed to be right now, in case I'm missing something, and why it's in tag_list rather than tag_categories.

**Comment by shish** [comment]
I think that dates from the very olden times when people wanted to drop shimmie in place of an oldschool folder-based gallery, using a small number of tags as "folders", one tag per image... it wasn't a very good fit, and I'm not aware of anyone using that screen in the past decade, so feel free to do whatever you like with it :)

**Comment by sanmadjack** [comment]
That sounds ridiculous.
