### ISSUE TITLE
Incorrect logic blocks account creation

### ISSUE THREAD

**Issue by trashcand69** [shish/shimmie2#691]
Was trying to set up latest version and ran into issues when I went to sign up page.
There is incorrect logic in [ext/user/main.php:443](https://github.com/shish/shimmie2/blob/f6022e80fbb6fe531a8f1cf6e24419508b5a8faa/ext/user/main.php#L443) blocks account creation.
`        if ($user->can(Permissions::CREATE_USER)) {`

It should be negated:
`        if (!$user->can(Permissions::CREATE_USER)) {`

**Comment by shish** [comment]
Gah, thanks for spotting that, fixed :)
