### ISSUE TITLE
Consistent line endings

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#694]
Checking out the git repo results in my files having CRLF endings (obviously on Windows). Running the PHP formatter we discussed changes everything to LF endings, resulting in hundreds of changed files in git. I know I can tweak things in my git environment to compensate (and likely will), we can add this to .gitattributes in order to make php files default to checking out in LF. 

*.php text eol=lf

This will of course mean anything left in the repo that's still CRLF will then have large EOL-changing check-ins, which can make merging difficult. What do you think about this?

**Comment by shish** [comment]
Poking around a bit, it seems that doing that is the least-bad option... hopefully it'll only need migrating once, and save us from merge issues in the long term /o/
