### ISSUE TITLE
Save images on mountpoint

### ISSUE THREAD

**Issue by Sonixier** [shish/shimmie2#702]
By default shimmie saves images in the "images" folder. In my case i've wanted to put uploaded images into "/mnt". Is it possible to save images in some other folder than the default one?

**Comment by shish** [comment]
There's no built-in support for it - every time I've needed to do that, I've used a symlink (ie move the existing `images` folder to `/mnt/images`, then create a link in the old location which points to the new location). That way you're using the external disk for the actual storage, but all the software which expects it to be in the default location (eg any webserver config files) will find it there :)

**Comment by shish** [comment]
Closing as the symlink approach works for all the sites I've seen so far - feel free to reopen if you really need support built-in for some reason
