### ISSUE TITLE
how do I fix this?  Please guide

### ISSUE THREAD

**Issue by leo859** [shish/shimmie2#708]
Install Error
Warning: Composer vendor folder does not exist!
Shimmie is unable to find the composer vendor directory.
To finish installing, you need to run composer install in the shimmie directory.

**Comment by shish** [comment]
You need to install Composer (https://getcomposer.org/), then run `composer install` in the directory where shimmie is installed

(or use one of the .zip files from the release page, which includes the composer stuff - but if you're able to use git and composer, that tends to make future upgrades easier than using the .zip files)
