### ISSUE TITLE
Error 404 if i try to login or register

### ISSUE THREAD

**Issue by csBlackWolf** [shish/shimmie2#709]
Hi.

After creating the first account, i can't login or register a new account anymore, because i get a 404 error.

I have installed Shimmie 2.8.1 on a webserver with PHP Version 7.4.3. using mariadb 10.1.26 and the webserver is running nginx. (The proxymode to apache is deactivated at the moment.)

I access the Website with firefox 74.0 (64 bit) over my desktop pc with windows 10.

If i click on "Log In" i get to the url: "https://mywebsite.com/user_admin/login" with a 404 error

If i click "Create Account" after filling out the register form, i get to the url: "https://mywebsite.com/user_admin/create" with a 404 error.

I think i got stuck with the url's to create a admin account, while i already have created an admin... or something like this.

**Comment by shish** [comment]
`user_admin/create` / `user_admin/login` are the correct URLs

Are you getting a generic webserver 404 or the shimmie-themed 404?

**Comment by csBlackWolf** [comment]
The 404 error comes from the web server. It doesn't look like a 404 from Shimmie.

**Comment by shish** [comment]
Then I would guess that something is missing at the webserver config level - you've mentioned both nginx and apache, how exactly is the site set up?

Either way, it looks like somehow Nice URLs (ie, `/user_admin/login` as opposed to `index.php?q=user_admin/login`) have been enabled - even though the check for them should have failed... So ideally we'd configure the web server to make nice URLs work, or disable them

**Comment by csBlackWolf** [comment]
Ok. Just got it to work. I just enabled the "proxymode" so it is running with apache.

My hosting provider said that Nginx isn't properly configured for nice URLs, but with the "proxymode" enabled it would work. And now it is running perfectly.

Sorry for the inconvenience and thanks for your help.
