### ISSUE TITLE
Popular by <x> is seemingly not working

### ISSUE THREAD

**Issue by Jaika1** [shish/shimmie2#713]
This is occurring an a relatively new shimmie install of only a few days old, but it appears that only the popular by <x> tabs are not working. All they do is go to a white screen, however all other pages are working splendidly. Changing themes didn't do anything either, currently settled on Danbooru2. This is using the current latest version of shimmie with mysql and apache.

**Comment by DanielOaks** [comment]
Hm, when using SQLite I get an SQL syntax error instead. Weird, I'll see if I can fix that for me if Shish doesn't get to it first. Maybe we should have a test that just grabs each of those pages in order and asserts a 200 code to confirm they work properly?

**Comment by Jaika1** [comment]
Sounds good, I'll be ready to give my experience when a potential fix is ready

**Comment by Jaika1** [comment]
Update, it seems like the pages for popular by day and by month are now both appearing, but cycling through past days or months doesn't turn up any results, and going under the amount of days/months tracked brings us back to the white page, which might not be the most user friendly? I'm guessing that things might not be appearing due to a threshold?

**Comment by MetallicAchu** [comment]
Same problem here.
Would be nice if there's a sort option by popular, like most viewed

**Comment by MetallicAchu** [comment]
> Update, it seems like the pages for popular by day and by month are now both appearing, but cycling through past days or months doesn't turn up any results, and going under the amount of days/months tracked brings us back to the white page, which might not be the most user friendly? I'm guessing that things might not be appearing due to a threshold?

Popular by X is relying on votes, does your pictures have any votes to them?

**Comment by SpannerWZ** [comment]
in my case popular by month and year gives up a error 500 in my release version and in my git pull version im getting this error:

Fatal error: Uncaught TypeError: Argument 1 passed to Image::by_id() must be of the type int, string given, called in C:\xampp\htdocs\shimmie\ext\numeric_score\main.php on line 155 and defined in C:\xampp\htdocs\shimmie\core\imageboard\image.php:103 Stack trace: #0 C:\xampp\htdocs\shimmie\ext\numeric_score\main.php(155): Image::by_id('1') #1 C:\xampp\htdocs\shimmie\core\send_event.php(113): NumericScore->onPageRequest(Object(PageRequestEvent)) #2 C:\xampp\htdocs\shimmie\index.php(82): send_event(Object(PageRequestEvent)) #3 {main} thrown in C:\xampp\htdocs\shimmie\core\imageboard\image.php on line 103

**Comment by shish** [comment]
b1f37f1c should fix that last issue

**Comment by SpannerWZ** [comment]
it worked, had to comment the original line though, thanks a lot!
