### ISSUE TITLE
RewriteRule for customized WH_SPLITS

### ISSUE THREAD

**Issue by gphg** [shish/shimmie2#721]
Let's be honest: for partition reason, I have to set `WH_SPLITS` onto `2` (default is `1`), and now every images and thumbs are 404. 

I'm having difficult in when it come to regex; I'm very suck at it. Would you please help me on what should I do on my project's `.htaccess`?

**Extra questions:** 
1. On further, the web server might not be Apache. Would you please explain Rewrite Rules config for other web server too.
2. On practive, `WH_SPLITS` might be set higher than 2.

**Comment by shish** [comment]
.htaccess for two splits would have:
```
RewriteRule ^_(images|thumbs)/([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{28}).*$  data/$1/$2/$3/$2$3$4 [L]
```

Some other popular web server configs are documented in the wiki

2 splits has been plenty for a site with ~5 million images; in theory I would expect it to be fine for over 100 million images - do you have issues where 2 splits isn't enough?

**Comment by gphg** [comment]
I see the pattern.

Thanks! That really helps me out.

> 100 million images - do you have issues where 2 splits isn't enough?
Theoretically.
