### ISSUE TITLE
Tag wiki - information regarding each tag

### ISSUE THREAD

**Issue by MetallicAchu** [shish/shimmie2#722]
Whenever viewing a certain tag, it would be nice if we could add a small wiki / information about what that tag is used for.
Currently we have a wikipedia link, which is nice, but it would be nice if we could have an option to describe to our visitors in what cases we expect certain tags.

**Comment by DanielOaks** [comment]
@MetallicAchu I introduced a setting in the board config called _"Show shortwiki entry when searching for a single tag"_ in a recent PR, maybe that would work for your needs? It'll show the first line of the tag's wiki entry if a page for that tag exists~ #705 for more info

**Comment by MetallicAchu** [comment]
That's exactly it! Thank you so much for pointing me out to it. Much appreciated!!
