### ISSUE TITLE
Post Title extension errors out View page if window title feature enabled

### ISSUE THREAD

**Issue by Viktini** [shish/shimmie2#725]
**Server Software**
 - Shimmie version: master (commit: 06bd458 - settings reads 2.8.3)
 - Database: MySQL 10.4.13-MariaDB
 - Web server: Apache/2.4.13, PHP/7.4.6, Arch Linux

**Client Software**
 - Device: Desktop
 - Browser: Mozilla Firefox 76.0.1

**What steps trigger this bug**
1. With Post Titles extension enabled, go to Board Config, enable "Show in window title" and save.
2. Navigate to a valid view page (e.g. click an uploaded image)

**What did you expect to happen?**
The post's title should appear in the window title as described when on its view page.

**What actually happened?**
Entering the view page raises a PHP error.

`Fatal error: Uncaught Error: Call to undefined method DisplayingImageEvent::set_title() in /srv/http/booru/ext/post_titles/main.php:39 Stack trace: #0 /srv/http/booru/core/send_event.php(113): PostTitles->onDisplayingImage() #1 /srv/http/booru/ext/view/main.php(63): send_event() #2 /srv/http/booru/core/send_event.php(113): ViewImage->onPageRequest() #3 /srv/http/booru/index.php(95): send_event() #4 {main} thrown in /srv/http/booru/ext/post_titles/main.php on line 39`

The error is not present when the window title feature is disabled.

**Comment by sanmadjack** [comment]
Pull request #726 resolves this
