### ISSUE TITLE
Animated WEBP thumbnail fatal error

### ISSUE THREAD

**Issue by arthurmv** [shish/shimmie2#727]
With GD:
`Fatal error: gd-webp cannot allocate temporary buffer in D:\WEB\htdocs\shimmie\ext\media\main.php on line 705`

After install Imagemagick and change to it I get this:
```
Error while creating thumbnail: Resizing image with command `convert   -strip -thumbnail 200x200\> -quality 100 -background black webp:"data\images\cf\cfd4917d5a574c79de75e70b97bb3e75[0]"  jpg:"data\thumbs\cf\cfd4917d5a574c79de75e70b97bb3e75" 2>&1`, returns 4, outputting
``` 

_Shimmie version 2.8.3+_

**Comment by shish** [comment]
> gd-webp cannot allocate temporary buffer

Is this a particularly large image? o_O

**Comment by sanmadjack** [comment]
@arthurmv Can you provide a copy of the image in question for testing?
