### ISSUE TITLE
Media engine defaults to null instead of GD or ImageMagick

### ISSUE THREAD

**Issue by Antonio-Rocchia** [shish/shimmie2#729]
**Server Software**
about:
  title: "Shimmie"
  theme: "default"
  url: "http://localhost/shimmie"

versions:
  shimmie: "2.8.3+"
  schema: 18
  php: "7.3.12"
  db: "mysql 10.4.10-MariaDB"
  os: "Windows NT DESKTOP-LA25JP0 10.0 build 18363 (Windows 10) AMD64"
  server: "Apache/2.4.41 (Win64) PHP/7.3.12"

extensions:
  core: ["alias_editor","bbcode","comment","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: []
  handled_extensions: ["jpg","jpeg","gif","png","webp"]

stats:
  images: 0
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "331.2GB"
  disk_total: "930.5GB"

thumbnails:
  engine: null
  quality: 75
  width: 192
  height: 192
  scaling: 100
  type: "jpg"

 - Shimmie version:
 - Database: "mysql 10.4.10-MariaDB"
 - Web server: "Apache/2.4.41 (Win64) PHP/7.3.12"

**Client Software (please complete the following information)**
 - Device: windows 10 desktop
 - Browser: chrome

**What steps trigger this bug**
On a fresh installation go to index
Select an image and click upload

**What did you expect to happen?**
Image uploaded

**What actually happened?**
![Cattura](https://user-images.githubusercontent.com/49683601/84429253-1f2e0380-ac28-11ea-9ee0-bba7a27495d5.PNG)

**Comment by shish** [comment]
> engine: null

Well that looks suspicious. If you go into board config and set thumbnailing engine to something (GD or Imagemagick) does it work after that?

(And if that works, we can start investigating why it was set to null on a fresh install...)

**Comment by Antonio-Rocchia** [comment]
> > engine: null
> 
> Well that looks suspicious. If you go into board config and set thumbnailing engine to something (GD or Imagemagick) does it work after that?
> 
> (And if that works, we can start investigating why it was set to null on a fresh install...)

Totally works after switching from GD to imagekick

**Comment by damjess** [comment]
Just writing to confirm that we are seeing the same issue. Going into Board Config and setting the engine to Imagick fixed it, though seeing a 500 on thumbnail images. 

Here are the errors:
`[Wed Jun 24 04:51:31.158462 2020] [php7:warn] [pid 9610] [client XX.XX.XXX.XX] PHP Warning:  filemtime(): stat failed for data/thumbs/5f/5f37e1635ff9df0675c8d5c81dca9de8 in /path/to/directory/shimmie2/ext/image/main.php on line 287, referer: https://mydomain.com/index.php?q=post/list
[Wed Jun 24 04:51:31.158546 2020] [php7:error] [pid 9610] [client XX.XX.XXX.XX] PHP Fatal error:  Uncaught TypeError: gmdate() expects parameter 2 to be int, bool given in /path/to/directory/shimmie2/ext/image/main.php:287\nStack trace:\n#0 /path/to/directory/shimmie2/ext/image/main.php(287): gmdate()\n#1 /path/to/directory/shimmie2/ext/image/main.php(76): ImageIO->send_file()\n#2 /path/to/directory/shimmie2/core/send_event.php(113): ImageIO->onPageRequest()\n#3 /path/to/directory/shimmie2/index.php(95): send_event()\n#4 {main}\n  thrown in /path/to/directory/shimmie2/ext/image/main.php on line 287, referer: https://mydomain.com/index.php?q=post/list`

**Comment by sanmadjack** [comment]
My pull request has a fix for this now

**Comment by sanmadjack** [comment]
@shish This may be important to include in the new release, since this affects any new installation.
