### ISSUE TITLE
Installing new Shimmie blank page & PHP fatal error

### ISSUE THREAD

**Issue by damjess** [shish/shimmie2#733]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version: 2.8.3
 - Database: postgres 11.7
 - Web server: apache 2.4
 - PHP: 7.4

**Client Software (please complete the following information)**
 - Device: Mac
 - Browser: Safari 13.1.1

**What steps trigger this bug**
1. Navigate to install directory
2. Enter database information
3. Click "Go!"

**What did you expect to happen?**
Expected to see the welcome page or information on errors

**What actually happened?**
Blank page. From the apache error log:

`PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PostgreSQL::set_timeout() must be of the type int, string given, called in /path/to/install/shimmie2/core/dbengine.php on line 95 and defined in /path/to/install/shimmie2/core/dbengine.php:114\nStack trace:\n#0 /path/to/install/shimmie2/core/dbengine.php(95): PostgreSQL->set_timeout()\n#1 /path/to/install/shimmie2/core/database.php(61): PostgreSQL->init()\n#2 /path/to/install/shimmie2/core/database.php(307): Database->connect_db()\n#3 /path/to/install/shimmie2/core/install.php(209): Database->count_tables()\n#4 /path/to/install/shimmie2/core/install.php(69): create_tables()\n#5 /path/to/install/shimmie2/core/install.php(42): do_install()\n#6 /path/to/install/shimmie2/index.php(35): install()\n#7 {main}\n  thrown in /path/to/install/shimmie2/core/dbengine.php on line 114, referer: http://mydomain.com/`

**Comment by sanmadjack** [comment]
What do you have DATABASE_TIMEOUT set to?

**Comment by shish** [comment]
Assuming this is a fresh install with no customisation, the only relevant code I can see is:

```
core/sys_config.php:_d("DATABASE_TIMEOUT", 10000);
```

and

```
core/dbengine.php:        $this->set_timeout($db, DATABASE_TIMEOUT);
```

I wonder if the installer isn't including sys_config.php for some reason, and then PHP is being PHP and silently converting the undefined value `DATABASE_TIMEOUT` into the string `"DATABASE_TIMEOUT"`?

(If that is that, then I wonder if there's a way to force PHP to crash on undefined variables instead of silently converting them to strings... and I also wonder how this passed the automated tests)

**Comment by shish** [comment]
ad1e52bf should fix this - I'll keep this issue open for now as a reminder to add more tests to catch issues like this in the future :)

**Comment by damjess** [comment]
Amazing! Thanks a bunch

**Comment by damjess** [comment]
Whoops I just noticed you waned it open still 😄

**Comment by shish** [comment]
eecd35d1 should stop this class of bug from happening again

2197b150 moves the PHP-sanity stuff into its own file so that it can be included before anything else, so that we can catch this bug ASAP, not merely "after initialization"
