### ISSUE TITLE
thumbnails are blurry when increasing its size

### ISSUE THREAD

**Issue by SpannerWZ** [shish/shimmie2#738]
(using DanbooruV2)

i have accomplished to increase thumbnail size by modifying style.css (so they do not overlap when using a greater thumb size)

the issue i have is that the thumbnails are now all blurry, i tried mass thumb regen and per image thumb regen and it doesn't work...

the same happens using GD and imagemagick with webP filetype, even worse in my local installation png´s transparent background became black

**Comment by sanmadjack** [comment]
You have to increase the thumbnail size in the settings. CSS just controls the display size of the image, it doesn't make the actual image files bigger.

You can also control the transparent color in the same settings. Only webp thumbnails will be able to have transparent backgrounds, jpg will not.

**Comment by SpannerWZ** [comment]
i have increased the size for that reason, using thumbnails of 250x250 with 100% on the quality, i'm using official release, not dev release so alpha color is not available yet in my installation, still on my local test server i have the exact same issue and its running the latest version of shimmie
![shimmie thumbs](https://user-images.githubusercontent.com/29823579/88434375-06d80980-cdce-11ea-8de3-5558b53a77c6.png)

**Comment by sanmadjack** [comment]
Does your screen have DPI scaling set to more than 100%?

**Comment by SpannerWZ** [comment]
no, also the issue repeats on mobile and other devices

**Comment by sanmadjack** [comment]
Can you post your updated css?

**Comment by SpannerWZ** [comment]
i changed some colors of the theme, that's why the line of the code is not the same as vanilla (Danbooru2) but i will have to take those changes back because it caused an error 500 when opening images (still don't know what is causing it)

in the attached image is the thumbnail code that i changed (from 220px)

![Anotación 2020-07-25 142438](https://user-images.githubusercontent.com/29823579/88463695-95a65e00-ce82-11ea-8fc5-8fb45f9c359c.png)

**Comment by LaureeGrd** [comment]
I had this confusion before. Did you remember to use bulk actions to regenerate the thumbnails with the new settings? Changing it to 250x250 will only make it work for new uploads or if you regenerate them
