### ISSUE TITLE
Video Thumb

### ISSUE THREAD

**Issue by xecuth** [shish/shimmie2#741]
**Server Software**
https://pastebin.com/6cpFmdpk

 - Shimmie version: 2.8.4
 - Database: mysql 10.3.23
 - Web server: apache 2.4.38

**Client Software (please complete the following information)**
 - Device: VirtualBox on Windows 10 with Debian 10.5
 - Browser: Chrome

**What steps trigger this bug**
Nothing special.

**What did you expect to happen?**
I expected to see thumb for video files.

**What actually happened?**
I see the content of the alt attribute.
![chrome_jVuC5NTc4I](https://user-images.githubusercontent.com/56955307/89986896-db866300-dc85-11ea-9ad8-2b057482afb4.png)

**Another**
I also use a custom danburu2 theme, but it doesn't matter as there is no video thumb for all themes.

**Comment by shish** [comment]
Do you have ffmpeg installed? (Also seeing that you're using GD for image thumbnails, imagemagick supports more types there too o.o)

**Comment by xecuth** [comment]
No, just installed, now it works, thanks a lot :3
