### ISSUE TITLE
Can't build image from source | Docker

### ISSUE THREAD

**Issue by kirikiyonami** [shish/shimmie2#742]
After downloading the shimmie from the github and write it:
`docker build -t shimmie2 .`
I see this:
```
Sending build context to Docker daemon  3.297MB
Step 1/26 : FROM debian:stable-slim AS app
 ---> 52baa1311484
Step 2/26 : RUN apt update && apt install -y composer php7.3-gd php7.3-dom php7.3-sqlite3 php-xdebug imagemagick
 ---> Using cache
 ---> deb16c79aa7b
Step 3/26 : COPY composer.json composer.lock /app/
 ---> Using cache
 ---> f88c225334db
Step 4/26 : WORKDIR /app
 ---> Using cache
 ---> ac271013c86c
Step 5/26 : RUN composer install --no-dev
 ---> Running in 7ca8a9e77466
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 13 installs, 0 updates, 0 removals
  - Installing bower-asset/jquery (1.12.4): Downloading (100%)
  - Installing bower-asset/jquery-timeago (v1.5.4): Downloading (100%)
  - Installing bower-asset/js-cookie (v2.1.4): Downloading (100%)
  - Installing bower-asset/mediaelement (2.21.2): Downloading (100%)
    Failed to download bower-asset/mediaelement from dist: Failed to execute unzip -qq -o '/app/vendor/bower-asset/mediaelement/2c4e78d06a147c3d0f8839a9f93c01ed' -d '/app/vendor/composer/c5da1289'

/app/vendor/composer/c5da1289/mediaelement-mediaelement-394db3b/media/other.mp4  bad CRC 07e80b56  (should be f489a9fe)

    Now trying to download from source
  - Installing bower-asset/mediaelement (2.21.2): Cloning 394db3b4a2

In Git.php line 354:

  Failed to execute git clone --no-checkout 'git@github.com:johndyer/mediaele
  ment.git' '/app/vendor/bower-asset/mediaelement' && cd '/app/vendor/bower-a
  sset/mediaelement' && git remote add composer 'git@github.com:johndyer/medi
  aelement.git' && git fetch composer


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

The command '/bin/sh -c composer install --no-dev' returned a non-zero code: 1
```

OS: Windows 10
Docker Toolbox version: 19.03.1

**Comment by shish** [comment]
Does this happen consistently?

Does it still happen with `docker build --no-cache`?

(Trying to repro myself, I actually hit a *different* composer installation error where it would half-install a package and then report "everything is fine" so docker would cache the broken result :/ )

**Comment by kirikiyonami** [comment]
> Does this happen consistently?
> 
> Does it still happen with `docker build --no-cache`?
> 
> (Trying to repro myself, I actually hit a _different_ composer installation error where it would half-install a package and then report "everything is fine" so docker would cache the broken result :/ )

I have same error with `docker build --no-cache`

**Comment by shish** [comment]
That is weird - it's building here and doesn't look like anything is significantly different about the code :(

Totally random guess as I'm not seeing anything specifically shimmie-related here... is a firewall blocking the git protocol or something? Like does the command that's failing in docker work when run by itself?

( `git clone --no-checkout 'git@github.com:johndyer/mediaelement.git' 'mediaelement' && cd 'mediaelement' && git remote add composer 'git@github.com:johndyer/mediaelement.git' && git fetch composer` )

**Comment by kirikiyonami** [comment]
I used docker on windows, I will try to build on my linux machine
