### ISSUE TITLE
Forum Extension Does Not "Enable"

### ISSUE THREAD

**Issue by psychosoundwave** [shish/shimmie2#753]
Hi Shish,

I sent an email to your webmaster email address, but figured I should post it here.

The forum extension didn't enable because in **/ext/forum/info.php** the KEY was "**dorum**" with a "d" instead of "**forum**".
I changed that, and disabled, and enabled the forum extension again and it works - although there is no link to the forum anywhere.
I have to manually link to **index.php?q=forum/index**

```
<?php declare(strict_types=1);

class ForumInfo extends ExtensionInfo
{
    public const KEY = "dorum";

    public $key = self::KEY;
    public $name = "Forum";
    public $authors = ["Sein Kraft"=>"mail@seinkraft.info","Alpha"=>"alpha@furries.com.ar"];
    public $license = self::LICENSE_GPLV2;
    public $description = "Rough forum extension";
}
```

**Server Software**

versions:
  shimmie: "2.8.4+"
  schema: 19
  php: "7.4.10"
  db: "mysql 10.1.41-MariaDB"
  os: "Linux c06.tmdcloud.com 3.10.0-962.3.2.lve1.5.36.el7.x86_64 #1 SMP Mon May 18 02:16:06 EDT 2020 x86_64"
  server: "LiteSpeed"

extensions:
  core: ["alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["admin","approval","autocomplete","blocks","bulk_actions","bulk_add","bulk_import_export","emoticons","emoticons_list","favorites","featured","forum","handle_archive","handle_video","home","link_image","random_image","random_list","regen_thumb","report_image","resize","rotate","site_description","sitemap","source_history","tag_history","trash","update","wiki"]
  handled_mimes: {"0":"image/jpeg","1":"image/gif","2":"image/png","3":"image/webp","4":"application/zip","6":"video/x-ms-asf","7":"video/x-msvideo","8":"video/x-flv","9":"video/x-matroska","10":"video/mp4","11":"video/ogg","12":"video/quicktime","13":"video/webm"}

stats:
  images: 1356
  comments: 1
  users: 4

media:
  memory_limit: "8.0MB"
  disk_use: "1.3TB"
  disk_total: "2.0TB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: ""
  branch: "HEAD"
  origin: ""

**Comment by shish** [comment]
Thanks for spotting this and figuring out the fix :) I will get that committed to the repo now

**Comment by psychosoundwave** [comment]
Awesome!
Do you know why it doesn't place a forum link in the navigation?

**Comment by psychosoundwave** [comment]
I added this to /ext/forum/main.php:

```
    public function onPageNavBuilding(PageNavBuildingEvent $event)
    {
        $event->add_nav_link("forum", new Link('forum/index'), "Forum");
    }
```
I'm not sure if that's legit, but it gets the link in the navigation! :)

**Comment by shish** [comment]
Looks like that feature was just never added, everyone who used that extension so far used it in conjunction with a custom theme :S

**Comment by shish** [comment]
That is even better than the fix I just tried :D
