### ISSUE TITLE
Comments only shows most recent page (no pagination)

### ISSUE THREAD

**Issue by psychosoundwave** [shish/shimmie2#755]
Hi!

I am running the latest master, and when viewing **index.php?q=comment/list** there is only a single page of comments shown. There is a "1" at the bottom of the page, but no link to page 2, 3, etc.

I did locate this : https://github.com/shish/shimmie2/issues/346 but I guess the problem continues still?

Also, the comment settings in page **index.php?q=setup** don't make any difference to what is displayed. 

Cheers,
~psychosoundwave

**Comment by psychosoundwave** [comment]
I thought this was a theme-specific issue, but it turns out it's not.
Anyone have any ideas as to why it only thinks there is 10 comments and only displays the most recent 10?
I have verified that there are 24 comments in my database (mysql).

**Comment by psychosoundwave** [comment]
OK so after some more digging, in this area:

`private function onPageRequest_list(PageRequestEvent $event)
    {
        global $cache, $database, $user;

        $where = SPEED_HAX ? "WHERE posted > now() - interval '24 hours'" : "";

        $total_pages = $cache->get("comment_pages");
        if (empty($total_pages)) {
            $total_pages = (int)($database->get_one("
				SELECT COUNT(c1)
				FROM (SELECT COUNT(image_id) AS c1 FROM comments $where GROUP BY image_id) AS s1
			") / 10);
    
            $cache->set("comment_pages", $total_pages, 600);
        }
        $total_pages = max($total_pages, 1);
        echo $total_pages;`

If I change:
`$total_pages = (int)($database->get_one("
				SELECT COUNT(c1)
				FROM (SELECT COUNT(image_id) AS c1 FROM comments $where GROUP BY image_id) AS s1
			") / 10);`

to:

`$total_pages = (int)($database->get_one("
				SELECT COUNT(c1)
				FROM (SELECT COUNT(image_id) AS c1 FROM comments $where GROUP BY image_id) AS s1
			") **/ 8**);`

I get more pages.

Also, if I just comment more (and leave the /10 in there) I see more pages appear, but the comment count is almost always incorrect.

Strange....

**Comment by shish** [comment]
That is strange - Do you have any kind of caching or `SPEED_HAX` mode enabled?

**Comment by psychosoundwave** [comment]
Definitely no SPEED_HAX enabled.
The web host doesn't have any caching enabled.

**Comment by psychosoundwave** [comment]
Changing:

```
$total_pages = (int)($database->get_one("
				SELECT COUNT(c1)
				FROM (SELECT COUNT(image_id) AS c1 FROM comments $where GROUP BY image_id) AS s1
			") / 10);
```

to:

```
$total_pages = (int)($database->get_one("
				SELECT COUNT(c1)
				FROM (SELECT COUNT(image_id) AS c1 FROM comments $where GROUP BY image_id) AS s1
			") / 10) +1;
```

(divided by 10 plus 1) seems to fix things for me!

**Comment by shish** [comment]
Looks like that nearly fixes it - but when you have an exact multiple of 10 commented images then you get an /extra/ page -- 4ac9ab2 should round up instead of rounding down, which I think fixes this for all cases :)

**Comment by psychosoundwave** [comment]
Ahhh that's perfect, and that's why you're the boss! \o/
