### ISSUE TITLE
false handling

### ISSUE THREAD

**Issue by sanmadjack** [shish/shimmie2#758]
I got this error with the current commit in master:

```
Internal Error
Message: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: ""

Query:

Version: 2.8.4+ (on 7.3.23-1+ubuntu18.04.1+deb.sury.org+1)

Stack Trace:

#0 /var/www/fanservice/ext/approval/main.php(176): Database->execute('UPDATE images S...', Array)
#1 /var/www/fanservice/ext/approval/main.php(240): Approval::approve_image(35182)
#2 /var/www/fanservice/core/send_event.php(113): Approval->onBulkAction(Object(BulkActionEvent))
#3 /var/www/fanservice/ext/bulk_actions/main.php(194): send_event(Object(BulkActionEvent))
#4 /var/www/fanservice/core/send_event.php(113): BulkActions->onPageRequest(Object(PageRequestEvent))
#5 /var/www/fanservice/index.php(82): send_event(Object(PageRequestEvent))
#6 {main}
```

This is an example of that false handling issue that I submitted a fix for, but since you said that it should have been fixed somewhere higher up, I wanted to give you  away to reproduce the issue.

**Comment by sanmadjack** [comment]
I suppose I should say how I triggered it, huh. It happens when using the approval extensions and approving pretty much anything.

**Comment by shish** [comment]
Starting to narrow this down, seems to be happening in PDO

```
        $db->execute("DROP TABLE IF EXISTS bools");
        $db->execute("CREATE TABLE bools (nt BOOLEAN, nf BOOLEAN, pt BOOLEAN, bf BOOLEAN)");
        $db->execute(
            "INSERT INTO bools VALUES (true, false, :true, :false)",
            ["true"=>true, "false"=>false]
        );
        $data = $db->execute("SELECT * FROM bools")->fetchAll();
        var_dump($data);  # "1", "0", "1", ""
```

Whyyyyyyyyyyyyyy T_T

**Comment by shish** [comment]
ffsphp 1.0.3 *should* fix this - I've updated Shimmie's `composer.lock` to use that one

**Comment by sanmadjack** [comment]
I'll update and let you know if it fixes it over here

**Comment by sanmadjack** [comment]
This appears to work now. Perhaps it would be a good idea to add a test to make sure this doesn't regress at some point?

**Comment by fliegenfuerst** [comment]
just dealt with this and changing 

`public static function approve_image($image_id)
    {
        global $database, $user;

        $database->execute(
            "UPDATE images SET approved = :true, approved_by_id = :approved_by_id WHERE id = :id AND approved = :false",
            ["approved_by_id"=>$user->id, "id"=>$image_id, "true"=>true, "false"=>false]
        );
    }

    public static function disapprove_image($image_id)
    {
        global $database;

        $database->execute(
            "UPDATE images SET approved = :false, approved_by_id = NULL WHERE id = :id AND approved = :true",
            ["id"=>$image_id, "true"=>true, "false"=>false]
        );
    }`
starting on line 170 in /ext/approval/main.php to:

`public static function approve_image($image_id)
    {
        global $database, $user;

        $database->execute(
            "UPDATE images SET approved = :true, approved_by_id = :approved_by_id WHERE id = :id AND approved = :false",
            ["approved_by_id"=>$user->id, "id"=>intval($image_id), "true"=>'Y', "false"=>'N']
        );
    }

    public static function disapprove_image($image_id)
    {
        global $database;

        $database->execute(
            "UPDATE images SET approved = :false, approved_by_id = NULL WHERE id = :id AND approved = :true",
            ["id"=>intval($image_id), "true"=>'Y', "false"=>'N']
        );
    }`

did the trick
