### ISSUE TITLE
Custom Themes, Existing ones

### ISSUE THREAD

**Issue by psychosoundwave** [shish/shimmie2#760]
I realize that shimmie comes with a few, but does anyone have any information about alternative themes? 

Where to find them?
Information on how the CSS relates to the theme and other things you'd want to know if creating your own.

Thanks!

**Comment by shish** [comment]
I'm not aware of any public themes that aren't included by default - lots of people do their own customizations and then keep them to themselves; the couple of people who did want to share, decided to share by adding them here

https://github.com/shish/shimmie2/wiki/Development-Info has a section on how themes work, though it's not very detailed - most people just copy-paste one of the provided themes and then tweak it until they like it.

Do you have any particular questions? I'm happy to add to the docs but I'm too familiar with the code to see what's missing ^^;
