### ISSUE TITLE
Make use of X-Forwarded-For

### ISSUE THREAD

**Issue by shish** [shish/shimmie2#800]
Is this actually a good idea? It's missing in proxies that care about privacy, and can be faked...

We could at least log it somewhere maybe?

**Comment by dali99** [comment]
X-Forwarded-For is required when using a reverse-proxy in front an application. If you don't, all logged ips are just the reverse proxy

It should be turned on with a setting though, or have an ip whitelist for trusted proxies

**Comment by PVNFU-28** [comment]
running shimmie2 with a reverse proxy and currently facing this issue, a setting would be great

**Comment by shish** [comment]
I'd personally been using the X-Real-IP boolean setting from #869 for a while, but added c5395df to make use of either X-Real-IP or X-Forwarded-For, with a list of trusted proxies rather than a boolean
