### ISSUE TITLE
Admin extension dump feature?

### ISSUE THREAD

**Issue by LaureeGrd** [shish/shimmie2#809]
According to the description of the "Board Admin" extension, there should be a way to dump all images and tags on the site. But I can't find said feature. I tried switching themes in case one of them had it visible, and I also took a quick look at the extension's code. Was it never implemented? Am I dumb? thanks lol

**Comment by shish** [comment]
The feature there was moved into the separate "bulk import / export" extension, but the documentation wasn't moved ^^

**Comment by shish** [comment]
Now that I look at it, the admin extension itself does very little these days, perhaps time to move the remaining actions into their own extensions, then the admin page in general into the core...

**Comment by shish** [comment]
(4aabb77a should clean things up a bit - `admin` is now just a shell enabled by default, and the random features which lived there in the past are now in more sensible places (export admin stuff in the export extension, tag admin stuff in the tag extension, media admin stuff in the media extension, etc))

**Comment by LaureeGrd** [comment]
Great!
