### ISSUE TITLE
How do i install this?

### ISSUE THREAD

**Issue by ghost** [shish/shimmie2#811]
im using cPanel how am i suppose to install this?

**Comment by shish** [comment]
I've never used cPanel, so can't do anything other than guess - hopefully it has some way to upload files? (Or your host offers something like FTP?)

In that case the simplest way to get started would be to fetch the latest version from https://github.com/shish/shimmie2/releases , unzip that, then copy the files to your host, then visiting the folder where files were uploaded should show the installer, and then if your host supports SQLite you should be able to use that as a database with no further configuration
