### ISSUE TITLE
Auto-tag creation broken?

### ISSUE THREAD

**Issue by laureegrd** [shish/shimmie2#817]
There seems to be a problem with the auto-tagging feature that applies newly created auto-tags to existing posts.
Image::by_id() is expecting an integer but the database returns strings?
https://github.com/shish/shimmie2/blob/02e0f925acc0390a4d280c89608169590b2b0081/ext/auto_tagger/main.php#L272

Adding a simple (int) casting solved it for me but I'm guessing it is not good to be getting strings from an int type column in the first place. This is not new, btw. I've always thought it was a problem on my server setup (it could be), but just in case, here it is.

---
**Server Software**
 - Shimmie version: 2.8.4+
 - Database: mysql 10.5.8-MariaDB
 - Web server: lighttpd/1.4.58

**What steps trigger this bug**
1. Go to '/auto_tag/list'.
2. Add auto-tags to a tag that is present on at least one post.
3. You get the error.

**Comment by sanmadjack** [comment]
Can you check your database and check what type image_tags.image_id is? It's an integer on mine, but I want to rule out a possible inconsistency. @shish I'm unable to reproduce in my branch, could there be something in the db library stuff that would be doing this?

**Comment by LaureeGrd** [comment]
Sorry, forgot to mention. Yes I have checked the db structure and it is an int.
