### ISSUE TITLE
Tag Edit Cloud doesn't work when sorted by Relevance 

### ISSUE THREAD

**Issue by MetallicAchu** [shish/shimmie2#820]
**Server Software**
about:
title: "Shosho's Gallery"
theme: "danbooru2"
url: "http://adars.co.il/"

versions:
shimmie: "2.8.4+"
schema: 21
php: "7.3.27"
db: "mysql 5.6.41-84.1"
os: "Linux gator3235.hostgator.com 4.14.146-225.ELK.el6.x86_64 #1 SMP Sat Sep 21 01:19:55 CDT 2019 x86_64"
server: "Apache"

extensions:
core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
extra: ["auto_tagger","autocomplete","bulk_actions","bulk_add","bulk_download","favorites","featured","google_analytics","handle_video","home","image_view_counter","random_image","random_list","rating","regen_thumb","rotate","site_description","sitemap","tag_categories","tag_editcloud","tag_history","tag_tools","tips","update","wiki"]
handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]

stats:
images: 38894
comments: 0
users: 3

media:
memory_limit: "8.0MB"
disk_use: "1.4TB"
disk_total: "1.5TB"

thumbnails:
engine: "gd"
quality: 75
width: 192
height: 192
scaling: 100
mime: "image/jpeg"

git:
commit: "efde5e1"
branch: "HEAD"
origin: "https://github.com/shish/shimmie2"

**What steps trigger this bug**
When sorting Tag Edit Cloud option by Relevance, it doesn't show any tags in the Edit Cloud, at all.

**What did you expect to happen?**
On the left side of the screen, there is a list populated by related tags, expected this option to mirror that list on the cloud edit option, but on my end nothing happened.

**What actually happened?**
Shows only the image's current tags

**Comment by noisycat05** [comment]
I am also having this issue.

**Comment by jellykells** [comment]
Seeing the same issue along with this error in my logs

```
FastCGI sent in stderr: "PHP message: PHP Warning:  Array to string conversion in /srv/http/shimmie2/vendor/shish/ffsphp/src/PDOStatement.php on line 28
```

I enabled statement logging in postgres and it appears the literal string 'Array' is being passed as a parameter

```
DETAIL:  parameters: $1 = '2', $2 = '2', $3 = 'Array', $4 = '36'
```
