### ISSUE TITLE
Video Handling issues. 

### ISSUE THREAD

**Issue by sahaq** [shish/shimmie2#822]
**Server Software**
 - Shimmie version:
  shimmie: "2.9.1+"
  schema: 21
  php: "8.0.3"
  db: "mysql 10.3.27-MariaDB-0+deb10u1"
  os: "Linux web 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64"
  server: "Apache/2.4.38 (Debian)"

**Client Software (please complete the following information)**
 - Device: Desktop/Mobile
 - Browser: Chrome, Firefox, Edge

**What steps trigger this bug**

1. Navigate to index of site
2. Click choose files under "Upload" header
3. Select a Webm or MP4
4. Add a tag
5. Hit submit.

**What did you expect to happen?**
Previous use of the this program, with HandleVideo plugin enabled, it would use Imagemagick to get a thumbnail for the video, then upload/present the file as expected.

**What actually happened?**
500 error, 

Fatal error: Uncaught Error: Typed property Image::$width must not be accessed before initialization in /var/www/site.tld/public_html/ext/handle_video/main.php:87 Stack trace: 
#0 /var/www/site.tld/public_html/core/extension.php(399): VideoFileHandler->media_check_properties() 
#1 /var/www/site.tld/public_html/core/send_event.php(113): DataHandlerExtension->onMediaCheckProperties() 
#2 /var/www/site.tld/public_html/core/extension.php(341): send_event() 
#3 /var/www/site.tld/public_html/core/send_event.php(113): DataHandlerExtension->onDataUpload() 
#4 /var/www/site.tld/public_html/ext/upload/main.php(355): send_event() 
#5 /var/www/site.tld/public_html/ext/upload/main.php(236): Upload->try_upload() 
#6 /var/www/site.tld/public_html/core/send_event.php(113): Upload->onPageRequest() 
#7 /var/www/site.tld/public_html/index.php(82): send_event() 
#8 {main} thrown in /var/www/site.tld/public_html/ext/handle_video/main.php on line 87

Initial setup was done on a current debian stable deployment, manually installing Apache/MariaDB/PHP8 via the Sury PPA.  At one point it successfully uploaded one MP4, but no others afterward.  I initially thought this was an issue with porting to PHP8, so uninstalled/reverted to 7.4, and encountered same issues.  Then figured it may be due to manually compiling ffmpeg/imagemagick, so said screw it, wiped the whole box, did a fresh install, installed LAMP stack again (Sury for PHP8), then used apt to install packaged imagemagick/ffmpeg.  The same issue is present.  

Side note; attempting to upload a video file seems to fail before any Shimmie-side logging can catch it, as nothing is put into the event log (Logging - Database) - Above error pulled from apache error log for the domain.

**Comment by noisycat05** [comment]
I am also encountering the same issue on PHP 7.4 and PHP 8.

**Comment by arthurmv** [comment]
Same issue here. Any fix there?

**Comment by MetallicAchu** [comment]
This was addressed in a previous fix
If you’re not up to date on the latest version, edit the following:

core/imageboard/image.php 

In `class Image`

Make sure that this is set:
```
    public int $height = 0;
    public int $width = 0;
```

If not, set it and report back if this fixed your problem

**Comment by arthurmv** [comment]
Works like a charm. Thank you @MetallicAchu

**Comment by MetallicAchu** [comment]
@sahaq @noisycat05 does this work for you as well?

**Comment by sahaq** [comment]
@MetallicAchu So sorry for the insane delays, but yes, on a recent reinstall, I still needed to put in the suggested fixes manually, but this did allow everything to function as intended.

**Comment by MetallicAchu** [comment]
Ah, I understand the problem here. 
The source code was fixed but the release not updated accordingly, so it might cause a confusion. 

@shish we had a lot of changes since March. Is it possible to publish an updated release? Thanks!
