### ISSUE TITLE
internal 500 errors, probably being caused by varnish, making shimmie unable to get user accounts on the system

### ISSUE THREAD

**Issue by mmd123** [shish/shimmie2#823]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version: latest version (just installed it yesterday, 04-11-2021)
 - Database: [mysql, postgres, ...] mysql-8.0 I think it said
 - Web server: [apache, nginx, ...] apache2, varnish cache, memcached

**Client Software (please complete the following information)**
 - Device: [e.g. iphone, windows desktop] windows desktop
 - Browser: [e.g. chrome, safari] waterfox (variant of firefox)

**What steps trigger this bug**
1. Go to '...' I have absolutely no idea, I went to bed, succesfully having set shimmie up with memcached, and varnish, and uploaded 2 images successfully, and everything worked, this morning however, when I go to add more images, its throwing an internal server 500 error, which I think I was able to peg down to being an issue in one of the php files, but what the hell made this php file start shitting itself I'm not really sure, I do know that whatevers going on, only started to happen after I rebooted both my computers from working on it the prior night, so I think it might have something to do with a logout system not liking me or something.. anyways... heres the log entry.

[Mon Apr 12 11:05:14.440697 2021] [php7:error] [pid 1000] [client 127.0.0.1:52182] PHP Fatal error:  Uncaught TypeError: Return value of _get_user() must be an instance of User, null returned in /var/www/html/core/util.php:653\nStack trace:\n#0 /var/www/html/index.php(77): _get_user()\n#1 {main}\n  thrown in /var/www/html/core/util.php on line 653

line after line after line of this log entry exist in the internal-http_error.log file, which is part of the varnish cache proxy, so I think it has something to do with varnish not behaving, but I'm not sure why, or how to fix it.

**What did you expect to happen?**
I expected to be able to just load the site back up after having rebooted my pc and continue to upload to shimmie

**What actually happened?**
I'm getting these lines of errors for an apparently non-existent admin user account that I know exists, given I think varnish is murdering the system somehow.

**Comment by shish** [comment]
Varnish *shouldn't* be able to cause errors like that - it's possible it's triggering a bug in shimmie but I'd still call that a shimmie bug

Looking at the code itself - it's failing in the `_get_user()` function, which basically says "if a user is logged in, fetch that user's data - if not, fetch the anonymous user data"

My guess would be that you were logged in last night, with a user account that exists; but then overnight got logged out (either cookie expired, or was cleared, or indeed varnish might be altering the cookie) - then this morning it's trying to find the anonymous account and not finding it.

Specifically I'm looking at:
```
$my_user = User::by_id($config->get_int("anon_id", 0));
```

Are you able to look at the database directly? Looking at this code there are a few things which should be true, but if it's crashing then something isn't true:

- there should be a row in the "config" table where `name=anon_id` and `value` is set to a number
- if that's missing for some reason, then we default to assuming our anonymous user has id=0
- there should be a row in the `users` table with `id=<value of anon_id above, or 0 if anon_id is missing>`

(If anon_id is set, and it's pointing to a valid user in the `users` table, then something is _very_ weird...)

**Comment by mmd123** [comment]
I am 99% sure it is cookie related, I recently disabled a firefox addon that clears cookies on regular intervals (it was not behaving properly), so I can almost positively confirm that's part of the issue, but it doesn't even let the homepage load without the cookie, as for the anon user and database, let me look into that in a bit and respond with my findings...I do not think i messed with the anonymous user yet, planned to disable it but don't think I did so yet, let me double check that.

**Comment by mmd123** [comment]
strange...apparently I DID fuck with the anonymous ID, it was null, no value, set it back to 0 in the database, refreshed the page and still not loading, rebooting the vm that shimmie is running on to see if it changes anything, but when browsing the users table, anon is set to 1

**Comment by mmd123** [comment]
AHAH...setting anonymous ID in config table to 1, to match what it is in the user table fixed it, site/shimmie loads again!  THANK YOU SHISH...this softwares awesome...but apparently yet again I found a way to kill things xD I have an unnatural talent for that!
