### ISSUE TITLE
Manual offline generation of video thumbnails (or usage of the static "Video File" thumb)?

### ISSUE THREAD

**Issue by NeonWabbit** [shish/shimmie2#832]
In situations where one absolutely cannot install ffmpeg on their server, is it possible to run an ffmpeg command on a device where ffmpeg _is_ installed, then drop the generated thumbnails into a folder on the server?

If not, I've also noticed there is a image file at "ext/handle_video/thumb.jpg" that just reads the text "Video File". How can one make all videos use this file as their thumbnail?

**Comment by shish** [comment]
> is it possible to run an ffmpeg command on a device where ffmpeg is installed, then drop the generated thumbnails into a folder on the server

There's no automation in place for that, but it's definitely possible -- for each post in the database, the full-size data is `data/images/<hash of full-size data>` and thumbnail is `data/thumbs/<hash of full-size data>` (ie the filename part is the same - so one could write a script to find files in `images` that are missing a corresponding file in `thumbs`)

> How can one make all videos use this file as their thumbnail?

Looks like that feature actually got lost in the big media-encoding-system rewrite -- shouldn't be too hard to add it back though (see how `ext/handle_mp3/main.php` uses a static thumbnail in `create_thumb()` - we'd need a config option (or, automatically fall-back when ffmpeg doesn't work) to do the same thing in `ext/handle_video/main.php`)

**Comment by shish** [comment]
`/_thumbs` and `/_images` are web server aliases which allow us to give the files nice names; by default eg `/_thumbs/abcdefg/thumb.jpg` -> `/data/thumbs/ab/abcdefg` (ie, the "thumb.jpg" part is ignored, so you can use whatever filename you like and it'll end up with the same file; and the layers of folders in the `data` directory are handled automatically)

All the files in `/data/thumbs/` should be regular JPEG files (minus the extension) - I wonder how you're uploading them, in particular wondering if you're using FTP (which can occasionally corrupt files without destroying them completely, which might explain them looking glitchy)

There's nothing special on the database side; in fact there's no checking that a thumbnail exists at all -- we create a link to `_thumbs/abcdefg/thumb.jpg`, which the webserver converts to `data/thumbs/ab/abcdefg`, and then the webserver serves that file (if it exists, and if the webserver has permission to read the file). I wonder if you `right click -> open image` on the missing thumbnail that you manually uploaded, does it say "404" or "corrupt image" or "permission denied" or anything?

**Comment by NeonWabbit** [comment]
Progress has been made! I discovered that as well as clearing browser cache, I also needed to manually purge _Cloudflare's_ cached versions of the thumbnails by entering the URLs one by one into the Custom Purge section of the Caching tab on Cloudflare's website.

Then from uploading the thumbs again (via FTP), the manually-generated thumbs did display on the booru as corrupted images, so I tried to find another way, such as uploading them from the File Manager in my server's cPanel, and now they are not glitchy anymore! So yes, it must've been FTP causing the corruption.

All should be well now, though the thumbs are displaying as 1:1 square aspect ratio images, instead of the 16:9 aspect ratio images they should be... but I guess it's better than nothing!

**So the working method is:**
1. Run FFmpeg thumbnail command on video
2. Rename thumb.jpg to hash of full-size data with no file extension
3. Upload to correct folder via File Manager in cPanel
4. Custom purge Cloudflare's cache of broken thumbnails by listing URLs
5. Ctrl+Shift+R (Chrome/Firefox browser cache hard refresh) on a page with broken thumbnails

Anything that can optimize this further, such as an alternative to cPanel's File Manager?
If not, I am perfectly happy to manually do this for all video files (and some larger image files which I discovered don't have thumbnails generated) by myself. ^^

**Comment by shish** [comment]
> though the thumbs are displaying as 1:1 square aspect ratio images

ffmpeg is also used for checking video metadata (in this case width and height), so if that's missing then it'd probably default to square yeah

> Anything that can optimize this further, such as an alternative to cPanel's File Manager?

sftp is generally more modern than ftp with fewer edge-cases; regular FTP *should* work but may need settings tweaked (IIRC "upload as text" vs "upload as binary", but it's been ~15 years since I last used regular FTP)

**Comment by NeonWabbit** [comment]
Well that should be everything then! We have a working solution to solve the main issue, and stuff to look into to solve the lesser ones.

Thank you so very much for the help! I'll close this issue now.
