### ISSUE TITLE
Error invalid post ID

### ISSUE THREAD

**Issue by PVNFU-28** [shish/shimmie2#834]
**Server Software**
 - Shimmie version: 2.9.1+
 - PHP: 7.4.3
 - Database: MySQL 8.0.25
 - Web server: Apache 2.4.41

**Client Software (please complete the following information)**
 - Device: Windows laptop
 - Browser: Chrome

**What steps trigger this bug**
1. Go to https://carbu.tk/post/list/truck/1
2. Click on any post

**What did you expect to happen?**
I expected the post to show up

**What actually happened?**
"Error Invalid post ID" showed up, looking at the URL and comparing it with other boorus using the same software it's missing a # before the search=truck
![carbooru](https://user-images.githubusercontent.com/34801669/119908259-92f41980-bf28-11eb-8cae-e679b0b40860.png)

**Comment by MetallicAchu** [comment]
You’re right, the correct phrasing is with a # sign. 
It seems like maybe your source changed, because it doesn’t work on any of your other tags as well. 

Would you consider rebuilding Shimmie2 gallery? That would probably be the best solution

**Comment by PVNFU-28** [comment]
How do I rebuild Shimmie2 gallery?

**Comment by MetallicAchu** [comment]
Download the source code and copy all the files to the folder that contains your gallery, overwrite every file present. 

The pictures information and tags are stored in the database so it shouldn’t be affected

**Comment by PVNFU-28** [comment]
And which files would that be? sorry I'm having a hard time understanding shimmie's structure. The error only happens when I have the Danbooru theme on, on all the other themes, the bug does not happen.

**Comment by PVNFU-28** [comment]
I have since switched to Danbooru2 so you won't be able to replicate the bug on my instance, it would be great if anyone tested on the last release and if it dosn't happen for them, close the issue.
