### ISSUE TITLE
'Fit Height' and 'Fit Both' locks file dimensions

### ISSUE THREAD

**Issue by PVNFU-28** [shish/shimmie2#836]
**Server Software**
 - Shimmie version: 2.9.1+
 - PHP: 7.4.3
 - Database: MySQL 8.0.25
 - Web server: Apache 2.4.41

**Client Software (please complete the following information)**
 - Device: Windows laptop
 - Browser: Chrome

**What steps trigger this bug**
1. Go to https://carbu.tk/post/view/55
2. Click on 'Fit Height' or 'Fit Both'

**What did you expect to happen?**
I expected for the image to fit the height and then be able to change the dimensions by click another option like 'Fit Width' or 'Full Size'

**What actually happened?**
When you click any other option after clicking 'Fit Height' or 'Fit Both', the image will stay the same, to able to change the images size you have to reload the page.
I know this is not my installations fault because it also happens on other boorus running the same version, rule34.paheal.net for example. This does not happen on Shimmie Testbed I suspect because hes still on Shimmie version 2.8.4

**Comment by MetallicAchu** [comment]
Recreated the same problem using multiple browsers.
I think this is a problem with how the cookies are saved

**Comment by shish** [comment]
This should be fixed now? Feel free to re-open if not :)
