### ISSUE TITLE
Booru statistics page

### ISSUE THREAD

**Issue by PVNFU-28** [shish/shimmie2#837]
Gelbooru 0.1 has an stats page and it contains various rankings about user interaction, see for example: https://gravityfalls.booru.org/stats/

The page I want should have:
Top 10 taggers, Top 10 commenters, Top 10 image posters
Top 100 of each previously mentioned stat
Each top should mention place, amount and username. (just like Gelbooru)

Top 10 forum posters and Top 10 favoriters are optional.
Time settings are not needed, I think the stats should only be of all time.
Pie chart is not needed.

I think it would give an incentive to users to interact more with the site.

**Comment by bobama5000** [comment]
I second this idea. The one thing I miss from using booru.org is the stats page. Seeing numbers go up and surpassing other people make uploading, tagging, and commenting sort of like a game, and most certainly encourages interaction.
