### ISSUE TITLE
Notes are not displayed

### ISSUE THREAD

**Issue by mitya12342** [shish/shimmie2#838]
**Server Software**

 - Shimmie version: 2.9.1+ commit c4ae68fb
 - Database: mysql 10.3.24-MariaDB
 - Web server: Apache/2.4.43 (Unix)

**Client Software **
 - Device: Windows 10 laptop
 - Browser: same behavior in latest Chrome and Firefox

**What steps trigger this bug**
1. Enable notes plugin
2. Go to any post in shimmie2
2. Click on Add note
3. Input note text
4. Add note
5. Try to find it

**What did you expect to happen?**
Note rectangle appears on image after page reload.

**What actually happened?**
Note appears in database
note javascript array is being set
No note appears anywhere on image even after clearing cache

**Comment by bobama5000** [comment]
This bug still exists. Hopefully it's fixed soon

**Comment by shish** [comment]
A whole lot of JS stuff got changed and this is working for me now - if it's not working for you feel free to re-open, also it'd be good to know what theme you're using and whether there are any errors in the browser's javascript console :)

**Comment by shish** [comment]
Actually, 05a981d935bdd06083cebf9514cd71c6c8c1016c goes ahead and rewrites 100% of the notes frontend ^^
