### ISSUE TITLE
edit image mime types

### ISSUE THREAD

**Issue by borkform2555** [shish/shimmie2#848]
Hello, i would like to disable webp mime type, i want to remove it and ban posting using that file type.
I tried to find option, but i can't find.

**Comment by shish** [comment]
Right now there's no option for this, you'd need to edit `ext/handle_pixel/main.php` to remove `MimeType::WEBP` from `$SUPPORTED_MIME`

Leaving this issue open in case somebody thinks of a nice way to have this be editable, if it's a generally-useful feature

**Comment by tegaki-tegaki** [comment]
I might look at this a bit... I'm currently on the mindset of "allow all file types on upload", but then forcibly transcode them to the single format that I want for my booru.

My end "goal" for my booru is to store data as _**minimally**_ as possible (costs and growth!), while allowing them to be viewable on as many **_devices_** as possible, but also allow data to originate from as **_many formats_** as possible. 

my thoughts... although subjective:
- jpeg doesn't support transparency
- gif is too big
- png is too big
- webm doesn't play on iphones :(

left me with the following choices:
- webp for images (a bit 'softer'/blurry than jpeg, but lose the classic 'blocky' jpeg artifacts at roughly same compression level)
- mp4 for video

I haven't thought about every file format ofc... but the end result should be flexible for future formats and file format tastes!

**Comment by tegaki-tegaki** [comment]
also, before I code anything: would something like the way checkboxes exist in eg the `transcode_video` extension be a nice way to do this? (it's what comes to mind first, and it's similarish to what exists!)

**Comment by tegaki-tegaki** [comment]
This can probably be closed when something like https://github.com/shish/shimmie2/pull/907 is merged... pending review!

**Comment by tegaki-tegaki** [comment]
@shish since #907 was merged, this can be closed! 🙌  (one less issue! 🎉 )
