### ISSUE TITLE
Can't run in Docker (Windows) from source

### ISSUE THREAD

**Issue by HeCorr** [shish/shimmie2#849]
**Server Software**
 - Shimmie version: `v2.9.1`
 - Database: none yet
 - Web server: the default (?)

**Client Software**
 - Device: Windows 10 Pro [1909]
 - Browser: not applicable

**What steps trigger this bug**
1. Clone the repo
2. Build the Docker image [as per instructions](https://github.com/shish/shimmie2/wiki/Docker#build-custom-image)
3. Try to run the container. I used the command `docker run --rm -ti -p 8000:8000 --name shimmie shimmie2`

**What did you expect to happen?**
I expected it to start normally.

**What actually happened?**
This error showed up:
```
' is not a valid group name
useradd: group '1000' does not exist
chown: invalid user: 'shimmie:shimmie'
su-exec: getpwnam(shimmie): Success
```

**Extra info**
First I tried building from the `master` branch, and when this error occurred, I checked out the latest release tag with `git checkout tags/v2.9.1 -b latest` and tried again, with no success (and yes I did use `--no-cache`).
Initially I tried running the image on a Linux server but the build process was taking so long that I moved it onto my Windows machine.
By the way, I **had** successfully run the official image from Dockerhub before, but I don't remember which version it was.

**Comment by shish** [comment]
Ah, looks like upstream debian released a new version, and since shimmie builds on top of "debian:testing" (Which up until recently meant "the beta for v11" and now means "the beta for v12"), that also got bumped to a major new release. I expect the fix would be to update the Dockerfile to use `debian:stable` (ie, v11). I'm testing that now, but I'm on mobile internet so it'll take a while to download the new docker base images...

**Comment by HeCorr** [comment]
Ohh, that would make sense. I'm trying it right now as well  ;)

**Comment by HeCorr** [comment]
Aaaand nope, same error unfortunately.  :(

![image](https://user-images.githubusercontent.com/75134774/141002282-ce6c4985-216e-48ff-819f-e52d39b25374.png)

**Comment by shish** [comment]
Hmm, weirdly it's working for me with either version...

Can you try adding at the top of tests/docker-init.sh
```
#!/bin/sh
echo UID=$UID, GID=$GID
```
And then rebuild and rerun? It looks like one of those is somehow set to something unusual (they should both be "1000" by default)

**Comment by HeCorr** [comment]
Sure thing! gimme a sec.

**Comment by HeCorr** [comment]
Okay, this is the result:

```
: not founddocker-init.sh: 2:
UID=1000, GID=1000
: not founddocker-init.sh: 4:
' is not a valid group name
useradd: group '1000' does not exist
chown: invalid user: 'shimmie:shimmie'
su-exec: getpwnam(shimmie): Success
```

I believe the "not found" errors are due to extra lines I left in the script:

![image](https://user-images.githubusercontent.com/75134774/141005894-3064461e-6afc-449b-a448-e8c229205728.png)

**Comment by HeCorr** [comment]
Same thing on my Linux server  =/

Still building from tag `v2.9.1` and image `debian:stable` btw. Let my try from `master` once again..

**Comment by HeCorr** [comment]
Yep, there's **definitely** something very wrong going on.

```
UID=1000, GID=1000
'seradd: invalid user name 'shimmie
chown: invalid user: 'shimmie:shimmie'
su-exec: getpwnam(shimmie): Success
```

**Comment by HeCorr** [comment]
Trying `#!/bin/bash` instead of `#!/bin/sh`.. It has never worked well for me anyway  :)

**Comment by shish** [comment]
Looks like there's somehow a `\r` getting in there? Like the error should be

`useradd: invalid user name 'shimmie'`

But it's getting

`useradd: invalid user name 'shimmie\r'`

I wonder if you`git clone`d the repository from windows, and it set newlines to `\r\n`, but then Linux / docker are expecting `\n`, so it treats `\r` as part of the variable...

**Comment by HeCorr** [comment]
It could be.. let me try updating the `.gitattributes` real quick..

**Comment by shish** [comment]
Exact byte sizes, in case that's what's being changed
docker-init.sh 327
Dockerfile 2252

MD5 (Dockerfile) = bbb362f728bfa66c27de259d0cf70a93
MD5 (tests/docker-init.sh) = 90b165bfe6b2370368b102c7579e8c94

**Comment by HeCorr** [comment]
Well, that seems to have been the issue.  :)

Thank you very much!

I'll try adding `*.sh text eol=lf` to `.gitattributes` and cloning my own repo to see if that fixes it for good.

**Comment by HeCorr** [comment]
> I'll try adding `*.sh text eol=lf` to `.gitattributes` and cloning my own repo to see if that fixes it for good.

That doesn't seem to work for some reason. Git being Git I guess.. Whatever.

**Comment by HeCorr** [comment]
Today I tried running Shimmie2 in Docker and got these errors:

![image](https://user-images.githubusercontent.com/75134774/153330333-cb7effff-02ff-4614-879a-d52b9af74330.png)

And changing `debian:testing-slim` to `debian:stable` (the first suggestion for the other issue) in the Dockerfile fixed it.

So thank you again!  xD
