### ISSUE TITLE
Unable to Access rule34.paheal.net on Verizon ISP Network

### ISSUE THREAD

**Issue by BigNStrauss** [shish/shimmie2#853]
**Client Software**
 **Device:** Windows desktop
 **Browser:** Chrome, Firefox

**What steps trigger this bug**
**1.** Be on a Verizon ISP network.
**2.** Attempt to load https://rule34.paheal.net
**3.** The site can't be contacted.

**What did you expect to happen?**
The site loads like it did previously.

**What actually happened?**
The site can't be contacted when on a Verizon ISP network.

**Additional info**
Myself and a few others recently lost the ability to connect to https://rule34.paheal.net when using a Verizon ISP network. We can connect if on a different network such as our phone's LTE network. Have you made any changes recently to the website's infrastructure or backend at all?

This also recently happened with https://rule34video.com because the owner began using DDoS-Guard which is a Russian product with a Russian IP which Verizon blocks for some reason. The owner created a mirror site (https://rule34video.party) which allowed Verizon ISP users to connect still.

These symptoms seem to be identical and I'm curious if you've implemented DDoS-Guard or some other similar product with your website that's now causing it to be blocked for us. Any information would be greatly appreciated. Thank you for your time.

**Comment by BigNStrauss** [comment]
**Update:** I think I got a little ahead of myself. The site seemed to come back up an hour or so later. Perhaps there was some work being done on it or a temporary interruption of some kind. Still weird that I could access it from my phone but not on my Verizon network during those times.

Will keep an eye on it the next few days.

**Comment by dali99** [comment]
Shimmie does not have anything to do with paheal.net. They only use shimmie for their imageboard. Please find their contact information rather than filing issues in this repository.
