### ISSUE TITLE
Cannot upload anything

### ISSUE THREAD

**Issue by yls4** [shish/shimmie2#856]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version: 2.9.1, from a fresh install and fresh database
 - Database: mysql
 - Web server: apache

**Client Software (please complete the following information)**
 - Device: [e.g. iphone, windows desktop]
 - Browser: [e.g. chrome, safari]

**What steps trigger this bug**
Attempt to upload literally anything

**What did you expect to happen?**
Upload

**What actually happened?**
No handler could be found for the page 'index.php?q=upload', because the URL is incorrect and tries to access http://localhost/index.php?q=index.php?q=upload

I'm not sure how you guys have been working on this software for so long without noticing that the most basic functionality is broken but good job.

**Comment by yls4** [comment]
The issue is caused by the upload theme calling SHM_FORM using a make_link.  SHM_FORM also calls make_link, so make_link gets called twice, causing it to generate the incorrect link the second time.  [Great update](https://github.com/shish/shimmie2/commit/7b9c9dc208b26fe5b8e69f977352409c5c958467#diff-eae10aa3a1b027bab1a5a942bed464db124799799824e0caa66f25adfa20ea90) good testing I'm gonna be extra careful about pulling any updates from now on

**Comment by shish** [comment]
> I'm not sure how you guys have been working on this software for so long without noticing that the most basic functionality is broken but good job.

For context I'm actually one person, working on this in my spare time; and this bug was in the work-in-progress branch for 3 days out of 17 years. If you need more reliability than that, you're welcome to pay me to work on it full-time :)
