### ISSUE TITLE
"warm" theme's CustomUploadTheme class is incompatible with parent

### ISSUE THREAD

**Issue by synth-ruiner** [shish/shimmie2#865]
came across this problem while helping a friend get their Shimmie installation set up. friend was getting a white screen while trying to upload an image. found this in the logs:

```
[Mon Jan 03 13:35:08.203274 2022] [fcgid:warn] [pid 143611:tid 3873581364992] [client 68.190.169.225:61918] mod_fcgid: stderr: PHP Fatal error:  Declaration of CustomUploadTheme::display_block(Page $page) must be compatible with UploadTheme::display_block(Page $page): void in /home/dh_titstr/marikedrawinge.com/shimmie2/themes/warm/upload.theme.php on line 7
```

I was able to fix the problem by setting the function return type declarations to void in `shimmie2/themes/warm/upload.theme.php`:

```php
class CustomUploadTheme extends UploadTheme
{
    public function display_block(Page $page): void
    {
        $page->add_block(new Block("Upload", $this->build_upload_block(), "head", 20));
    }

    public function display_full(Page $page): void
    {
        $page->add_block(new Block("Upload", "Disk nearly full, uploads disabled", "head", 20));
    }
}
```

might be worth checking the other themes for this problem too!

**Comment by soujdfig** [comment]
Many of the themes are a mess. Default is ugly but works. Danbooru themes are the only ones that seem to properly replace it, though with a somewhat messy interface on some elements. Futaba would be good if it wasn't slightly messed up style-wise. Warm breaks completely until changes are made on the backend to undo the theme change.
