### ISSUE TITLE
[Question] How to change the media name 'build'? 

### ISSUE THREAD

**Issue by Taijefx34** [shish/shimmie2#868]
Sorry, I don't know where to ask question so...
Shimmie2 by default names all media¹ (posts) like a sequence of num. (1.ext, 2.ext, 3.ext etc.) 

How can I change it? (ex. the posted media¹ will be named as its original name) 
(Thumbnails too)

I saw [this](https://github.com/shish/shimmie2/wiki/Settings#image-options) and i.g. this is what I need, but I can't find it anywhere in the Shimmie2 Settings. (System)
[maybe I'm blind idk, sorry 🙈]

Can you show me pleace where it is located (and how properly change it) if that's what I need?

If its not, what's the solution for my "problem"?

¹ media - images, videos, gifs
P. s. and where's others [image options ](https://github.com/shish/shimmie2/wiki/Settings#image-options) & [related tag list ](https://github.com/shish/shimmie2/wiki/Settings#popular--related-tag-list) located.

P. p. s. I'm **very sorry** if this is kind of **stupid** question.

**Comment by Taijefx34** [comment]
Feel free to clarify what did I mean.

**Comment by Taijefx34** [comment]
And for the future, if I will have any questions, where can I ask them

**Comment by Taijefx34** [comment]
oh, and is it possible to change ab existed post media

**Comment by shish** [comment]
From the "Board Config" screen there should be a link to "Advanced", then you're looking for `image_ilink` for the image links and `image_tlink` for the thumbnail links

**Comment by Taijefx34** [comment]
Thank you so much for a reply ;)

But when I change those values, images/thumbnails just not shown (same with old and new posts).

Maybe somehow hard-reset cache or smth?

Here is screenshots, maybe I'm doing something wrong.
(I'll split them in a several comments w/ desc)

P. s. Tested on Chrome & Edge. Same problems

**Comment by Taijefx34** [comment]
![images_ilink without image 1](https://user-images.githubusercontent.com/48826466/150536790-9dae0ff2-4e7d-4ef4-a3a4-d389557808af.png)
![images_ilink without image 2](https://user-images.githubusercontent.com/48826466/150536804-d9767032-8e68-48e3-afb5-47bd722aa382.png)

In logs:
`[Fri Jan 21 182456 2022] 127.0.0.165218 [404] GET index.phpq=bt%20graphic.png`

![images_ilink without image 3](https://user-images.githubusercontent.com/48826466/150536813-e702e5a7-138a-490a-b5c4-7d3f2b5f0dbd.png)

**Comment by Taijefx34** [comment]
![Snipaste_2022-01-21_18-31-23](https://user-images.githubusercontent.com/48826466/150536974-8691b582-8069-46b5-a558-86b25b2a1054.png)

I mentioned that there is `image/` before the actual name so I tried to change it the same way but Still imagen not shows, but logs are ok

**Comment by Taijefx34** [comment]
![Snipaste_2022-01-21_18-33-40](https://user-images.githubusercontent.com/48826466/150537190-39d67072-20d7-40cf-a825-294f602857c2.png)
![Snipaste_2022-01-21_18-31-56](https://user-images.githubusercontent.com/48826466/150537203-147f4a4a-8fb2-476d-9199-4646759c4a6f.png)
![Snipaste_2022-01-21_18-36-19](https://user-images.githubusercontent.com/48826466/150537211-7d638716-e3db-462e-9896-7ad37354f847.png)

Same with thumbnail

**Comment by Taijefx34** [comment]
If I open image in a new link.

**Post not in a database**
The requested image was not found in the database.

**Comment by Taijefx34** [comment]
I tried MySQL
Same

**Comment by Danipulok** [comment]
@shish, have the same problem. Any solution please?

**Comment by shish** [comment]
Sorry for the delay - real life has been a pain D:

For image URLs, when not using niceurls, they need to begin with `image/$id` so that the server knows which image to serve - but if you don't want the ID to be part of the filename, it should also work to have it as a folder name - so eg setting `image_ilink` to `image/$id/$filename.$ext`

When using niceurls, they need to begin with the hash, so something like `_images/$hash/$filename.$ext`

**Comment by Taijefx34** [comment]
No problem. Thank you a lot for answering those quite dumb questions!
Have a nice day, keep going and don't be sad :D

P. s. maybe you should mention that in docs 👀
