### ISSUE TITLE
Fatal Error: Uncaught TypeError when attempting to upload images

### ISSUE THREAD

**Issue by applesaucyy** [shish/shimmie2#879]
**Server Software**
 - Shimmie version: 2.9.1
 - Database: MySQL
 - Web server: Apache (XAMPP)

**Client Software (please complete the following information)**
 - Device: Windows/Linux
 - Browser: Vivaldi/Chrome/Firefox

**What steps trigger this bug**
Attempting to upload any image 

**What did you expect to happen?**
A post to appear

**What actually happened?**
`Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, null given in D:\Downloads\shimmie2\themes\lite\page.class.php:114 Stack trace: #0 D:\Downloads\shimmie2\themes\lite\page.class.php(114): str_replace(' ', '_', NULL) #1 D:\Downloads\shimmie2\themes\lite\page.class.php(54): Page->block_to_html(Object(Block), false, 'main') #2 D:\Downloads\shimmie2\core\basepage.php(260): Page->render() #3 D:\Downloads\shimmie2\index.php(83): BasePage->display() #4 {main} thrown in D:\Downloads\shimmie2\themes\lite\page.class.php on line 114`

I don't know if i'm stupid or what but i get this error whenever i try to upload any images to my test instance. this happens independent of filesize, and it happens on all pages until i delete the image from the SQL database. what could be causing this issue?

**Comment by shish** [comment]
This should be fixed in 818ea626
