### ISSUE TITLE
Message: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'mime'

### ISSUE THREAD

**Issue by BoniDobes** [shish/shimmie2#887]
Message: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'mime'

Internal Error
Message: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'mime'

Query:

Version: 2.9.1+ (on 7.4.26)

Stack Trace:

#0 D:\server\ext\upgrade\main.php(172): Database->execute('ALTER TABLE ima...')
#1 D:\server\core\send_event.php(113): Upgrade->onDatabaseUpgrade(Object(DatabaseUpgradeEvent))
#2 D:\server\index.php(72): send_event(Object(DatabaseUpgradeEvent))
#3 {main}

**Server Software**
WAMPserver version 3.2.6 64 bit compiled for windows PC.
 - Shimmie version: Stated in error I think?
 - Database: [mysql, postgres, ...] MySQL (also MariaDB, but that doesn't apply here, I tried to use MySQL)
 - Web server: [apache, nginx, ...] Apache with PHP.

**Client Software (please complete the following information)**
 - Device: [e.g. iphone, windows desktop] Windows 11 Professional Edition on Desktop PC.
 - Browser: [e.g. chrome, safari] Attempted in: Google Chrome, Mozilla Firefox, Microsoft Edge even.

**What steps trigger this bug**
Installing Shimmie and then trying to run localhost.

**What did you expect to happen?**
1: I download shimmie.
2: I extract from ZIP.
3: I place in server folder that WAMPserver is set to serve as host (localhost which is linked to d:/server/)
4: I load http://localhost/
5: I install shimmie.
6: I load shimmie, it runs for me.

**What actually happened?**
1: I have a hell of a time finding the ZIP, but get it.
2: WAMPserver likes to pull stupid bullshit with virtual hosts, I sort that out.
3: I extract ZIP contents and place them in the folder finally.
4: I get an error trying to install, turns out it needs me to require a password. (wampserver gives username root and no password by default). (this is stupid because phpbb doesn't give me this kind of problem btw)
5: I set a password and install.
6: I load localhost, I get the error stated above.

**Comment by shish** [comment]
My first thought is - were there multiple attempts to go through the install process? It sounds like part of the database is already there, but it didn't complete (specifically, it sounds like it put some stuff in the database, but didn't write `data/config/shimmie.conf.php` to flag "database is ready, here's how to connect to it")

So questions -- does `<install folder>/data/config/shimmie.conf.php` exist? And is there an option to nuke the database and start from blank in case there's some half-installed tables there? Another potential option - is sqlite an available database engine in the install screen? That might be more suitable than mysql for the localhost-install use-case....

**Comment by BoniDobes** [comment]
You are correct, good sir/maam! I manually inserted the database entry "shimmie" why? because without doing that, I get this: 

PDO Error:
An error occurred while trying to create the database tables necessary for Shimmie.

Please check and ensure that the database configuration options are all correct.

SQLSTATE[HY000][1049]  Unnknown database 'shimmie'

So, what did I do exactly that led up to THAT error? I tried to install without manually entering shimmie.

In the dropdown menu: 
Type: MySQL 

Host: localhost
username: root
password: password (this is for LAN usage, I don't need a better pw)
DB Name: shimmie

And I click Go!

And error.

I enter the database, I get an error.

Help!

**Comment by shish** [comment]
Sorry for dropping the ball here - if this is still an issue, feel free to re-open >.<
