### ISSUE TITLE
General error: 1709 Index column size too large. The maximum column size is 767 bytes. 

### ISSUE THREAD

**Issue by BerryTheCat2** [shish/shimmie2#891]
**Server Software**

 - Shimmie version: 2.9.2
 - Database: MySQL
 - Web server: localhost

**Client Software**
 - Device: Windows
 - Browser: Firefox

**What steps trigger this bug**
1. Set up Shimmie
2. Enter database info and click installl

**What did you expect to happen?**
The program to be usable.

**What actually happened?**
[screenshot](https://media.discordapp.net/attachments/1015082352411672597/1039326789975146547/Screenshot_2022-11-07_6.46.33_PM.png)
The arrow thing at the right is because I'm using Google Remote Desktop.

**Comment by shish** [comment]
Sorry for dropping the ball here - if this is still an issue, feel free to re-open >.<
