### ISSUE TITLE
Unable to upgrade to latest version

### ISSUE THREAD

**Issue by loudhouse** [shish/shimmie2#897]
I am unable to upgrade my installation to the latest version without an HTTP 500 error resulting in being unable to load any pages. I upgraded my PHP version to 8.1 in order to support it.
Currently, my site is running on an older version of Shimmie with PHP 7.4.
The problem appears to lie with the existing data/config/shimmie.conf.php file containing the database information, as when this is removed the site will load without the 500 error (though it prompts you to install Shimmie as if it were a fresh install, and Shimmie will only accept a clean DB that isn't already populated for installation).
I would appreciate any assistance with this. Thank you.

**Comment by shish** [comment]
Do the server logs contain any error messages?

Is there anything in `data/config/...` other than `shimmie.conf.php`, and does `shimmie.conf.php` contain anything other than the database connection string?

Do you have any other custom files / extensions?

If you have CLI access, does `php index.php` show anything?

**Comment by loudhouse** [comment]
Thank you for your help.
Upon further troubleshooting, I realized that the problem is _actually_ with the file user-classes.conf.php which I have in my /data/config folder, containing parameters relating custom user classes and permissions that are necessary for the wanted functionality of my site.
Has the functionality of this file been changed or removed in the latest version?
`<?php
new UserClass("moderator", "user", [
	Permissions::DELETE_IMAGE => True,
	Permissions::DELETE_COMMENT => True,
	Permissions::MANAGE_ALIAS_LIST => True,
	Permissions::MANAGE_AUTO_TAG => True,
	Permissions::MASS_TAG_EDIT => True,
	Permissions::REPLACE_IMAGE => True,
	Permissions::EDIT_IMAGE_LOCK => True,
	Permissions::BULK_EDIT_IMAGE_TAG => True,
	Permissions::BULK_EDIT_IMAGE_SOURCE => True,
	Permissions::BAN_IMAGE => True,
	#Permissions::IGNORE_DOWNTIME => True,
	Permissions::PERFORM_BULK_ACTIONS => True,
	Permissions::BULK_EDIT_IMAGE_RATING => True,
	Permissions::BULK_ADD => True,
	Permissions::EDIT_TAG_CATEGORIES => True,
	Permissions::BIG_SEARCH => True,
]);
new UserClass("uploader", "base", [
    Permissions::BIG_SEARCH => true,
    Permissions::CREATE_IMAGE => true,
    Permissions::CREATE_COMMENT => true,
    Permissions::EDIT_IMAGE_TAG => true,
    Permissions::EDIT_IMAGE_SOURCE => true,
    Permissions::EDIT_IMAGE_TITLE => true,
    Permissions::EDIT_IMAGE_RELATIONSHIPS => true,
    Permissions::EDIT_IMAGE_ARTIST => true,
    Permissions::CREATE_IMAGE_REPORT => true,
    Permissions::EDIT_IMAGE_RATING => true,
    Permissions::EDIT_FAVOURITES => true,
    Permissions::SEND_PM => true,
    Permissions::READ_PM => true,
    Permissions::SET_PRIVATE_IMAGE => true,
    Permissions::BULK_DOWNLOAD => true,
    Permissions::CHANGE_USER_SETTING => true
]);
new UserClass("user", "base", [
    Permissions::BIG_SEARCH => true,
    Permissions::CREATE_COMMENT => true,
    Permissions::EDIT_FAVOURITES => true,
    Permissions::SEND_PM => true,
    Permissions::READ_PM => true,
    Permissions::BULK_DOWNLOAD => true,
    Permissions::CHANGE_USER_SETTING => true
]);`
These are the custom settings which I have in it.

**Comment by shish** [comment]
Ah, I think that needs to have `namespace Shimmie2;` added after `<?php` - sorry about that, I will see if I can automate that upgrade step for future people...

**Comment by loudhouse** [comment]
Thanks very much. This has resolved the issue. 
There does, however, seem to be a related issue with my custom theme, though, appending `namespace Shimmie2;` to the beginning of the theme's php files after `<?php` does not seem to resolve it in this case.

**Comment by shish** [comment]
f15407bc7516b5aa07b8632b2e89673a4188b188 added some config options to the varnish purge extension - I wonder if the default settings are giving the wrong results for you, and does it work when set correctly?

**Comment by loudhouse** [comment]
Strangely, modifying the config does not seem to affect the behavior of the extension (for example, it still displays 127.0.0.1 as the IP in the Nginx error, despite having changed the IP in the config to 127.0.1.1).
It behaves as expected when reverting it to the old version of the extension without the config options.

**Comment by loudhouse** [comment]
> There does, however, seem to be a related issue with my custom theme, though, appending `namespace Shimmie2;` to the beginning of the theme's php files after `<?php` does not seem to resolve it in this case.

The issue with my theme was something to do with the page.class.php file - replacing it with the latest version of the original from the theme upon which mine was based seems to have resolved the issue and has not created any visual issues with the theme.

**Comment by shish** [comment]
Sorry for dropping the ball here - if there are any problems remaining, feel free to open new issues ^^
