### ISSUE TITLE
Fatal error: Uncaught TypeError: Block::__construct(): Argument #2 ($body) must be of type ?string, MicroHTML\HTMLElement given

### ISSUE THREAD

**Issue by AstroAntics** [shish/shimmie2#911]
Steps to reproduce (Git commit hash `522b57da`):

1) Download and install shimmie2.
2) Create a new account and go into the Admin Panel.
3) Try to change the theme.
4) The error occurs on every page.

I've attached some screenshots to show that and the last couple lines of the error log. I'm going to take a crack at fixing it.

<img width="1436" alt="Screen Shot 2023-04-12 at 2 09 37 PM" src="https://user-images.githubusercontent.com/54302245/231366732-871d8a8a-38da-4955-80f1-242ded37d99c.png">

Error log (normal content, and then the last couple of errors)

**This bit is normal content**
[Wed Apr 12 14:01:20 2023] [::1]:55064 [200]: GET /ext/autocomplete/lib/jquery.tagit.css
[Wed Apr 12 14:01:20 2023] [::1]:55064 Closing
[Wed Apr 12 14:01:20 2023] [::1]:55065 Accepted
[Wed Apr 12 14:01:20 2023] [::1]:55065 [200]: GET /nicetest
[Wed Apr 12 14:01:20 2023] [::1]:55065 Closing
[Wed Apr 12 14:01:27 2023] [::1]:55072 Accepted
[Wed Apr 12 14:01:27 2023] [::1]:55072 [302]: POST /index.php?q=setup/save
[Wed Apr 12 14:01:27 2023] [::1]:55072 Closing
[Wed Apr 12 14:01:27 2023] [::1]:55074 Accepted

**Everything here is the error**

```
[Wed Apr 12 14:01:27 2023] PHP Fatal error:  Uncaught TypeError: Block::__construct(): Argument #2 ($body) must be of type ?string, MicroHTML\HTMLElement given, called in /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php on line 9 and defined in /Users/astroantics/Downloads/shimmie2-1/core/block.php:46
Stack trace:
#0 /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php(9): Block->__construct('Upload', Object(MicroHTML\HTMLElement), 'head', 20)
#1 /Users/astroantics/Downloads/shimmie2-1/ext/upload/main.php(177): CustomUploadTheme->display_block(Object(Page))
#2 /Users/astroantics/Downloads/shimmie2-1/core/send_event.php(115): Upload->onPageRequest(Object(PageRequestEvent))
#3 /Users/astroantics/Downloads/shimmie2-1/index.php(82): send_event(Object(PageRequestEvent))
#4 {main}
  thrown in /Users/astroantics/Downloads/shimmie2-1/core/block.php on line 46
[Wed Apr 12 14:01:27 2023] [::1]:55074 [200]: GET /index.php?q=setup&flash=Config%20saved - Uncaught TypeError: Block::__construct(): Argument #2 ($body) must be of type ?string, MicroHTML\HTMLElement given, called in /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php on line 9 and defined in /Users/astroantics/Downloads/shimmie2-1/core/block.php:46
Stack trace:
#0 /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php(9): Block->__construct('Upload', Object(MicroHTML\HTMLElement), 'head', 20)
#1 /Users/astroantics/Downloads/shimmie2-1/ext/upload/main.php(177): CustomUploadTheme->display_block(Object(Page))
#2 /Users/astroantics/Downloads/shimmie2-1/core/send_event.php(115): Upload->onPageRequest(Object(PageRequestEvent))
#3 /Users/astroantics/Downloads/shimmie2-1/index.php(82): send_event(Object(PageRequestEvent))
#4 {main}
  thrown in /Users/astroantics/Downloads/shimmie2-1/core/block.php on line 46
[Wed Apr 12 14:01:27 2023] [::1]:55074 Closing
[Wed Apr 12 14:01:57 2023] [::1]:55108 Accepted
[Wed Apr 12 14:01:57 2023] PHP Fatal error:  Uncaught TypeError: Block::__construct(): Argument #2 ($body) must be of type ?string, MicroHTML\HTMLElement given, called in /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php on line 9 and defined in /Users/astroantics/Downloads/shimmie2-1/core/block.php:46
Stack trace:
#0 /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php(9): Block->__construct('Upload', Object(MicroHTML\HTMLElement), 'head', 20)
#1 /Users/astroantics/Downloads/shimmie2-1/ext/upload/main.php(177): CustomUploadTheme->display_block(Object(Page))
#2 /Users/astroantics/Downloads/shimmie2-1/core/send_event.php(115): Upload->onPageRequest(Object(PageRequestEvent))
#3 /Users/astroantics/Downloads/shimmie2-1/index.php(82): send_event(Object(PageRequestEvent))
#4 {main}
  thrown in /Users/astroantics/Downloads/shimmie2-1/core/block.php on line 46
[Wed Apr 12 14:01:57 2023] [::1]:55108 [200]: POST /index.php?q=setup/save - Uncaught TypeError: Block::__construct(): Argument #2 ($body) must be of type ?string, MicroHTML\HTMLElement given, called in /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php on line 9 and defined in /Users/astroantics/Downloads/shimmie2-1/core/block.php:46
Stack trace:
#0 /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php(9): Block->__construct('Upload', Object(MicroHTML\HTMLElement), 'head', 20)
#1 /Users/astroantics/Downloads/shimmie2-1/ext/upload/main.php(177): CustomUploadTheme->display_block(Object(Page))
#2 /Users/astroantics/Downloads/shimmie2-1/core/send_event.php(115): Upload->onPageRequest(Object(PageRequestEvent))
#3 /Users/astroantics/Downloads/shimmie2-1/index.php(82): send_event(Object(PageRequestEvent))
#4 {main}
  thrown in /Users/astroantics/Downloads/shimmie2-1/core/block.php on line 46
```

**This bit is the immediate stack trace**
```
Stack trace:
#0 /Users/astroantics/Downloads/shimmie2-1/themes/warm/upload.theme.php(9): Block->__construct('Upload', Object(MicroHTML\HTMLElement), 'head', 20)
#1 /Users/astroantics/Downloads/shimmie2-1/ext/upload/main.php(177): CustomUploadTheme->display_block(Object(Page))
#2 /Users/astroantics/Downloads/shimmie2-1/core/send_event.php(115): Upload->onPageRequest(Object(PageRequestEvent))
#3 /Users/astroantics/Downloads/shimmie2-1/index.php(82): send_event(Object(PageRequestEvent))
#4 {main}
  thrown in /Users/astroantics/Downloads/shimmie2-1/core/block.php on line 46
```

=======

**Attempted Solutions**
1) I commented out `declare(strict_types=1)` from the top of /core/block.php and made $body `string` instead of `?string`. It did not work. Though the error I got was `
Fatal error: Type of SetupBlock::$body must be string (as in class Block) in /Users/astroantics/Downloads/shimmie2-1/ext/setup/main.php on line 0` instead.

2) I removed `?string` from the `$body` declaration in core.block.php (lines 20 and 46). Got the same error as number 1 above (and no, it did not work either). 

3) I changed `public ?string` to `public ?MicroHTML\HTMLElement` in line 22 on core/block.php and `string $body = null` to `MicroHTML\HTMLElement` on line 48 of the same file. The error I got was `Fatal error: Type of SetupBlock::$body must be ?MicroHTML\HTMLElement (as in class Block) in /Users/astroantics/Downloads/shimmie2-1/ext/setup/main.php on line 0`.

The complete error log is pretty big, so I uploaded it in a Pastebin here: (https://pastebin.com/z0b8HfFB)

**Comment by AstroAntics** [comment]
Just bumping this in a new post to show my system information (you can ignore the first bit, I cloned another copy and created a new board instead of fixing the old one because I only had one image inside it):

`about:
  title: "Shimmie"
  theme: "default" <-- I won't change this until the bug gets fixed as it'll otherwise break everything!
  url: "http://localhost:9999/index.php?q="

versions:
  shimmie: "2.10.0-alpha+"
  schema: 21
  php: "8.1.10"
  db: "pgsql PostgreSQL 14.3 on x86_64-apple-darwin20.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit"
  os: "Darwin MacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64"
  server: "PHP 8.1.10 Development Server"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: []
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 1
  comments: 1
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "226.6GB"
  disk_total: "228.3GB"

thumbnails:
  engine: "gd"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: "b5b7fe7d"
  branch: "master"
  origin: "https://github.com/shish/shimmie2.git"

`

**Comment by AstroAntics** [comment]
bump

**Comment by shish** [comment]
This was fixed a while ago and I forgot to mention here ^^;;
