### ISSUE TITLE
Images on docker hub do not include stable versions

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#925]
Typically it is good practice to provide at least the last stable version (as of this writing, 2.9.2) with your available Docker images, so that users can run a known release, test against it for regressions, report issues, etc. Running the "latest" release (the only one) has an unknown set of changes from the last stable release, and makes it hard to know if something is truly an issue or merely in-development. Adding such a release should be a matter of building the Docker image from the github release and tagging it. I've done so myself locally, but this is something that really belongs on Docker Hub, and is a one-time thing for the maintainer to do.

While Shimmie is mostly working well and I now have a library of several thousand images in it, I have run into a few additional problems beyond my initial flurry of bug reports. However, since there does not appear to be any active development or monitoring of these issues, it's rather hard to justify the effort of writing them up if they do no good.

**Comment by shish** [comment]
That seems reasonable; I've been focused on the latest image since all the sites I'm running use that, but then I'm in a pretty good place to debug and fix issues that occur ^^;

(And yeah, development is somewhat bursty as my open-source work is trying to fit around my day job and life in general)

**Comment by shish** [comment]
There are now semver docker tags on docker hub, so you can choose your preferred level of stability (2.X.X, 2.9.X, or 2.9.3) - older versions aren't included as they no longer build. Putting out a new 2.8.X / 2.7.X release might be possible, but a bunch more effort, so I'd only do that if specifically needed

**Comment by diamondsw** [comment]
Thanks, I see the tags, and they're very much appreciated. Since there's issues to be tested I've shifted back to the ":latest" tag from my self-build 2.9.2 stable. Things are looking good!
