### ISSUE TITLE
Searches work from homepage search field, but fail from "posts" page search field when using Nice URLs

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#930]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://booru.redacted.com/"

versions:
  shimmie: "2.10.0-alpha"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 11.20 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit"
  os: "Linux 989667cbfe21 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64"
  server: "PHP 8.2.7 Development Server"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","bulk_add_csv","favorites","home","pools","random_image","random_list","rating","regen_thumb","relationships","tag_categories"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 17004
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "174.7GB"
  disk_total: "196.7GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

**What steps trigger this bug**
This may be related to an interaction between the tag_categories plugin (or any search with "special characters" like rating) and the "Nice URLs" setting.
1. From the homepage, search for a known existing tag with special characters, like "rating:e" or "artist:haruhisky". This creates a link of the form "https://booru.redacted.com/post/list/rating%3Ae/1" or "https://booru.redacted.com/post/list/artist%3Aharuhisky/1", which works as expected.
2. From the posts page, execute the same search.

**What did you expect to happen?**
I'd expect the same URL to be created by the search on both screens, and the same resulting list of results.

**What actually happened?**
This now results in a different URL format ("https://booru.redacted.com/home?search=rating%3Ae&q=%2Fpost%2Flist" and "https://booru.redacted.com/home?search=artist%3Aharuhisky&q=%2Fpost%2Flist") which fails.

(Presumably this is the 404 error that #929 is seeing, but on the Docker image it oddly redirects to the home page of the site!)

This may be related to c5273c4 in #919, and related to #929. Turning off "Nice URLs" works as expected, and I noticed a "blink and you'll miss it" redirect, what looked like from the search URL to the post URL.

**Comment by shish** [comment]
I think you have "main page" set to "/home"? Normally I'd expect "front page = /home" and "main page = /post/list" -- but setting it that way would hide this bug rather than fixing it

**Comment by diamondsw** [comment]
Yes, front page is "home" and main page is "home".
