### ISSUE TITLE
Safari shows "Full Size" images below the sidebar, rather than next to it

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#939]
**Server Software**
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://booru.redacted.com/index.php?q="

versions:
  shimmie: "2.10.0-alpha"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 11.20 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit"
  os: "Linux 989667cbfe21 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64"
  server: "PHP 8.2.7 Development Server"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","bulk_add_csv","favorites","home","pools","random_image","random_list","rating","regen_thumb","relationships","tag_categories"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 17008
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "175.5GB"
  disk_total: "196.7GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

**Client Software (please complete the following information)**
 - MacOS Ventura 13.4.1
 - Safari 16.5.1

**What steps trigger this bug**
View a post that is larger than the current browser viewport.
Under "Post Controls", change it to "Full Size" view.

**What did you expect to happen?**
In Chrome, this shows the image at full size to the right of the sidebar.

**What actually happened?**
In Safari, the full size image is shown to the right **and below** the sidebar. I'm sure it's some CSS layout issue, but these days I can't tell if it's "Safari is borked" or "Everyone codes to Chrome and not standards".

Screenshot: https://imgur.com/a/gwbQ3oz

**Comment by shish** [comment]
I'm not sure what changed, but there have been a whole load of CSS updates recently and I can no longer repro this - feel free to re-open if it's still an issue and we can dig some more...

**Comment by diamondsw** [comment]
Confirmed; this odd behavior no longer occurs - thank you!
