### ISSUE TITLE
Pagination sometimes uses "..." when not necessary

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#940]
**Server Software**

**Client Software (please complete the following information)**
 - MacOS Ventura 13.4.1
 - Safari 16.5.1

**What steps trigger this bug**
1. View a list of posts that has 4 pages of results

**What did you expect to happen?**
The pagination at the bottom should be [1] [2] [3] [4] >>.

**What actually happened?**
The pagination at the bottom actually is [1] [2] [3] ... [4] >>. Somewhere in the code it thinks it needs to collapse the page results - but in reality it can show all of them. If there are more results, then it appropriately shows [1] [2] [3] ... [5] >>.

**Comment by shish** [comment]
My brain is too splat for mat right now, but this looks to be specific to the danbooru2 theme - `themes/danbooru2/themelet.class.php :: build_paginator`

**Comment by diamondsw** [comment]
Heh, I feel you! Off-by-one errors are such a pain in the butt (because that's clearly what this will end up being).
