### ISSUE TITLE
Request: Option to Retrieve Nice URL for an image even if not set. (For sharing images in Discord)

### ISSUE THREAD

**Issue by OhGodItsBroken** [shish/shimmie2#946]
This is a very specific problem, but anyone who shares images in a discord channel might relate.

If Nice URLs is OFF, still images, webms, and mp4s will display in our discord channel without issue, but gifs will only load the first frame.
If Nice URLs is ON, still images and gifs work, but videos like webm and mp4 will only diplay a URL. Clicking on the URL to view onsite works, but we're trying to share things in the discord channel.

The simplest solution I can think of is a setting to make the Nice URL of an image available upon request even if the site is not running Nice URLs by default.

Someone more experienced with how Discord loads images from external sites might have a more elegant solution, but I'm a novice at all this.

**Comment by shish** [comment]
That sounds like a webserver configuration issue, presumably the direct and indirect file serving methods are setting different headers somewhere, but they _should_ be the same - can you use the web inspector to check headers in each case and see what's different there?

**Comment by OhGodItsBroken** [comment]
I think I see the problem. The Content-type on the response header is different depending on what I'm using.
With no nice URLs, a GIF shows image/gif
But on Nice URLs, the Content-Type is set to image/jpeg

Similarly, with a WEBM, the Content-type is image/jpeg on Nice URLs and video/webm without.

It might be best to share my system info at this point.

> about:
  title: "spambooru"
  theme: "danbooru"
  url: "http://booru.example.com/"

> versions:
  shimmie: "2.10.0-alpha"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit"
  os: "Linux f74bb2d5fe8b 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64"
  server: "PHP 8.2.7 Development Server"

> extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["handle_video"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]

> stats:
  images: 20
  comments: 0
  users: 4

> media:
  memory_limit: "8.0MB"
  disk_use: "24.1GB"
  disk_total: "149.9GB"

> thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

I'm using a Docker setup with a proxy pass/reverse proxy pass in apache2. I'm guessing I need to do something in the apache conf to make sure the content type gets passed through correctly.
I'm looking into it. If you have any advice, please let me know.

**Comment by OhGodItsBroken** [comment]
Okay, I have a solution that is working for me. GIF, WEBM, MP4, and still images all display in the discord window.

My solution was to just remove the Content-Type from the header entirely by putting these lines in the apache conf.

`Header set Content-Type ""`
`Header unset Content-Type`

Taken from the advice found here
https://stackoverflow.com/questions/2428563/how-can-i-prevent-apache2-from-setting-the-content-type-header

Both lines were necessary to remove the content-type from the header, and prevent it from setting a default one.
