### ISSUE TITLE
Cron Uploader

### ISSUE THREAD

**Issue by ryfon** [shish/shimmie2#972]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version: 2.10.0-alpha+
 - Database: mysql 10.11.4-MariaDB-1~deb12u1
 - Web server: Apache/2.4.57 (Debian)

**Client Software (please complete the following information)**
 - Device: Windows desktop
 - Browser: Firefox

**What steps trigger this bug**
1. Upload files to queue folder
2. After cron runs uploaded and failed information page counts folders.
3. Under Board Admin clear uploaded and failed folders

![image](https://github.com/shish/shimmie2/assets/1157094/1e442586-9b02-42f3-9984-6ebc14447975)

**What did you expect to happen?**
Uploaded and failed information page should not count folders.
Clear uploaded and failed folders should remove folders.

**What actually happened?**
Folders remain and counted on cron information page.
This causes the most problems on failed folder. Under board admin failed dir never gets fully removed and list slowly fills up until folder is manually cleared.

**Comment by shish** [comment]
I am unable to reproduce this - can you show exactly what is in your `data/cron_uploader` folder when you see errors on the admin screen?

eg running `find data/cron_uploader` on my test server is showing:
```
# find data/cron_uploader/
data/cron_uploader/
data/cron_uploader/demo
data/cron_uploader/demo/.lock
data/cron_uploader/demo/uploaded
data/cron_uploader/demo/uploaded/20240104-190002
data/cron_uploader/demo/uploaded/20240104-190002/subdir
data/cron_uploader/demo/uploaded/20240104-190002/subdir/favicon.png
data/cron_uploader/demo/uploaded/20240104-185411
data/cron_uploader/demo/uploaded/20240104-185411/subdir
data/cron_uploader/demo/uploaded/20240104-185411/subdir/pbx_screenshot.jpg
data/cron_uploader/demo/failed_to_upload
data/cron_uploader/demo/failed_to_upload/testfaildir
data/cron_uploader/demo/failed_to_upload/testfaildir/subdoir
data/cron_uploader/demo/failed_to_upload/20240104-190019
data/cron_uploader/demo/failed_to_upload/20240104-190019/subdir
data/cron_uploader/demo/failed_to_upload/20240104-190019/subdir/index.php
data/cron_uploader/demo/queue
data/cron_uploader/demo/queue/subdir
data/cron_uploader/demo/uploads.log
```
Then the counts on the table correctly show the number of files without counting directories. Then when I push the buttons to clear each of them, both the files and the empty folders are cleared:
```
# find data/cron_uploader/
data/cron_uploader/
data/cron_uploader/demo
data/cron_uploader/demo/.lock
data/cron_uploader/demo/uploaded
data/cron_uploader/demo/failed_to_upload
data/cron_uploader/demo/queue
data/cron_uploader/demo/queue/subdir
data/cron_uploader/demo/uploads.log
```

**Comment by ryfon** [comment]
Before clear
`data/cron_uploader
data/cron_uploader/.listing
data/cron_uploader/ryfon
data/cron_uploader/ryfon/failed_to_upload
data/cron_uploader/ryfon/failed_to_upload/20240105-130325
data/cron_uploader/ryfon/failed_to_upload/20240105-130325/.listing
data/cron_uploader/ryfon/failed_to_upload/20240105-130325/animated
data/cron_uploader/ryfon/failed_to_upload/20240105-130325/animated/.listing
data/cron_uploader/ryfon/failed_to_upload/20240105-130325/animated/13B7E3EC7C0C6ECD2B79D5789986945D.gif
data/cron_uploader/ryfon/failed_to_upload/.listing
data/cron_uploader/ryfon/queue
data/cron_uploader/ryfon/queue/animated
data/cron_uploader/ryfon/uploads.log
data/cron_uploader/ryfon/.listing
data/cron_uploader/ryfon/uploaded
data/cron_uploader/ryfon/uploaded/.listing
data/cron_uploader/ryfon/.lock`

After clear
`data/cron_uploader
data/cron_uploader/.listing
data/cron_uploader/ryfon
data/cron_uploader/ryfon/failed_to_upload
data/cron_uploader/ryfon/failed_to_upload/20240105-130325
data/cron_uploader/ryfon/failed_to_upload/20240105-130325/.listing
data/cron_uploader/ryfon/failed_to_upload/20240105-130325/animated
data/cron_uploader/ryfon/failed_to_upload/20240105-130325/animated/.listing
data/cron_uploader/ryfon/failed_to_upload/.listing
data/cron_uploader/ryfon/queue
data/cron_uploader/ryfon/queue/animated
data/cron_uploader/ryfon/uploads.log
data/cron_uploader/ryfon/.listing
data/cron_uploader/ryfon/uploaded
data/cron_uploader/ryfon/uploaded/.listing
data/cron_uploader/ryfon/.lock`

The only difference I see from your test to mine are these .listing files that automatically get created. not sure what is creating those, they are owned by www-data so it shouldn't have any issues removing them.

**Comment by shish** [comment]
Looks like .listing files are created when wget is used to download files from an FTP server with the `--no-remove-listing` flag set -- is that what you're using the fill up the `queue` folder?

Either way I agree, the "clear out these folders" buttons should remove the .listing files
