### ISSUE TITLE
/ext/system/main.php references function 'sort_nav_links' which does not exist -> HTTP 500 when navigating to /system

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#986]
Navigating to /system using the Danbooru theme therefore results in HTTP 500 and /var/log/unit.log shows:
`
2024/01/02 19:42:19 [notice] 71#71 [unit] #29: php message: PHP Fatal error:  Uncaught TypeError: usort(): Argument #2 ($callback) must be a valid callback, function "Shimmie2\sort_nav_links" not found or invalid function name in /app/ext/system/main.php:15
Stack trace:
#0 /app/ext/system/main.php(15): usort()
#1 /app/core/send_event.php(156): Shimmie2\System->onPageRequest()
#2 /app/index.php(85): Shimmie2\send_event()
#3 {main}
  thrown in /app/ext/system/main.php on line 15
`

f00a4e3 removed function sort_nav_links in /core/basepage.php. However, /ext/system/main.php:15 still references that function:
`usort($e->links, "Shimmie2\sort_nav_links");`

**Comment by shish** [comment]
Thanks for catching that (I wonder how the static analysis didn't o.o), fix is landing now :)
