### ISSUE TITLE
Source link does not get set when transloading images

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#989]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

-   Shimmie version: 2.10.0-alpha
-   Database: pgsql PostgreSQL 15.5
-   Web server: PHP 8.2.7 Development Server

**Client Software (please complete the following information)**

-   Device: windows/linux desktop
-   Browser: Firefox, MS Edge

**What steps trigger this bug**
1. In System > Board Config, under Upload, choose cURL or fopen for transloading and check option "Use transloaded URL as source if none is provided", then save
2. go to Upload, fill in tags and "or URL", leave "common source" and "post-specific source" fields blank, then upload

**What did you expect to happen?**
The image gets posted with "source link" set to the image URL entered in "or URL" when uploading

**What actually happened?**
The image gets posted with "source link" being "Unknown". "Source link" is only set if "post-specific source" field is filled out ("common source" is also not used).

Tested this with both cURL and fopen and images from https://apod.nasa.gov/ - could not test with wget because it keeps complaining about hotlink protection with every image I try, even from wikimedia.

**Comment by shish** [comment]
Thanks for the report, 87368ac56a86381521f8de030d467d44ee7d5330 should fix that, please reopen if not :)

**Comment by Giraffaman** [comment]
yup that fixes it - thank you :)
