### ISSUE TITLE
(Ratings) page numbers do not get updated if Default Rating Filter is used

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#991]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version: 2.10.0-alpha 
 - Database: pgsql PostgreSQL 15.5
 - Web server: PHP 8.2.7 Development Server

**Client Software (please complete the following information)**
 - Device: windows/linux desktop
 - Browser: Firefox, MS Edge
 
**What steps trigger this bug**
1. Have images of rating A and images of rating B
2. Set Account > User Options > Default Rating Filter to only A or B, then save

**What did you expect to happen?**
The paginator at /post/list should reflect the amount of pages filled with images of the chosen rating. 

**What actually happened?**
Suppose we have 30 images total, two of which are rating "public" and 28 have rating "safe". Each page displays 10 images, so three pages total:
![image](https://github.com/shish/shimmie2/assets/56076467/73317117-320f-49f2-b05c-6d98a9721859)
![image](https://github.com/shish/shimmie2/assets/56076467/a4f5a445-0891-4374-8e7d-b1eba95fdfe7)

After setting the default rating filter to rating "public" only, the paginator still shows three pages despite only two images matching that rating:
![image](https://github.com/shish/shimmie2/assets/56076467/c3d22cd0-51d0-400e-9cd9-3a0a65d3779f)

Clicking on page 2 or 3 results in "No Posts Found".
![image](https://github.com/shish/shimmie2/assets/56076467/3ffa880b-c71f-47ee-b1fb-ffa2bc379884)

Note: 
when using the search box and searching for "rating=p", the paginator is updated to show the correct number of pages filled by images of rating "public":
![image](https://github.com/shish/shimmie2/assets/56076467/0277338d-5192-46a4-83e1-f8299045be9b)

**Comment by shish** [comment]
Do you have either SPEED_HAX or CACHE_DSN set?

**Comment by shish** [comment]
Actually also I wonder exactly what version is being used, because something like this was fixed recently o.o

(If the latest release doesn't fix it completely, it should at least have a more specific version number on /system_info)

**Comment by Giraffaman** [comment]
> Do you have either SPEED_HAX or CACHE_DSN set?

no my shimmie.conf.php currently just has database_DSN set.

**Comment by Giraffaman** [comment]
> Actually also I wonder exactly what version is being used, because something like this was fixed recently o.o
> 
> (If the latest release doesn't fix it completely, it should at least have a more specific version number on /system_info)

I updated everything now to be sure and the versions in System Info are now:
`versions:
  shimmie: "2.10.0-beta2-unknown-unknown"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 15.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 0137e6b4d959 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64"
  server: "Unit/1.31.1"`

Maybe it reminded you of #984 - that also dealt with Ratings-related stuff which is now fixed though.

**Comment by shish** [comment]
Aha, I think I found it - 68ee4d0e77 added an implied "rating:*" into the search query but only when counting images. I'm not sure why, and there's no code comment explaining it, so I'mma remove that...

**Comment by shish** [comment]
77e88f6f should be the fix, and comes with a small unit test (there's already loads of testing for `find_images()`, and `count_images()` is just a small wrapper around that, so all we really need to test is that `count_images()` isn't messing with the query like it was up until now...)

**Comment by Giraffaman** [comment]
yes works as expected now - thank you :)
